/** @generated by scripts/gen-roster.ts from scripts/package-catalog.ts; do not hand-edit. */
// prettier-ignore
export const GENERATED_DEFAULT_ANALYZABLE_ARTIFACTS = [
  "src/**/*.ts",
  "src/**/*.tsx",
  "!src/**/*.d.ts",
] as const;
// prettier-ignore
export const GENERATED_PACKAGE_TOPOLOGY = {
  "@liteship/_spine": { kind: "standalone", allowedInternalImports: [], analyzableArtifacts: ["*.d.ts"] },
  "@liteship/error": { kind: "standalone", allowedInternalImports: [], analyzableArtifacts: ["src/**/*.ts", "src/**/*.tsx", "!src/**/*.d.ts"] },
  "@liteship/canonical": { kind: "standalone", allowedInternalImports: [], analyzableArtifacts: ["src/**/*.ts", "src/**/*.tsx", "!src/**/*.d.ts"] },
  // _spine owns shared public types; canonical owns the byte kernel core re-exports.
  "@liteship/core": { kind: "core", allowedInternalImports: ["@liteship/_spine", "@liteship/canonical"], analyzableArtifacts: ["src/**/*.ts", "src/**/*.tsx", "!src/**/*.d.ts"] },
  "@liteship/genui": { kind: "layered", allowedInternalImports: ["@liteship/canonical", "@liteship/_spine"], analyzableArtifacts: ["src/**/*.ts", "src/**/*.tsx", "!src/**/*.d.ts"] },
  "@liteship/quantizer": { kind: "layered", allowedInternalImports: ["@liteship/core"], analyzableArtifacts: ["src/**/*.ts", "src/**/*.tsx", "!src/**/*.d.ts"] },
  // Compiler and quantizer are siblings; compiler deliberately imports core only.
  "@liteship/compiler": { kind: "layered", allowedInternalImports: ["@liteship/core"], analyzableArtifacts: ["src/**/*.ts", "src/**/*.tsx", "!src/**/*.d.ts"] },
  "@liteship/web": { kind: "layered", allowedInternalImports: ["@liteship/_spine", "@liteship/core", "@liteship/genui", "@liteship/canonical"], analyzableArtifacts: ["src/**/*.ts", "src/**/*.tsx", "!src/**/*.d.ts"] },
  "@liteship/detect": { kind: "layered", allowedInternalImports: ["@liteship/core", "@liteship/error"], analyzableArtifacts: ["src/**/*.ts", "src/**/*.tsx", "!src/**/*.d.ts"] },
  "@liteship/edge": { kind: "host-adjacent", allowedInternalImports: ["@liteship/core", "@liteship/detect"], analyzableArtifacts: ["src/**/*.ts", "src/**/*.tsx", "!src/**/*.d.ts"] },
  // edge owns the boundary-manifest handoff; web owns the shared wire-event dispatcher.
  "@liteship/vite": { kind: "host-adjacent", allowedInternalImports: ["@liteship/core", "@liteship/compiler", "@liteship/edge", "@liteship/web"], analyzableArtifacts: ["src/**/*.ts", "src/**/*.tsx", "!src/**/*.d.ts"] },
  "@liteship/worker": { kind: "host-adjacent", allowedInternalImports: ["@liteship/core"], analyzableArtifacts: ["src/**/*.ts", "src/**/*.tsx", "!src/**/*.d.ts"] },
  "@liteship/remotion": { kind: "standalone", allowedInternalImports: ["@liteship/core"], analyzableArtifacts: ["src/**/*.ts", "src/**/*.tsx", "!src/**/*.d.ts"] },
  "@liteship/scene": { kind: "layered", allowedInternalImports: ["@liteship/core", "@liteship/_spine"], analyzableArtifacts: ["src/**/*.ts", "src/**/*.tsx", "!src/**/*.d.ts"] },
  // Astro owns the host bridge; scene and canonical edges serve the live SVG and docs-byte paths.
  "@liteship/astro": { kind: "host-adjacent", allowedInternalImports: ["@liteship/core", "@liteship/vite", "@liteship/detect", "@liteship/edge", "@liteship/web", "@liteship/worker", "@liteship/genui", "@liteship/scene", "@liteship/canonical"], analyzableArtifacts: ["src/**/*.ts", "src/**/*.tsx", "!src/**/*.d.ts"] },
  "@liteship/cloudflare": { kind: "host-adjacent", allowedInternalImports: ["@liteship/core", "@liteship/edge", "@liteship/astro"], analyzableArtifacts: ["src/**/*.ts", "src/**/*.tsx", "!src/**/*.d.ts"] },
  "@liteship/stage": { kind: "host-adjacent", allowedInternalImports: ["@liteship/core", "@liteship/compiler", "@liteship/astro", "@liteship/web"], analyzableArtifacts: ["src/**/*.ts", "src/**/*.tsx", "!src/**/*.d.ts"] },
  "@liteship/assets": { kind: "layered", allowedInternalImports: ["@liteship/core", "@liteship/_spine"], analyzableArtifacts: ["src/**/*.ts", "src/**/*.tsx", "!src/**/*.d.ts"] },
  "@liteship/gauntlet": { kind: "standalone", allowedInternalImports: [], analyzableArtifacts: ["src/**/*.ts", "src/**/*.tsx", "!src/**/*.d.ts"] },
  "@liteship/audit": { kind: "standalone", allowedInternalImports: ["@liteship/canonical", "@liteship/gauntlet"], analyzableArtifacts: ["src/**/*.ts", "src/**/*.tsx", "!src/**/*.d.ts"] },
  // Command owns shared host execution; assets, gauntlet, and canonical are deliberate host seams.
  "@liteship/command": { kind: "layered", allowedInternalImports: ["@liteship/core", "@liteship/assets", "@liteship/gauntlet", "@liteship/canonical"], analyzableArtifacts: ["src/**/*.ts", "src/**/*.tsx", "!src/**/*.d.ts"] },
  // CLI is the terminal host that injects audit/gauntlet facts and deployed edge expectations.
  "@liteship/cli": { kind: "host-adjacent", allowedInternalImports: ["@liteship/core", "@liteship/command", "@liteship/assets", "@liteship/audit", "@liteship/gauntlet", "@liteship/edge", "@liteship/canonical"], analyzableArtifacts: ["src/**/*.ts", "src/**/*.tsx", "!src/**/*.d.ts"] },
  // MCP projects the command catalog and compiler/UI renderers without importing CLI.
  "@liteship/mcp-server": { kind: "host-adjacent", allowedInternalImports: ["@liteship/canonical", "@liteship/core", "@liteship/command", "@liteship/compiler", "@liteship/genui", "@liteship/web"], analyzableArtifacts: ["src/**/*.ts", "src/**/*.tsx", "!src/**/*.d.ts"] },
  // The generated scaffold imports core and the core/fs-walk public subpath.
  "create-liteship": { kind: "standalone", allowedInternalImports: ["@liteship/core"], analyzableArtifacts: ["src/**/*.ts", "src/**/*.tsx", "!src/**/*.d.ts"] },
  // The facade is a dependency sink whose explicit subpaths re-export these semantic and host owners.
  "liteship": { kind: "host-adjacent", allowedInternalImports: ["@liteship/core", "@liteship/quantizer", "@liteship/gauntlet", "@liteship/compiler", "@liteship/web", "@liteship/astro", "@liteship/vite", "@liteship/genui"], analyzableArtifacts: ["src/**/*.ts", "src/**/*.tsx", "!src/**/*.d.ts"] },
} as const;
