/** GENERATED by scripts/gen-event-protocol.ts from owner-local protocol declarations. */
// prettier-ignore
export const FLEET_EVENT_PROTOCOL = Object.freeze([
  {
    "name": "liteship:adaptive-state",
    "owner": "astro",
    "channel": "dom",
    "producers": [
      "packages/astro/src/runtime/adaptive.ts"
    ],
    "description": "Adaptive boundary state crossing.",
    "catalog": "packages/astro/src/runtime/event-protocol.ts"
  },
  {
    "name": "liteship:detect-ready",
    "owner": "detect",
    "channel": "dom",
    "producers": [
      "packages/detect/src/head-probe.ts"
    ],
    "description": "Capability detection settled on either the success or error path.",
    "catalog": "packages/detect/src/event-protocol.ts"
  },
  {
    "name": "liteship:gpu-ready",
    "owner": "astro",
    "channel": "dom",
    "producers": [
      "packages/astro/src/runtime/gpu.ts"
    ],
    "description": "GPU shader runtime initialized on the directive host.",
    "catalog": "packages/astro/src/runtime/event-protocol.ts"
  },
  {
    "name": "liteship:graph-state",
    "owner": "astro",
    "channel": "dom",
    "producers": [
      "packages/astro/src/runtime/motion.ts",
      "packages/astro/src/runtime/scene-bridge.ts"
    ],
    "description": "Discrete graph-runtime state crossing on a bound element.",
    "catalog": "packages/astro/src/runtime/event-protocol.ts"
  },
  {
    "name": "liteship:llm-done",
    "owner": "astro",
    "channel": "dom",
    "producers": [
      "packages/astro/src/runtime/llm-session.ts"
    ],
    "description": "LLM stream finished with the final accumulated text.",
    "catalog": "packages/astro/src/runtime/event-protocol.ts"
  },
  {
    "name": "liteship:llm-error",
    "owner": "astro",
    "channel": "dom",
    "producers": [
      "packages/astro/src/runtime/llm.ts"
    ],
    "description": "Terminal LLM stream or connection failure.",
    "catalog": "packages/astro/src/runtime/event-protocol.ts"
  },
  {
    "name": "liteship:llm-frame",
    "owner": "astro",
    "channel": "dom",
    "producers": [
      "packages/astro/src/runtime/llm-session.ts"
    ],
    "description": "Structured UI frame emitted during an LLM stream.",
    "catalog": "packages/astro/src/runtime/event-protocol.ts"
  },
  {
    "name": "liteship:llm-genui",
    "owner": "astro",
    "channel": "dom",
    "producers": [
      "packages/astro/src/runtime/llm-session.ts"
    ],
    "description": "Generated-UI tree rendered from the host catalog.",
    "catalog": "packages/astro/src/runtime/event-protocol.ts"
  },
  {
    "name": "liteship:llm-start",
    "owner": "astro",
    "channel": "dom",
    "producers": [
      "packages/astro/src/runtime/llm.ts"
    ],
    "description": "LLM stream opened on the directive host.",
    "catalog": "packages/astro/src/runtime/event-protocol.ts"
  },
  {
    "name": "liteship:llm-token",
    "owner": "astro",
    "channel": "dom",
    "producers": [
      "packages/astro/src/runtime/llm-session.ts"
    ],
    "description": "Incremental LLM text token.",
    "catalog": "packages/astro/src/runtime/event-protocol.ts"
  },
  {
    "name": "liteship:llm-tool-end",
    "owner": "astro",
    "channel": "dom",
    "producers": [
      "packages/astro/src/runtime/llm-session.ts"
    ],
    "description": "LLM tool call completed.",
    "catalog": "packages/astro/src/runtime/event-protocol.ts"
  },
  {
    "name": "liteship:llm-tool-start",
    "owner": "astro",
    "channel": "dom",
    "producers": [
      "packages/astro/src/runtime/llm-session.ts"
    ],
    "description": "LLM tool call started.",
    "catalog": "packages/astro/src/runtime/event-protocol.ts"
  },
  {
    "name": "liteship:morph-rejected",
    "owner": "web",
    "channel": "dom",
    "producers": [
      "packages/web/src/morph/diff.ts"
    ],
    "description": "Morph preserve constraint violated.",
    "catalog": "packages/web/src/wire/event-protocol.ts"
  },
  {
    "name": "liteship:mutation",
    "owner": "web",
    "channel": "dom",
    "producers": [
      "packages/web/src/graph-form.ts"
    ],
    "description": "Graph mutation channel response after form submit.",
    "catalog": "packages/web/src/wire/event-protocol.ts"
  },
  {
    "name": "liteship:reinit",
    "owner": "astro",
    "channel": "dom",
    "producers": [
      "packages/astro/src/runtime/inspector/panel.ts",
      "packages/astro/src/runtime/slots.ts",
      "packages/vite/src/hmr.ts"
    ],
    "description": "Directive re-read after a live or view-transition swap.",
    "catalog": "packages/astro/src/runtime/event-protocol.ts"
  },
  {
    "name": "liteship:request-snapshot",
    "owner": "web",
    "channel": "dom",
    "producers": [
      "packages/web/src/morph/diff.ts",
      "packages/astro/src/runtime/stream.ts"
    ],
    "description": "Recovery fetch requested after morph rejection or a receipt gap.",
    "catalog": "packages/web/src/wire/event-protocol.ts"
  },
  {
    "name": "liteship:scene-update",
    "owner": "scene",
    "channel": "vite-hmr",
    "producers": [
      "packages/scene/src/dev/server.ts"
    ],
    "description": "Scene source changed while preserving the development playhead.",
    "catalog": "packages/scene/src/dev/event-protocol.ts"
  },
  {
    "name": "liteship:signal",
    "owner": "astro",
    "channel": "dom",
    "producers": [
      "packages/astro/src/runtime/stream.ts"
    ],
    "description": "SSE signal message payload from the stream directive.",
    "catalog": "packages/astro/src/runtime/event-protocol.ts"
  },
  {
    "name": "liteship:slot-mounted",
    "owner": "web",
    "channel": "dom",
    "producers": [
      "packages/web/src/slot/registry.ts"
    ],
    "description": "Slot registry registered a data-liteship-slot element.",
    "catalog": "packages/web/src/wire/event-protocol.ts"
  },
  {
    "name": "liteship:slot-unmounted",
    "owner": "web",
    "channel": "dom",
    "producers": [
      "packages/web/src/slot/registry.ts"
    ],
    "description": "Slot registry removed a slot path.",
    "catalog": "packages/web/src/wire/event-protocol.ts"
  },
  {
    "name": "liteship:state",
    "owner": "astro",
    "channel": "dom",
    "producers": [
      "packages/astro/src/runtime/boundary.ts"
    ],
    "description": "Boundary state crossing with CSS, ARIA, and uniform detail.",
    "catalog": "packages/astro/src/runtime/event-protocol.ts"
  },
  {
    "name": "liteship:stream-connected",
    "owner": "astro",
    "channel": "dom",
    "producers": [
      "packages/astro/src/runtime/stream.ts"
    ],
    "description": "Stream SSE transport connected, including reconnect.",
    "catalog": "packages/astro/src/runtime/event-protocol.ts"
  },
  {
    "name": "liteship:stream-disconnected",
    "owner": "astro",
    "channel": "dom",
    "producers": [
      "packages/astro/src/runtime/stream.ts"
    ],
    "description": "Stream SSE transport disconnected before a possible retry.",
    "catalog": "packages/astro/src/runtime/event-protocol.ts"
  },
  {
    "name": "liteship:stream-error",
    "owner": "web",
    "channel": "dom",
    "producers": [
      "packages/web/src/stream/recovery.ts",
      "packages/astro/src/runtime/stream.ts"
    ],
    "description": "Stream transport, resumption, or recovery failed.",
    "catalog": "packages/web/src/wire/event-protocol.ts"
  },
  {
    "name": "liteship:stream-morph",
    "owner": "astro",
    "channel": "dom",
    "producers": [
      "packages/astro/src/runtime/stream.ts"
    ],
    "description": "Stream patch morph applied.",
    "catalog": "packages/astro/src/runtime/event-protocol.ts"
  },
  {
    "name": "liteship:teardown",
    "owner": "astro",
    "channel": "dom",
    "producers": [
      "packages/astro/src/runtime/slots.ts"
    ],
    "description": "Final directive teardown and owned-resource release.",
    "catalog": "packages/astro/src/runtime/event-protocol.ts"
  },
  {
    "name": "liteship:uniform-update",
    "owner": "web",
    "channel": "dom",
    "producers": [
      "packages/astro/src/runtime/boundary.ts",
      "packages/astro/src/runtime/scene-bridge.ts",
      "packages/astro/src/runtime/uniform-signal.ts",
      "packages/astro/src/runtime/write-continuous-map.ts",
      "packages/vite/src/hmr.ts"
    ],
    "description": "Live CSS, GLSL, WGSL, ARIA, and state values for runtime consumers.",
    "catalog": "packages/web/src/wire/event-protocol.ts"
  },
  {
    "name": "liteship:update",
    "owner": "vite",
    "channel": "vite-hmr",
    "producers": [
      "packages/vite/src/plugin.ts"
    ],
    "description": "Compiled boundary CSS or uniforms changed during development.",
    "catalog": "packages/vite/src/event-protocol.ts"
  },
  {
    "name": "liteship:wasm-error",
    "owner": "astro",
    "channel": "dom",
    "producers": [
      "packages/astro/src/runtime/wasm.ts"
    ],
    "description": "WASM kernel load failed.",
    "catalog": "packages/astro/src/runtime/event-protocol.ts"
  },
  {
    "name": "liteship:wasm-ready",
    "owner": "astro",
    "channel": "dom",
    "producers": [
      "packages/astro/src/runtime/wasm.ts"
    ],
    "description": "WASM kernels loaded onto the browser host.",
    "catalog": "packages/astro/src/runtime/event-protocol.ts"
  },
  {
    "name": "liteship:worker-ready",
    "owner": "astro",
    "channel": "dom",
    "producers": [
      "packages/astro/src/runtime/worker.ts"
    ],
    "description": "Worker boundary runtime ready on the directive host.",
    "catalog": "packages/astro/src/runtime/event-protocol.ts"
  },
  {
    "name": "liteship:worker-state",
    "owner": "astro",
    "channel": "dom",
    "producers": [
      "packages/astro/src/runtime/worker.ts"
    ],
    "description": "Worker boundary state crossing.",
    "catalog": "packages/astro/src/runtime/event-protocol.ts"
  }
] as const);
