/** @generated by scripts/gen-roster.ts from scripts/package-catalog.ts; do not hand-edit. */
// prettier-ignore
export const GENERATED_SEMANTIC_ASSURANCE_CAMPAIGNS = [
  { id: "wave5/genui-semantic", owner: "@liteship/genui", packageDir: "packages/genui", scope: "public-runtime-closure", required: ["mutation", "mcdc"], class: "semantic-l4", entrypoints: ["packages/genui/src/index.ts"] },
  { id: "wave5/assets-semantic", owner: "@liteship/assets", packageDir: "packages/assets", scope: "public-runtime-closure", required: ["mutation", "mcdc"], class: "semantic-l4", entrypoints: ["packages/assets/src/index.ts"] },
] as const;
