/** Generated spine provenance projection. Do not edit by hand. @module */
import type { SpineTypeAdmission } from '@liteship/audit';

export type SpineProtocolDeclaration =
  | {
      readonly classification: 'spine-protocol';
      readonly symbol: string;
      readonly leaf: string;
      readonly owner: '@liteship/_spine';
      readonly provenance: 'declaration-leaf';
    }
  | {
      readonly classification: 'protocol-projection';
      readonly symbol: string;
      readonly leaf: string;
      readonly owner: '@liteship/_spine';
      readonly provenance: 'generated-owner-catalog';
      readonly generator: string;
      readonly ownerCatalogs: readonly string[];
    };

// prettier-ignore
export const GENERATED_LITESHIP_SPINE_ADMISSIONS: readonly SpineTypeAdmission[] = [
  {
    typeName: 'AIAction',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'AIAction',
    runtimeModule: 'packages/compiler/src/ai-manifest.ts',
    runtimeExpr: 'AIAction',
  },
  {
    typeName: 'AIConstraint',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'AIConstraint',
    runtimeModule: 'packages/compiler/src/ai-manifest.ts',
    runtimeExpr: 'AIConstraint',
  },
  {
    typeName: 'AIDimension',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'AIDimension',
    runtimeModule: 'packages/compiler/src/ai-manifest.ts',
    runtimeExpr: 'AIDimension',
  },
  {
    typeName: 'AIManifest',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'AIManifest',
    runtimeModule: 'packages/compiler/src/ai-manifest.ts',
    runtimeExpr: 'AIManifest',
  },
  {
    typeName: 'AIManifestCompileResult',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'AIManifestCompileResult',
    runtimeModule: 'packages/compiler/src/ai-manifest.ts',
    runtimeExpr: 'AIManifestCompileResult',
  },
  {
    typeName: 'AIManifestInput',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'AIManifestInput',
    runtimeModule: 'packages/compiler/src/ai-manifest.ts',
    runtimeExpr: 'AIManifestInput',
  },
  {
    typeName: 'AIParamSchema',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'AIParamSchema',
    runtimeModule: 'packages/compiler/src/ai-manifest.ts',
    runtimeExpr: 'AIParamSchema',
  },
  {
    typeName: 'AISlot',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'AISlot',
    runtimeModule: 'packages/compiler/src/ai-manifest.ts',
    runtimeExpr: 'AISlot',
  },
  {
    typeName: 'AIToolDefinition',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'AIToolDefinition',
    runtimeModule: 'packages/compiler/src/ai-manifest.ts',
    runtimeExpr: 'AIToolDefinition',
  },
  {
    typeName: 'AIValidationIssue',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'AIValidationIssue',
    runtimeModule: 'packages/compiler/src/ai-manifest.ts',
    runtimeExpr: 'AIValidationIssue',
  },
  {
    typeName: 'ARIACompileResult',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'ARIACompileResult',
    runtimeModule: 'packages/compiler/src/aria.ts',
    runtimeExpr: 'ARIACompileResult',
  },
  {
    typeName: 'ARIAStates',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'ARIAStates',
    runtimeModule: 'packages/compiler/src/dispatch.ts',
    runtimeExpr: 'ARIAStates',
  },
  {
    typeName: 'AdmittedPartValue',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'AdmittedPartValue',
    runtimeModule: 'packages/core/src/ecs/part.ts',
    runtimeExpr: 'AdmittedPartValue',
  },
  {
    typeName: 'Animation',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'typeof Animation',
    runtimeModule: 'packages/core/src/motion/animation.ts',
    runtimeExpr: 'typeof Animation',
  },
  {
    typeName: 'AstroLoggerLike',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'AstroLoggerLike',
    runtimeModule: 'packages/astro/src/diagnostics-bridge.ts',
    runtimeExpr: 'AstroLoggerLike',
  },
  {
    typeName: 'AsyncOwnedResource',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'AsyncOwnedResource',
    runtimeModule: 'packages/core/src/reactive/lifetime.ts',
    runtimeExpr: 'AsyncOwnedResource',
  },
  {
    typeName: 'BackpressureHint',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'BackpressureHint',
    runtimeModule: 'packages/web/src/types.ts',
    runtimeExpr: 'BackpressureHint',
  },
  {
    typeName: 'BeatComponent',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'BeatComponent',
    runtimeModule: 'packages/scene/src/beat-binding-capsule.ts',
    runtimeExpr: 'BeatComponent',
  },
  {
    typeName: 'BeatHandle',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'BeatHandle',
    runtimeModule: 'packages/scene/src/sugar/beat.ts',
    runtimeExpr: 'BeatHandle',
  },
  {
    typeName: 'BeatMarkerSet',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'BeatMarkerSet',
    runtimeModule: 'packages/assets/src/analysis/beat-markers.ts',
    runtimeExpr: 'BeatMarkerSet',
  },
  {
    typeName: 'BeatSpawn',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'BeatSpawn',
    runtimeModule: 'packages/scene/src/beat-binding-capsule.ts',
    runtimeExpr: 'BeatSpawn',
  },
  {
    typeName: 'BlendTree',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'BlendTree<any>',
    runtimeModule: 'packages/core/src/motion/blend.ts',
    runtimeExpr: 'BlendTree<any>',
  },
  {
    typeName: 'Boundary',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'Boundary',
    runtimeModule: 'packages/core/src/authoring/boundary.ts',
    runtimeExpr: 'Boundary',
  },
  {
    typeName: 'BoundaryCrossing',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'BoundaryCrossing',
    runtimeModule: 'packages/core/src/reactive/types.ts',
    runtimeExpr: 'BoundaryCrossing',
  },
  {
    typeName: 'BoundarySpec',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'BoundarySpec',
    runtimeModule: 'packages/core/src/authoring/boundary.ts',
    runtimeExpr: 'BoundarySpec',
  },
  {
    typeName: 'BytesCtor',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'BytesCtor',
    runtimeModule: 'packages/core/src/schema/ast.ts',
    runtimeExpr: 'BytesCtor',
  },
  {
    typeName: 'CSSCompileResult',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'CSSCompileResult',
    runtimeModule: 'packages/compiler/src/css.ts',
    runtimeExpr: 'CSSCompileResult',
  },
  {
    typeName: 'CSSContainerRule',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'CSSContainerRule',
    runtimeModule: 'packages/compiler/src/css.ts',
    runtimeExpr: 'CSSContainerRule',
  },
  {
    typeName: 'CSSRule',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'CSSRule',
    runtimeModule: 'packages/compiler/src/css.ts',
    runtimeExpr: 'CSSRule',
  },
  {
    typeName: 'CSSStateBody',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'CSSStateBody',
    runtimeModule: 'packages/compiler/src/css.ts',
    runtimeExpr: 'CSSStateBody',
  },
  {
    typeName: 'CSSStateInput',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'CSSStateInput',
    runtimeModule: 'packages/compiler/src/css.ts',
    runtimeExpr: 'CSSStateInput',
  },
  {
    typeName: 'CSSStates',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'CSSStates',
    runtimeModule: 'packages/compiler/src/dispatch.ts',
    runtimeExpr: 'CSSStates',
  },
  {
    typeName: 'CapAxis',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'CapAxis',
    runtimeModule: 'packages/detect/src/cap-axes.ts',
    runtimeExpr: 'CapAxis',
  },
  {
    typeName: 'CapabilityAxisEvidence',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'CapabilityAxisEvidence',
    runtimeModule: 'packages/detect/src/cap-axes.ts',
    runtimeExpr: 'CapabilityAxisEvidence',
  },
  {
    typeName: 'CapabilityAxisValues',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'CapabilityAxisValues',
    runtimeModule: 'packages/detect/src/cap-axes.ts',
    runtimeExpr: 'CapabilityAxisValues',
  },
  {
    typeName: 'CapabilityEvidenceInput',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'CapabilityEvidenceInput',
    runtimeModule: 'packages/detect/src/cap-axes.ts',
    runtimeExpr: 'CapabilityEvidenceInput',
  },
  {
    typeName: 'CapabilityEvidenceInputs',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'CapabilityEvidenceInputs',
    runtimeModule: 'packages/detect/src/cap-axes.ts',
    runtimeExpr: 'CapabilityEvidenceInputs',
  },
  {
    typeName: 'CapabilityInputEvidence',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'CapabilityInputEvidence',
    runtimeModule: 'packages/detect/src/cap-axes.ts',
    runtimeExpr: 'CapabilityInputEvidence',
  },
  {
    typeName: 'CapabilityTierEvidence',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'CapabilityTierEvidence',
    runtimeModule: 'packages/detect/src/cap-axes.ts',
    runtimeExpr: 'CapabilityTierEvidence',
  },
  {
    typeName: 'CapabilityTierProjection',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'CapabilityTierProjection',
    runtimeModule: 'packages/detect/src/cap-axes.ts',
    runtimeExpr: 'CapabilityTierProjection',
  },
  {
    typeName: 'CapsuleResultMetaKey',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'CapsuleResultMetaKey',
    runtimeModule: 'packages/core/src/authoring/command.ts',
    runtimeExpr: 'CapsuleResultMetaKey',
  },
  {
    typeName: 'CapsuleResultReceipt',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'CapsuleResultReceipt',
    runtimeModule: 'packages/core/src/authoring/command.ts',
    runtimeExpr: 'CapsuleResultReceipt',
  },
  {
    typeName: 'CaptureConfig',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'CaptureConfig',
    runtimeModule: 'packages/core/src/evidence/capture.ts',
    runtimeExpr: 'CaptureConfig',
  },
  {
    typeName: 'CaptureFrame',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'CaptureFrame',
    runtimeModule: 'packages/core/src/evidence/capture.ts',
    runtimeExpr: 'CaptureFrame',
  },
  {
    typeName: 'Cell',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'Cell<any>',
    runtimeModule: 'packages/core/src/reactive/cell.ts',
    runtimeExpr: 'Cell<any>',
  },
  {
    typeName: 'CellEnvelope',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'CellEnvelope',
    runtimeModule: 'packages/core/src/schema/protocol.ts',
    runtimeExpr: 'CellEnvelope',
  },
  {
    typeName: 'CellKernel',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'typeof CellKernel',
    runtimeModule: 'packages/core/src/reactive/cell-kernel.ts',
    runtimeExpr: 'typeof CellKernel',
  },
  {
    typeName: 'CellKind',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'CellKind',
    runtimeModule: 'packages/core/src/schema/protocol.ts',
    runtimeExpr: 'CellKind',
  },
  {
    typeName: 'CellMeta',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'CellMeta',
    runtimeModule: 'packages/core/src/schema/protocol.ts',
    runtimeExpr: 'CellMeta',
  },
  {
    typeName: 'ChainValidationError',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'ChainValidationError',
    runtimeModule: 'packages/core/src/evidence/receipt.ts',
    runtimeExpr: 'ChainValidationError',
  },
  {
    typeName: 'ChainValidationOptions',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'ChainValidationOptions',
    runtimeModule: 'packages/core/src/evidence/receipt.ts',
    runtimeExpr: 'ChainValidationOptions',
  },
  {
    typeName: 'CheckpointResult',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'CheckpointResult',
    runtimeModule: 'packages/core/src/graph/dag.ts',
    runtimeExpr: 'CheckpointResult',
  },
  {
    typeName: 'ClientHints',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'typeof ClientHints',
    runtimeModule: 'packages/edge/src/client-hints.ts',
    runtimeExpr: 'typeof ClientHints',
  },
  {
    typeName: 'ClientHintsEvidence',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'ClientHintsEvidence',
    runtimeModule: 'packages/edge/src/client-hints.ts',
    runtimeExpr: 'ClientHintsEvidence',
  },
  {
    typeName: 'Clock',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'Clock',
    runtimeModule: 'packages/core/src/clock/clock.ts',
    runtimeExpr: 'Clock',
  },
  {
    typeName: 'CompileResult',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'CompileResult',
    runtimeModule: 'packages/compiler/src/dispatch.ts',
    runtimeExpr: 'CompileResult',
  },
  {
    typeName: 'CompilerDef',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'CompilerDef',
    runtimeModule: 'packages/compiler/src/dispatch.ts',
    runtimeExpr: 'CompilerDef',
  },
  {
    typeName: 'Component',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'Component',
    runtimeModule: 'packages/core/src/authoring/component.ts',
    runtimeExpr: 'Component',
  },
  {
    typeName: 'ComponentCatalog',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'ComponentCatalog',
    runtimeModule: 'packages/genui/src/types.ts',
    runtimeExpr: 'ComponentCatalog',
  },
  {
    typeName: 'ComponentDef',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'ComponentDef',
    runtimeModule: 'packages/genui/src/types.ts',
    runtimeExpr: 'ComponentDef',
  },
  {
    typeName: 'ComponentPropDef',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'ComponentPropDef',
    runtimeModule: 'packages/genui/src/types.ts',
    runtimeExpr: 'ComponentPropDef',
  },
  {
    typeName: 'Compositor',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'Compositor',
    runtimeModule: 'packages/core/src/media/compositor.ts',
    runtimeExpr: 'Compositor',
  },
  {
    typeName: 'CompositorQuantizer',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'CompositorQuantizer',
    runtimeModule: 'packages/core/src/schema/quantizer-types.ts',
    runtimeExpr: 'CompositorQuantizer',
  },
  {
    typeName: 'ConfigInput',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'ConfigInput',
    runtimeModule: 'packages/core/src/authoring/config.ts',
    runtimeExpr: 'ConfigInput',
  },
  {
    typeName: 'ConfigTemplateResult',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'ConfigTemplateResult',
    runtimeModule: 'packages/compiler/src/dispatch.ts',
    runtimeExpr: 'ConfigTemplateResult',
  },
  {
    typeName: 'CrossOriginEmbedderPolicy',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'CrossOriginEmbedderPolicy',
    runtimeModule: 'packages/edge/src/cross-origin.ts',
    runtimeExpr: 'CrossOriginEmbedderPolicy',
  },
  {
    typeName: 'CssKeyframeStep',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'CssKeyframeStep',
    runtimeModule: 'packages/core/src/motion/interpret-transition.ts',
    runtimeExpr: 'CssKeyframeStep',
  },
  {
    typeName: 'CssMotionPlan',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'CssMotionPlan',
    runtimeModule: 'packages/core/src/motion/interpret-transition.ts',
    runtimeExpr: 'CssMotionPlan',
  },
  {
    typeName: 'DAGNode',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'DAGNode',
    runtimeModule: 'packages/core/src/graph/dag.ts',
    runtimeExpr: 'DAGNode',
  },
  {
    typeName: 'DenseStore',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'DenseStore',
    runtimeModule: 'packages/core/src/ecs/dense.ts',
    runtimeExpr: 'DenseStore',
  },
  {
    typeName: 'DenseStoreWriter',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'DenseStoreWriter',
    runtimeModule: 'packages/core/src/ecs/dense.ts',
    runtimeExpr: 'DenseStoreWriter',
  },
  {
    typeName: 'DenseSystem',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'DenseSystem',
    runtimeModule: 'packages/core/src/ecs/dense.ts',
    runtimeExpr: 'DenseSystem',
  },
  {
    typeName: 'DenseSystemContext',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'DenseSystemContext<any, any>',
    runtimeModule: 'packages/core/src/ecs/dense.ts',
    runtimeExpr: 'DenseSystemContext<any, any>',
  },
  {
    typeName: 'Derived',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'Derived<any>',
    runtimeModule: 'packages/core/src/reactive/derived.ts',
    runtimeExpr: 'Derived<any>',
  },
  {
    typeName: 'DesignTier',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'DesignTier',
    runtimeModule: 'packages/detect/src/tiers.ts',
    runtimeExpr: 'DesignTier',
  },
  {
    typeName: 'DetectionResult',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'DetectionResult',
    runtimeModule: 'packages/detect/src/detect.ts',
    runtimeExpr: 'DetectionResult',
  },
  {
    typeName: 'DeviceCapabilities',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'DeviceCapabilities',
    runtimeModule: 'packages/detect/src/detect.ts',
    runtimeExpr: 'DeviceCapabilities',
  },
  {
    typeName: 'DirtyFlags',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'DirtyFlags',
    runtimeModule: 'packages/core/src/reactive/dirty.ts',
    runtimeExpr: 'DirtyFlags',
  },
  {
    typeName: 'Disposer',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'Disposer',
    runtimeModule: 'packages/detect/src/detect-ready.ts',
    runtimeExpr: 'Disposer',
  },
  {
    typeName: 'EaseName',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'EaseName',
    runtimeModule: 'packages/scene/src/sugar/ease.ts',
    runtimeExpr: 'EaseName',
  },
  {
    typeName: 'EaseTag',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'EaseTag',
    runtimeModule: 'packages/scene/src/sugar/ease.ts',
    runtimeExpr: 'EaseTag',
  },
  {
    typeName: 'Easing',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'typeof Easing',
    runtimeModule: 'packages/core/src/motion/easing.ts',
    runtimeExpr: 'typeof Easing',
  },
  {
    typeName: 'EdgeHostBackground',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'EdgeHostBackground',
    runtimeModule: 'packages/edge/src/host-adapter.ts',
    runtimeExpr: 'EdgeHostBackground',
  },
  {
    typeName: 'EdgeTier',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'typeof EdgeTier',
    runtimeModule: 'packages/edge/src/edge-tier.ts',
    runtimeExpr: 'typeof EdgeTier',
  },
  {
    typeName: 'EdgeType',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'EdgeType',
    runtimeModule: 'packages/core/src/authoring/plan.ts',
    runtimeExpr: 'EdgeType',
  },
  {
    typeName: 'Entity',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'Entity',
    runtimeModule: 'packages/core/src/ecs/world.ts',
    runtimeExpr: 'Entity',
  },
  {
    typeName: 'EntityId',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'EntityId',
    runtimeModule: 'packages/core/src/ecs/part.ts',
    runtimeExpr: 'EntityId',
  },
  {
    typeName: 'ExtendedDetectionResult',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'ExtendedDetectionResult',
    runtimeModule: 'packages/detect/src/detect.ts',
    runtimeExpr: 'ExtendedDetectionResult',
  },
  {
    typeName: 'ExtendedDeviceCapabilities',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'ExtendedDeviceCapabilities',
    runtimeModule: 'packages/detect/src/detect.ts',
    runtimeExpr: 'ExtendedDeviceCapabilities',
  },
  {
    typeName: 'FadeEnvelope',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'FadeEnvelope',
    runtimeModule: 'packages/scene/src/sugar/envelope.ts',
    runtimeExpr: 'FadeEnvelope',
  },
  {
    typeName: 'FetchLayerNext',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'FetchLayerNext',
    runtimeModule: 'packages/astro/src/fetch-layer.ts',
    runtimeExpr: 'FetchLayerNext',
  },
  {
    typeName: 'FocusState',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'FocusState',
    runtimeModule: 'packages/web/src/types.ts',
    runtimeExpr: 'FocusState',
  },
  {
    typeName: 'ForkViolation',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'ForkViolation',
    runtimeModule: 'packages/core/src/graph/dag.ts',
    runtimeExpr: 'ForkViolation',
  },
  {
    typeName: 'FrameBudget',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'FrameBudget',
    runtimeModule: 'packages/core/src/media/frame-budget.ts',
    runtimeExpr: 'FrameBudget',
  },
  {
    typeName: 'FrameCapture',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'FrameCapture',
    runtimeModule: 'packages/core/src/evidence/capture.ts',
    runtimeExpr: 'FrameCapture',
  },
  {
    typeName: 'FrameMark',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'FrameMark',
    runtimeModule: 'packages/scene/src/contract.ts',
    runtimeExpr: 'FrameMark',
  },
  {
    typeName: 'FrameMarkSum',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'FrameMarkSum',
    runtimeModule: 'packages/scene/src/sugar/beat.ts',
    runtimeExpr: 'FrameMarkSum',
  },
  {
    typeName: 'FrameSchedule',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'FrameSchedule',
    runtimeModule: 'packages/core/src/media/video.ts',
    runtimeExpr: 'FrameSchedule',
  },
  {
    typeName: 'GLSLCompileResult',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'GLSLCompileResult',
    runtimeModule: 'packages/compiler/src/glsl.ts',
    runtimeExpr: 'GLSLCompileResult',
  },
  {
    typeName: 'GLSLDefine',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'GLSLDefine',
    runtimeModule: 'packages/compiler/src/glsl.ts',
    runtimeExpr: 'GLSLDefine',
  },
  {
    typeName: 'GLSLStates',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'GLSLStates',
    runtimeModule: 'packages/compiler/src/dispatch.ts',
    runtimeExpr: 'GLSLStates',
  },
  {
    typeName: 'GLSLType',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'GLSLType',
    runtimeModule: 'packages/compiler/src/glsl.ts',
    runtimeExpr: 'GLSLType',
  },
  {
    typeName: 'GLSLUniform',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'GLSLUniform',
    runtimeModule: 'packages/compiler/src/glsl.ts',
    runtimeExpr: 'GLSLUniform',
  },
  {
    typeName: 'GPUTier',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'GPUTier',
    runtimeModule: 'packages/detect/src/detect.ts',
    runtimeExpr: 'GPUTier',
  },
  {
    typeName: 'GeneratedUINode',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'GeneratedUINode',
    runtimeModule: 'packages/genui/src/types.ts',
    runtimeExpr: 'GeneratedUINode',
  },
  {
    typeName: 'GeneratedUIValidationError',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'GeneratedUIValidationError',
    runtimeModule: 'packages/genui/src/types.ts',
    runtimeExpr: 'GeneratedUIValidationError',
  },
  {
    typeName: 'HLC',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'HLC',
    runtimeModule: 'packages/core/src/clock/hlc.ts',
    runtimeExpr: 'HLC',
  },
  {
    typeName: 'HMRBoundaryIdentity',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'HMRBoundaryIdentity',
    runtimeModule: 'packages/vite/src/hmr.ts',
    runtimeExpr: 'HMRBoundaryIdentity',
  },
  {
    typeName: 'HtmlPolicy',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'HtmlPolicy',
    runtimeModule: 'packages/web/src/types.ts',
    runtimeExpr: 'HtmlPolicy',
  },
  {
    typeName: 'IMEState',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'IMEState',
    runtimeModule: 'packages/web/src/types.ts',
    runtimeExpr: 'IMEState',
  },
  {
    typeName: 'IntegrationConfig',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'IntegrationConfig',
    runtimeModule: 'packages/astro/src/integration.ts',
    runtimeExpr: 'IntegrationConfig',
  },
  {
    typeName: 'IslandMode',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'IslandMode',
    runtimeModule: 'packages/web/src/types.ts',
    runtimeExpr: 'IslandMode',
  },
  {
    typeName: 'Lifetime',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'Lifetime',
    runtimeModule: 'packages/core/src/reactive/lifetime.ts',
    runtimeExpr: 'Lifetime',
  },
  {
    typeName: 'LiteralValue',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'LiteralValue',
    runtimeModule: 'packages/core/src/schema/ast.ts',
    runtimeExpr: 'LiteralValue',
  },
  {
    typeName: 'LiteshipFetchLayer',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'LiteshipFetchLayer',
    runtimeModule: 'packages/astro/src/fetch-layer.ts',
    runtimeExpr: 'LiteshipFetchLayer',
  },
  {
    typeName: 'LiteshipFetchLayerConfig',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'LiteshipFetchLayerConfig',
    runtimeModule: 'packages/astro/src/fetch-layer.ts',
    runtimeExpr: 'LiteshipFetchLayerConfig',
  },
  {
    typeName: 'LiteshipLocals',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'LiteshipLocals',
    runtimeModule: 'packages/astro/src/middleware.ts',
    runtimeExpr: 'LiteshipLocals',
  },
  {
    typeName: 'LiteshipMiddlewareConfig',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'LiteshipMiddlewareConfig',
    runtimeModule: 'packages/astro/src/middleware.ts',
    runtimeExpr: 'LiteshipMiddlewareConfig',
  },
  {
    typeName: 'LiveCell',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'LiveCell<any, any>',
    runtimeModule: 'packages/core/src/reactive/live-cell.ts',
    runtimeExpr: 'LiveCell<any, any>',
  },
  {
    typeName: 'MatchPriority',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'MatchPriority',
    runtimeModule: 'packages/web/src/types.ts',
    runtimeExpr: 'MatchPriority',
  },
  {
    typeName: 'MatchResult',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'MatchResult',
    runtimeModule: 'packages/web/src/types.ts',
    runtimeExpr: 'MatchResult',
  },
  {
    typeName: 'MergeResult',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'MergeResult',
    runtimeModule: 'packages/core/src/graph/dag.ts',
    runtimeExpr: 'MergeResult',
  },
  {
    typeName: 'Messages',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'typeof Messages',
    runtimeModule: 'packages/worker/src/messages.ts',
    runtimeExpr: 'typeof Messages',
  },
  {
    typeName: 'MorphCallbacks',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'MorphCallbacks',
    runtimeModule: 'packages/web/src/types.ts',
    runtimeExpr: 'MorphCallbacks',
  },
  {
    typeName: 'MorphConfig',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'MorphConfig',
    runtimeModule: 'packages/web/src/types.ts',
    runtimeExpr: 'MorphConfig',
  },
  {
    typeName: 'MorphHints',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'MorphHints',
    runtimeModule: 'packages/web/src/types.ts',
    runtimeExpr: 'MorphHints',
  },
  {
    typeName: 'MorphRejection',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'MorphRejection',
    runtimeModule: 'packages/web/src/types.ts',
    runtimeExpr: 'MorphRejection',
  },
  {
    typeName: 'MorphResult',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'MorphResult',
    runtimeModule: 'packages/web/src/types.ts',
    runtimeExpr: 'MorphResult',
  },
  {
    typeName: 'MotionCompileInput',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'MotionCompileInput',
    runtimeModule: 'packages/compiler/src/motion.ts',
    runtimeExpr: 'MotionCompileInput',
  },
  {
    typeName: 'MotionCompileResult',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'MotionCompileResult',
    runtimeModule: 'packages/compiler/src/motion.ts',
    runtimeExpr: 'MotionCompileResult',
  },
  {
    typeName: 'MotionEasing',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'MotionEasing',
    runtimeModule: 'packages/compiler/src/motion.ts',
    runtimeExpr: 'MotionEasing',
  },
  {
    typeName: 'MotionPropertyTween',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'MotionPropertyTween',
    runtimeModule: 'packages/core/src/motion/interpret-transition.ts',
    runtimeExpr: 'MotionPropertyTween',
  },
  {
    typeName: 'MotionScrollTimeline',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'MotionScrollTimeline',
    runtimeModule: 'packages/compiler/src/motion.ts',
    runtimeExpr: 'MotionScrollTimeline',
  },
  {
    typeName: 'MotionSpringConfig',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'MotionSpringConfig',
    runtimeModule: 'packages/compiler/src/motion.ts',
    runtimeExpr: 'MotionSpringConfig',
  },
  {
    typeName: 'MotionViewTimeline',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'MotionViewTimeline',
    runtimeModule: 'packages/compiler/src/motion.ts',
    runtimeExpr: 'MotionViewTimeline',
  },
  {
    typeName: 'NativeTimelineEligibility',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'NativeTimelineEligibility',
    runtimeModule: 'packages/core/src/motion/interpret-transition.ts',
    runtimeExpr: 'NativeTimelineEligibility',
  },
  {
    typeName: 'OpType',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'OpType',
    runtimeModule: 'packages/core/src/authoring/plan.ts',
    runtimeExpr: 'OpType',
  },
  {
    typeName: 'OutputsFor',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'OutputsFor<any, any>',
    runtimeModule: 'packages/core/src/authoring/types.ts',
    runtimeExpr: 'OutputsFor<any, any>',
  },
  {
    typeName: 'OverflowPolicy',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'OverflowPolicy',
    runtimeModule: 'packages/web/src/types.ts',
    runtimeExpr: 'OverflowPolicy',
  },
  {
    typeName: 'OwnedDenseStore',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'OwnedDenseStore',
    runtimeModule: 'packages/core/src/ecs/dense.ts',
    runtimeExpr: 'OwnedDenseStore',
  },
  {
    typeName: 'Part',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'Part',
    runtimeModule: 'packages/core/src/ecs/part.ts',
    runtimeExpr: 'Part',
  },
  {
    typeName: 'PartRetentionPolicy',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'PartRetentionPolicy',
    runtimeModule: 'packages/core/src/ecs/part.ts',
    runtimeExpr: 'PartRetentionPolicy',
  },
  {
    typeName: 'PartValue',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'PartValue<any>',
    runtimeModule: 'packages/core/src/ecs/part.ts',
    runtimeExpr: 'PartValue<any>',
  },
  {
    typeName: 'PhysicalState',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'PhysicalState',
    runtimeModule: 'packages/web/src/types.ts',
    runtimeExpr: 'PhysicalState',
  },
  {
    typeName: 'PhysicalStateTracker',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'PhysicalStateTracker',
    runtimeModule: 'packages/web/src/physical/capture.ts',
    runtimeExpr: 'PhysicalStateTracker',
  },
  {
    typeName: 'Prettify',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'Prettify<any>',
    runtimeModule: 'packages/core/src/schema/types.ts',
    runtimeExpr: 'Prettify<any>',
  },
  {
    typeName: 'Primitive',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'Primitive<any>',
    runtimeModule: 'packages/core/src/reactive/primitive.ts',
    runtimeExpr: 'Primitive<any>',
  },
  {
    typeName: 'Priority',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'Priority',
    runtimeModule: 'packages/core/src/media/frame-budget.ts',
    runtimeExpr: 'Priority',
  },
  {
    typeName: 'PulseEnvelope',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'PulseEnvelope',
    runtimeModule: 'packages/scene/src/sugar/envelope.ts',
    runtimeExpr: 'PulseEnvelope',
  },
  {
    typeName: 'QuantizeProps',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'QuantizeProps',
    runtimeModule: 'packages/astro/src/quantize.ts',
    runtimeExpr: 'QuantizeProps',
  },
  {
    typeName: 'Quantizer',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'Quantizer',
    runtimeModule: 'packages/core/src/schema/quantizer-types.ts',
    runtimeExpr: 'Quantizer',
  },
  {
    typeName: 'QuantizerCrossings',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'QuantizerCrossings',
    runtimeModule: 'packages/core/src/schema/quantizer-types.ts',
    runtimeExpr: 'QuantizerCrossings',
  },
  {
    typeName: 'QuantizerState',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'QuantizerState',
    runtimeModule: 'packages/core/src/schema/quantizer-types.ts',
    runtimeExpr: 'QuantizerState',
  },
  {
    typeName: 'ReactiveQuantizer',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'ReactiveQuantizer',
    runtimeModule: 'packages/core/src/schema/quantizer-types.ts',
    runtimeExpr: 'ReactiveQuantizer',
  },
  {
    typeName: 'ReadonlyDenseValues',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'ReadonlyDenseValues',
    runtimeModule: 'packages/core/src/ecs/dense.ts',
    runtimeExpr: 'ReadonlyDenseValues',
  },
  {
    typeName: 'ReceiptDAG',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'ReceiptDAG',
    runtimeModule: 'packages/core/src/graph/dag.ts',
    runtimeExpr: 'ReceiptDAG',
  },
  {
    typeName: 'ReceiptEnvelope',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'ReceiptEnvelope',
    runtimeModule: 'packages/core/src/evidence/receipt.ts',
    runtimeExpr: 'ReceiptEnvelope',
  },
  {
    typeName: 'ReceiptSubject',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'ReceiptSubject',
    runtimeModule: 'packages/core/src/evidence/receipt.ts',
    runtimeExpr: 'ReceiptSubject',
  },
  {
    typeName: 'ReconnectConfig',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'ReconnectConfig',
    runtimeModule: 'packages/web/src/types.ts',
    runtimeExpr: 'ReconnectConfig',
  },
  {
    typeName: 'RenderFn',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'RenderFn',
    runtimeModule: 'packages/web/src/capture/render.ts',
    runtimeExpr: 'RenderFn',
  },
  {
    typeName: 'ResolvedEnvelope',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'ResolvedEnvelope',
    runtimeModule: 'packages/scene/src/sugar/envelope.ts',
    runtimeExpr: 'ResolvedEnvelope',
  },
  {
    typeName: 'ResponsiveMediaCapabilities',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'ResponsiveMediaCapabilities',
    runtimeModule: 'packages/core/src/media/responsive-media.ts',
    runtimeExpr: 'ResponsiveMediaCapabilities',
  },
  {
    typeName: 'ResponsiveMediaIntent',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'ResponsiveMediaIntent',
    runtimeModule: 'packages/core/src/media/responsive-media.ts',
    runtimeExpr: 'ResponsiveMediaIntent',
  },
  {
    typeName: 'ResponsiveMediaPictureProjection',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'ResponsiveMediaPictureProjection',
    runtimeModule: 'packages/core/src/media/responsive-media.ts',
    runtimeExpr: 'ResponsiveMediaPictureProjection',
  },
  {
    typeName: 'ResponsiveMediaResolutionReason',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'ResponsiveMediaResolutionReason',
    runtimeModule: 'packages/core/src/media/responsive-media.ts',
    runtimeExpr: 'ResponsiveMediaResolutionReason',
  },
  {
    typeName: 'ResponsiveMediaVariant',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'ResponsiveMediaVariant',
    runtimeModule: 'packages/core/src/media/responsive-media.ts',
    runtimeExpr: 'ResponsiveMediaVariant',
  },
  {
    typeName: 'ResumeResponse',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'ResumeResponse',
    runtimeModule: 'packages/web/src/types.ts',
    runtimeExpr: 'ResumeResponse',
  },
  {
    typeName: 'ResumptionConfig',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'ResumptionConfig',
    runtimeModule: 'packages/web/src/types.ts',
    runtimeExpr: 'ResumptionConfig',
  },
  {
    typeName: 'ResumptionState',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'ResumptionState',
    runtimeModule: 'packages/web/src/types.ts',
    runtimeExpr: 'ResumptionState',
  },
  {
    typeName: 'ResumptionStateInput',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'ResumptionStateInput',
    runtimeModule: 'packages/web/src/types.ts',
    runtimeExpr: 'ResumptionStateInput',
  },
  {
    typeName: 'RuntimeEndpointKind',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'RuntimeEndpointKind',
    runtimeModule: 'packages/web/src/types.ts',
    runtimeExpr: 'RuntimeEndpointKind',
  },
  {
    typeName: 'RuntimeEndpointPolicy',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'RuntimeEndpointPolicy',
    runtimeModule: 'packages/web/src/types.ts',
    runtimeExpr: 'RuntimeEndpointPolicy',
  },
  {
    typeName: 'RuntimeHtmlPolicy',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'RuntimeHtmlPolicy',
    runtimeModule: 'packages/astro/src/runtime/policy.ts',
    runtimeExpr: 'RuntimeHtmlPolicy',
  },
  {
    typeName: 'SSEClient',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'SSEClient',
    runtimeModule: 'packages/web/src/stream/sse.ts',
    runtimeExpr: 'SSEClient',
  },
  {
    typeName: 'SSEConfig',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'SSEConfig',
    runtimeModule: 'packages/web/src/types.ts',
    runtimeExpr: 'SSEConfig',
  },
  {
    typeName: 'SSEMessage',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'SSEMessage',
    runtimeModule: 'packages/web/src/types.ts',
    runtimeExpr: 'SSEMessage',
  },
  {
    typeName: 'SSEState',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'SSEState',
    runtimeModule: 'packages/web/src/types.ts',
    runtimeExpr: 'SSEState',
  },
  {
    typeName: 'ScheduledFrame',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'ScheduledFrame',
    runtimeModule: 'packages/core/src/media/video.ts',
    runtimeExpr: 'ScheduledFrame',
  },
  {
    typeName: 'Scheduler',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'Scheduler',
    runtimeModule: 'packages/core/src/reactive/scheduler.ts',
    runtimeExpr: 'Scheduler',
  },
  {
    typeName: 'SchemaAnnotations',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'SchemaAnnotations',
    runtimeModule: 'packages/core/src/schema/ast.ts',
    runtimeExpr: 'SchemaAnnotations',
  },
  {
    typeName: 'SchemaNode',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'SchemaNode',
    runtimeModule: 'packages/core/src/schema/ast.ts',
    runtimeExpr: 'SchemaNode',
  },
  {
    typeName: 'SchemaPort',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'SchemaPort<any>',
    runtimeModule: 'packages/core/src/schema/schema-port.ts',
    runtimeExpr: 'SchemaPort<any>',
  },
  {
    typeName: 'ScrollPosition',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'ScrollPosition',
    runtimeModule: 'packages/web/src/types.ts',
    runtimeExpr: 'ScrollPosition',
  },
  {
    typeName: 'SelectionState',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'SelectionState',
    runtimeModule: 'packages/web/src/types.ts',
    runtimeExpr: 'SelectionState',
  },
  {
    typeName: 'ServerIslandContext',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'ServerIslandContext',
    runtimeModule: 'packages/astro/src/quantize.ts',
    runtimeExpr: 'ServerIslandContext',
  },
  {
    typeName: 'ShadowLayer',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'ShadowLayer',
    runtimeModule: 'packages/core/src/authoring/style.ts',
    runtimeExpr: 'ShadowLayer',
  },
  {
    typeName: 'SlotConfig',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'SlotConfig',
    runtimeModule: 'packages/core/src/authoring/component.ts',
    runtimeExpr: 'SlotConfig',
  },
  {
    typeName: 'SlotEntry',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'SlotEntry',
    runtimeModule: 'packages/web/src/types.ts',
    runtimeExpr: 'SlotEntry',
  },
  {
    typeName: 'SlotEntryInput',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'SlotEntryInput',
    runtimeModule: 'packages/web/src/types.ts',
    runtimeExpr: 'SlotEntryInput',
  },
  {
    typeName: 'SlotPath',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'SlotPath',
    runtimeModule: 'packages/web/src/types.ts',
    runtimeExpr: 'SlotPath',
  },
  {
    typeName: 'SlotRegistry',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'SlotRegistry',
    runtimeModule: 'packages/web/src/slot/registry.ts',
    runtimeExpr: 'SlotRegistry',
  },
  {
    typeName: 'Store',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'Store<any, any>',
    runtimeModule: 'packages/core/src/reactive/store.ts',
    runtimeExpr: 'Store<any, any>',
  },
  {
    typeName: 'StyleCSSResult',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'StyleCSSResult',
    runtimeModule: 'packages/compiler/src/style-css.ts',
    runtimeExpr: 'StyleCSSResult',
  },
  {
    typeName: 'StyleLayer',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'StyleLayer',
    runtimeModule: 'packages/core/src/authoring/style.ts',
    runtimeExpr: 'StyleLayer',
  },
  {
    typeName: 'System',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'System',
    runtimeModule: 'packages/core/src/ecs/world.ts',
    runtimeExpr: 'System',
  },
  {
    typeName: 'SystemContext',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'SystemContext',
    runtimeModule: 'packages/core/src/ecs/world.ts',
    runtimeExpr: 'SystemContext',
  },
  {
    typeName: 'SystemEntity',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'SystemEntity',
    runtimeModule: 'packages/core/src/ecs/world.ts',
    runtimeExpr: 'SystemEntity',
  },
  {
    typeName: 'ThemeCSSResult',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'ThemeCSSResult',
    runtimeModule: 'packages/compiler/src/theme-css.ts',
    runtimeExpr: 'ThemeCSSResult',
  },
  {
    typeName: 'ThemeDeclaration',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'ThemeDeclaration',
    runtimeModule: 'packages/edge/src/theme-compiler.ts',
    runtimeExpr: 'ThemeDeclaration',
  },
  {
    typeName: 'Timeline',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'Timeline',
    runtimeModule: 'packages/core/src/motion/timeline.ts',
    runtimeExpr: 'Timeline',
  },
  {
    typeName: 'TokenCSSResult',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'TokenCSSResult',
    runtimeModule: 'packages/compiler/src/token-css.ts',
    runtimeExpr: 'TokenCSSResult',
  },
  {
    typeName: 'TokenJSResult',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'TokenJSResult',
    runtimeModule: 'packages/compiler/src/token-js.ts',
    runtimeExpr: 'TokenJSResult',
  },
  {
    typeName: 'TokenTailwindResult',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'TokenTailwindResult',
    runtimeModule: 'packages/compiler/src/token-tailwind.ts',
    runtimeExpr: 'TokenTailwindResult',
  },
  {
    typeName: 'TrackEnvelope',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'TrackEnvelope',
    runtimeModule: 'packages/scene/src/sugar/envelope.ts',
    runtimeExpr: 'TrackEnvelope',
  },
  {
    typeName: 'TrackId',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'TrackId<any>',
    runtimeModule: 'packages/scene/src/contract.ts',
    runtimeExpr: 'TrackId<any>',
  },
  {
    typeName: 'TrackKind',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'TrackKind',
    runtimeModule: 'packages/scene/src/contract.ts',
    runtimeExpr: 'TrackKind',
  },
  {
    typeName: 'TypedRef',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'TypedRef',
    runtimeModule: 'packages/core/src/evidence/typed-ref.ts',
    runtimeExpr: 'TypedRef',
  },
  {
    typeName: 'VectorClock',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'VectorClock',
    runtimeModule: 'packages/core/src/clock/vector-clock.ts',
    runtimeExpr: 'VectorClock',
  },
  {
    typeName: 'VideoFrameOutput',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'VideoFrameOutput',
    runtimeModule: 'packages/core/src/media/video.ts',
    runtimeExpr: 'VideoFrameOutput',
  },
  {
    typeName: 'VideoRenderer',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'VideoRenderer',
    runtimeModule: 'packages/core/src/media/video.ts',
    runtimeExpr: 'VideoRenderer',
  },
  {
    typeName: 'ViewTransitionCompileInput',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'ViewTransitionCompileInput',
    runtimeModule: 'packages/compiler/src/view-transition-compile.ts',
    runtimeExpr: 'ViewTransitionCompileInput',
  },
  {
    typeName: 'ViewTransitionCompileResult',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'ViewTransitionCompileResult',
    runtimeModule: 'packages/compiler/src/view-transition-compile.ts',
    runtimeExpr: 'ViewTransitionCompileResult',
  },
  {
    typeName: 'WGSLBinding',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'WGSLBinding',
    runtimeModule: 'packages/compiler/src/wgsl.ts',
    runtimeExpr: 'WGSLBinding',
  },
  {
    typeName: 'WGSLBindingType',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'WGSLBindingType',
    runtimeModule: 'packages/compiler/src/wgsl.ts',
    runtimeExpr: 'WGSLBindingType',
  },
  {
    typeName: 'WGSLCompileResult',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'WGSLCompileResult',
    runtimeModule: 'packages/compiler/src/wgsl.ts',
    runtimeExpr: 'WGSLCompileResult',
  },
  {
    typeName: 'WGSLStates',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'WGSLStates',
    runtimeModule: 'packages/compiler/src/dispatch.ts',
    runtimeExpr: 'WGSLStates',
  },
  {
    typeName: 'WGSLStruct',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'WGSLStruct',
    runtimeModule: 'packages/compiler/src/wgsl.ts',
    runtimeExpr: 'WGSLStruct',
  },
  {
    typeName: 'WGSLType',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'WGSLType',
    runtimeModule: 'packages/compiler/src/wgsl.ts',
    runtimeExpr: 'WGSLType',
  },
  {
    typeName: 'WGSLUniformValue',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'WGSLUniformValue',
    runtimeModule: 'packages/compiler/src/wgsl.ts',
    runtimeExpr: 'WGSLUniformValue',
  },
  {
    typeName: 'WGSLUniformVector',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'WGSLUniformVector',
    runtimeModule: 'packages/compiler/src/wgsl.ts',
    runtimeExpr: 'WGSLUniformVector',
  },
  {
    typeName: 'WallClockTimestamp',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'WallClockTimestamp',
    runtimeModule: 'packages/core/src/authoring/command.ts',
    runtimeExpr: 'WallClockTimestamp',
  },
  {
    typeName: 'WebCodecsCaptureOptions',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'WebCodecsCaptureOptions',
    runtimeModule: 'packages/web/src/capture/webcodecs.ts',
    runtimeExpr: 'WebCodecsCaptureOptions',
  },
  {
    typeName: 'World',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'World',
    runtimeModule: 'packages/core/src/ecs/world.ts',
    runtimeExpr: 'World',
  },
  {
    typeName: 'Zap',
    authority: 'runtime',
    admittedRelation: 'exact',
    spineExpr: 'Zap<any>',
    runtimeModule: 'packages/core/src/reactive/zap.ts',
    runtimeExpr: 'Zap<any>',
  },
] as const;

// prettier-ignore
export const LITESHIP_SPINE_PROTOCOL_DECLARATIONS: readonly SpineProtocolDeclaration[] = [
  { classification: 'spine-protocol', symbol: 'AddQuantizerMessage', leaf: 'worker.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  { classification: 'spine-protocol', symbol: 'AnyPart', leaf: 'core.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  { classification: 'spine-protocol', symbol: 'AnySchemaNode', leaf: 'core.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  { classification: 'spine-protocol', symbol: 'ApplyResolvedStateMessage', leaf: 'worker.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  { classification: 'spine-protocol', symbol: 'ApplyUpdatesMessage', leaf: 'worker.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  { classification: 'spine-protocol', symbol: 'ArraySchemaNode', leaf: 'core.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  { classification: 'spine-protocol', symbol: 'BeatProjectionResolutionInput', leaf: 'beats.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  { classification: 'spine-protocol', symbol: 'BlendNode', leaf: 'core.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  { classification: 'spine-protocol', symbol: 'BooleanSchemaNode', leaf: 'core.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  { classification: 'spine-protocol', symbol: 'BootstrapQuantizerRegistration', leaf: 'worker.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  { classification: 'spine-protocol', symbol: 'BootstrapQuantizersMessage', leaf: 'worker.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  { classification: 'spine-protocol', symbol: 'BootstrapResolvedStateMessage', leaf: 'worker.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  { classification: 'spine-protocol', symbol: 'BoundaryAssetUrlMap', leaf: 'vite.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  { classification: 'spine-protocol', symbol: 'BrandSchemaNode', leaf: 'core.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  { classification: 'spine-protocol', symbol: 'BytesSchemaNode', leaf: 'core.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  { classification: 'spine-protocol', symbol: 'CSSCustomProp', leaf: 'design.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  { classification: 'spine-protocol', symbol: 'CSSLength', leaf: 'design.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  { classification: 'spine-protocol', symbol: 'CSSProp', leaf: 'design.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  { classification: 'spine-protocol', symbol: 'CSSTime', leaf: 'design.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  { classification: 'spine-protocol', symbol: 'Canvas2DTarget', leaf: 'web.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  { classification: 'spine-protocol', symbol: 'CompositorWorkerStartupStage', leaf: 'worker.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  { classification: 'spine-protocol', symbol: 'CompositorWorkerStartupTelemetry', leaf: 'worker.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  { classification: 'spine-protocol', symbol: 'ComputeMessage', leaf: 'worker.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  { classification: 'spine-protocol', symbol: 'ControllableSignal', leaf: 'core.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  { classification: 'spine-protocol', symbol: 'DefKind', leaf: 'compiler.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  { classification: 'spine-protocol', symbol: 'DisposeMessage', leaf: 'worker.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  { classification: 'spine-protocol', symbol: 'EdgeWGSLUniformValue', leaf: 'edge.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  { classification: 'spine-protocol', symbol: 'EdgeWGSLUniformVector', leaf: 'edge.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  { classification: 'spine-protocol', symbol: 'ErrorMessage', leaf: 'worker.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  { classification: 'spine-protocol', symbol: 'EvaluateMessage', leaf: 'worker.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  { classification: 'spine-protocol', symbol: 'EvaluateUpdate', leaf: 'worker.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  {
    classification: 'protocol-projection',
    symbol: 'EventDetail',
    leaf: 'events.generated.d.ts',
    owner: '@liteship/_spine',
    provenance: 'generated-owner-catalog',
    generator: 'scripts/lib/event-protocol-contract.ts',
    ownerCatalogs: ['packages/astro/src/runtime/event-protocol.ts', 'packages/detect/src/event-protocol.ts', 'packages/scene/src/dev/event-protocol.ts', 'packages/vite/src/event-protocol.ts', 'packages/web/src/wire/event-protocol.ts'],
  },
  {
    classification: 'protocol-projection',
    symbol: 'EventsInChannel',
    leaf: 'events.generated.d.ts',
    owner: '@liteship/_spine',
    provenance: 'generated-owner-catalog',
    generator: 'scripts/lib/event-protocol-contract.ts',
    ownerCatalogs: ['packages/astro/src/runtime/event-protocol.ts', 'packages/detect/src/event-protocol.ts', 'packages/scene/src/dev/event-protocol.ts', 'packages/vite/src/event-protocol.ts', 'packages/web/src/wire/event-protocol.ts'],
  },
  {
    classification: 'protocol-projection',
    symbol: 'EventsOwnedBy',
    leaf: 'events.generated.d.ts',
    owner: '@liteship/_spine',
    provenance: 'generated-owner-catalog',
    generator: 'scripts/lib/event-protocol-contract.ts',
    ownerCatalogs: ['packages/astro/src/runtime/event-protocol.ts', 'packages/detect/src/event-protocol.ts', 'packages/scene/src/dev/event-protocol.ts', 'packages/vite/src/event-protocol.ts', 'packages/web/src/wire/event-protocol.ts'],
  },
  { classification: 'spine-protocol', symbol: 'FrameMessage', leaf: 'worker.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  { classification: 'spine-protocol', symbol: 'HLCClock', leaf: 'core.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  { classification: 'spine-protocol', symbol: 'HoleSchemaNode', leaf: 'core.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  { classification: 'spine-protocol', symbol: 'InitMessage', leaf: 'worker.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  { classification: 'spine-protocol', symbol: 'KernelSchema', leaf: 'core.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  {
    classification: 'protocol-projection',
    symbol: 'LiteShipEventChannel',
    leaf: 'events.generated.d.ts',
    owner: '@liteship/_spine',
    provenance: 'generated-owner-catalog',
    generator: 'scripts/lib/event-protocol-contract.ts',
    ownerCatalogs: ['packages/astro/src/runtime/event-protocol.ts', 'packages/detect/src/event-protocol.ts', 'packages/scene/src/dev/event-protocol.ts', 'packages/vite/src/event-protocol.ts', 'packages/web/src/wire/event-protocol.ts'],
  },
  {
    classification: 'protocol-projection',
    symbol: 'LiteShipEventMap',
    leaf: 'events.generated.d.ts',
    owner: '@liteship/_spine',
    provenance: 'generated-owner-catalog',
    generator: 'scripts/lib/event-protocol-contract.ts',
    ownerCatalogs: ['packages/astro/src/runtime/event-protocol.ts', 'packages/detect/src/event-protocol.ts', 'packages/scene/src/dev/event-protocol.ts', 'packages/vite/src/event-protocol.ts', 'packages/web/src/wire/event-protocol.ts'],
  },
  {
    classification: 'protocol-projection',
    symbol: 'LiteShipEventName',
    leaf: 'events.generated.d.ts',
    owner: '@liteship/_spine',
    provenance: 'generated-owner-catalog',
    generator: 'scripts/lib/event-protocol-contract.ts',
    ownerCatalogs: ['packages/astro/src/runtime/event-protocol.ts', 'packages/detect/src/event-protocol.ts', 'packages/scene/src/dev/event-protocol.ts', 'packages/vite/src/event-protocol.ts', 'packages/web/src/wire/event-protocol.ts'],
  },
  {
    classification: 'protocol-projection',
    symbol: 'LiteShipEventOwner',
    leaf: 'events.generated.d.ts',
    owner: '@liteship/_spine',
    provenance: 'generated-owner-catalog',
    generator: 'scripts/lib/event-protocol-contract.ts',
    ownerCatalogs: ['packages/astro/src/runtime/event-protocol.ts', 'packages/detect/src/event-protocol.ts', 'packages/scene/src/dev/event-protocol.ts', 'packages/vite/src/event-protocol.ts', 'packages/web/src/wire/event-protocol.ts'],
  },
  { classification: 'spine-protocol', symbol: 'LiteralSchemaNode', leaf: 'core.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  { classification: 'spine-protocol', symbol: 'MetricsMessage', leaf: 'worker.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  { classification: 'spine-protocol', symbol: 'NumberSchemaNode', leaf: 'core.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  { classification: 'spine-protocol', symbol: 'OutputRecord', leaf: 'quantizer.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  { classification: 'spine-protocol', symbol: 'PartTuple', leaf: 'core.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  { classification: 'spine-protocol', symbol: 'PlanBuilder', leaf: 'core.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  { classification: 'spine-protocol', symbol: 'PlanEdge', leaf: 'core.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  { classification: 'spine-protocol', symbol: 'PlanIR', leaf: 'core.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  { classification: 'spine-protocol', symbol: 'PlanStep', leaf: 'core.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  { classification: 'spine-protocol', symbol: 'PlanValidationError', leaf: 'core.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  { classification: 'spine-protocol', symbol: 'PlanValidationResult', leaf: 'core.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  {
    classification: 'protocol-projection',
    symbol: 'ProtocolEvent',
    leaf: 'events.generated.d.ts',
    owner: '@liteship/_spine',
    provenance: 'generated-owner-catalog',
    generator: 'scripts/lib/event-protocol-contract.ts',
    ownerCatalogs: ['packages/astro/src/runtime/event-protocol.ts', 'packages/detect/src/event-protocol.ts', 'packages/scene/src/dev/event-protocol.ts', 'packages/vite/src/event-protocol.ts', 'packages/web/src/wire/event-protocol.ts'],
  },
  { classification: 'spine-protocol', symbol: 'ReadablePart', leaf: 'core.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  { classification: 'spine-protocol', symbol: 'ReadonlyConfigValue', leaf: 'config.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  { classification: 'spine-protocol', symbol: 'ReadonlyQuantizerValue', leaf: 'quantizer.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  { classification: 'spine-protocol', symbol: 'ReadyMessage', leaf: 'worker.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  { classification: 'spine-protocol', symbol: 'RecordSchemaNode', leaf: 'core.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  { classification: 'spine-protocol', symbol: 'RemoveQuantizerMessage', leaf: 'worker.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  { classification: 'spine-protocol', symbol: 'RemoveQuantizerUpdate', leaf: 'worker.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  { classification: 'spine-protocol', symbol: 'RenderCompleteMessage', leaf: 'worker.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  { classification: 'spine-protocol', symbol: 'RenderContext2D', leaf: 'web.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  { classification: 'spine-protocol', symbol: 'ResolvedStateAckMessage', leaf: 'worker.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  { classification: 'spine-protocol', symbol: 'ResolvedStateEntry', leaf: 'worker.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  { classification: 'spine-protocol', symbol: 'RuntimeCoordinatorDenseStore', leaf: 'core.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  { classification: 'spine-protocol', symbol: 'SchemaNodeMeta', leaf: 'core.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  { classification: 'spine-protocol', symbol: 'SetBlendMessage', leaf: 'worker.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  { classification: 'spine-protocol', symbol: 'SetBlendUpdate', leaf: 'worker.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  { classification: 'spine-protocol', symbol: 'SlotsOf', leaf: 'design.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  { classification: 'spine-protocol', symbol: 'StartRenderMessage', leaf: 'worker.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  { classification: 'spine-protocol', symbol: 'StartupComputeMessage', leaf: 'worker.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  { classification: 'spine-protocol', symbol: 'StartupComputePacket', leaf: 'worker.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  { classification: 'spine-protocol', symbol: 'StateMessage', leaf: 'worker.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  { classification: 'spine-protocol', symbol: 'StopRenderMessage', leaf: 'worker.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  { classification: 'spine-protocol', symbol: 'StringSchemaNode', leaf: 'core.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  { classification: 'spine-protocol', symbol: 'StructSchemaField', leaf: 'core.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  { classification: 'spine-protocol', symbol: 'StructSchemaNode', leaf: 'core.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  { classification: 'spine-protocol', symbol: 'StyleTransitionConfig', leaf: 'design.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  { classification: 'spine-protocol', symbol: 'TokensOf', leaf: 'design.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  { classification: 'spine-protocol', symbol: 'TransferCanvasMessage', leaf: 'worker.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  { classification: 'spine-protocol', symbol: 'TuplePart', leaf: 'core.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  { classification: 'spine-protocol', symbol: 'TupleSchemaNode', leaf: 'core.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  { classification: 'spine-protocol', symbol: 'UnionSchemaNode', leaf: 'core.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  { classification: 'spine-protocol', symbol: 'UnknownSchemaNode', leaf: 'core.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  { classification: 'spine-protocol', symbol: 'VariantsOf', leaf: 'design.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  { classification: 'spine-protocol', symbol: 'WarmResetMessage', leaf: 'worker.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  { classification: 'spine-protocol', symbol: 'WorkerErrorCode', leaf: 'worker.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
  { classification: 'spine-protocol', symbol: 'WorkerUpdate', leaf: 'worker.d.ts', owner: '@liteship/_spine', provenance: 'declaration-leaf' },
] as const;
