/** @generated by scripts/gen-roster.ts from packages/create-liteship/src/template-renames.ts; do not hand-edit. */
// prettier-ignore
export const GENERATED_TEMPLATE_RENAMES: Readonly<Record<string, string>> = Object.freeze({
  "gitignore": ".gitignore"
});
