/**
 * add — a minimal-real scaffold-fragment copier.
 *
 * `liteship add` (no args) lists the fragments available to copy; `liteship add
 * <kind> <name>` copies one into the working directory. Two fragment kinds are
 * shipped: `example` (generated byte-for-byte from the runnable/dogfood apps
 * under `examples/`) and `template` (generated byte-for-byte from the
 * `create-liteship` starter templates). A fragment is copied verbatim into
 * `./<name>`; the command refuses to overwrite an existing path.
 *
 * This is deliberately the SUBSET, not the full generator surface. Rich
 * generators (whole-project + per-component scaffolding with token substitution)
 * are tracked as OBL-FEATURE-ADD and are out of scope here; every response says
 * so via {@link RICHER_GENERATORS_NOTE}.
 *
 * @module
 */

import { cpSync, existsSync, readdirSync, statSync } from 'node:fs';
import { relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { wallClock } from '@liteship/core';
import { emit, emitError } from '../receipts.js';

/** The scaffold-fragment kinds this minimal copier understands. */
export type FragmentKind = 'example' | 'template';

/** Package-relative generated projection that holds each kind's fragments. */
const FRAGMENT_ROOTS: Record<FragmentKind, string> = {
  example: 'example',
  template: 'template',
};

/**
 * Published fragment root, resolved from this module rather than the caller's
 * cwd. The same `../../fragments` relation holds for source (`src/commands`) and
 * built (`dist/commands`) modules, so repository and installed execution drive
 * the exact same bytes.
 */
const PACKAGED_FRAGMENT_ROOT = fileURLToPath(new URL('../../fragments/', import.meta.url));

/** The forthcoming-richer-generators pointer carried on every `add` response. */
// OBLIGATION: OBL-FEATURE-ADD
export const RICHER_GENERATORS_NOTE =
  'This is the minimal fragment copier; richer scaffold generators (whole-project + per-component) are forthcoming (OBL-FEATURE-ADD).';

/** Narrow a raw kind token to the closed {@link FragmentKind} set. */
function isFragmentKind(value: string): value is FragmentKind {
  return value === 'example' || value === 'template';
}

/** List the fragment directory names available for each kind (empty when a root is absent). */
function listFragments(root: string): Record<FragmentKind, readonly string[]> {
  const forKind = (kind: FragmentKind): readonly string[] => {
    const dir = resolve(root, FRAGMENT_ROOTS[kind]);
    if (!existsSync(dir)) return [];
    return readdirSync(dir)
      .filter((name) => statSync(resolve(dir, name)).isDirectory())
      .sort();
  };
  return { example: forKind('example'), template: forKind('template') };
}

/** Count the files (not directories) copied under `dir`, recursively. */
function countFiles(dir: string): number {
  let total = 0;
  for (const name of readdirSync(dir)) {
    const abs = resolve(dir, name);
    if (statSync(abs).isDirectory()) total += countFiles(abs);
    else total += 1;
  }
  return total;
}

/**
 * Execute `liteship add [<kind> <name>]`. With no `kind`, lists the available
 * fragments (exit 0). With `kind`+`name`, copies the packaged projection into
 * `./<name>` and reports the copied file count. Exit 1 on an unknown kind/name
 * or an already-existing destination.
 */
export async function add(opts: { kind?: string; name?: string; cwd?: string } = {}): Promise<number> {
  const cwd = opts.cwd ?? process.cwd();
  const available = listFragments(PACKAGED_FRAGMENT_ROOT);
  const timestamp = new Date(wallClock.now()).toISOString();

  // List mode: no kind given.
  if (opts.kind === undefined) {
    emit({
      status: 'ok',
      command: 'add',
      timestamp,
      fragments: available,
      note: RICHER_GENERATORS_NOTE,
    });
    process.stderr.write(
      `liteship add <kind> <name> — copy a scaffold fragment.\n` +
        `  example:  ${available.example.join(', ') || '(none)'}\n` +
        `  template: ${available.template.join(', ') || '(none)'}\n` +
        `  ${RICHER_GENERATORS_NOTE}\n`,
    );
    return 0;
  }

  if (!isFragmentKind(opts.kind)) {
    emitError(
      'add',
      `unknown fragment kind: ${opts.kind}`,
      `Available kinds: ${Object.keys(FRAGMENT_ROOTS).join(', ')}`,
    );
    return 1;
  }

  const names = available[opts.kind];
  const availableHint = `Available ${opts.kind}s: ${names.join(', ') || '(none)'}`;
  if (opts.name === undefined) {
    emitError('add', `usage: liteship add ${opts.kind} <name>`, availableHint);
    return 1;
  }
  if (!names.includes(opts.name)) {
    emitError('add', `no ${opts.kind} fragment named "${opts.name}"`, availableHint);
    return 1;
  }

  const source = resolve(PACKAGED_FRAGMENT_ROOT, FRAGMENT_ROOTS[opts.kind], opts.name);
  const destination = resolve(cwd, opts.name);
  if (existsSync(destination)) {
    emitError('add', `destination already exists: ${destination}`, 'Choose an empty target path or remove it first');
    return 1;
  }

  cpSync(source, destination, { recursive: true });
  const fileCount = countFiles(destination);

  emit({
    status: 'ok',
    command: 'add',
    timestamp,
    kind: opts.kind,
    name: opts.name,
    dest: relative(cwd, destination) || opts.name,
    fileCount,
    note: RICHER_GENERATORS_NOTE,
  });
  process.stderr.write(
    `Copied ${opts.kind} '${opts.name}' → ${relative(cwd, destination) || opts.name} (${fileCount} file${fileCount === 1 ? '' : 's'}).\n` +
      `  ${RICHER_GENERATORS_NOTE}\n`,
  );
  return 0;
}
