/**
 * `liteship` — the curated facade for the LiteShip stack.
 *
 * Installing `liteship` still brings every publishable `@liteship/*` package into
 * your node_modules in one dependency (the umbrella role is unchanged). What is new
 * is the CURATED FACADE: this root `.` entry exposes a small, budgeted authoring
 * surface — the verbs (`defineConfig` / `defineBoundary` / `defineQuantizer` /
 * `defineToken` / `defineTheme` / `defineStyle` / `schema` / `createCell` /
 * `computed` / `createStore` / `createTimeline` / `chooseTier`) plus the domain
 * nouns as TYPES — and the deeper domain surfaces ride explicit SUBPATHS
 * (`liteship/schema`, `liteship/reactive`, `liteship/motion`, `liteship/graph`,
 * `liteship/media`, `liteship/evidence`, `liteship/compiler`, `liteship/runtime`,
 * `liteship/astro`, `liteship/vite`, `liteship/testing`).
 *
 * The root is DELIBERATELY minimal and host-free: importing `.` evaluates NOTHING
 * from the host integrations (`@liteship/astro`, `@liteship/vite`) — those carry
 * host-specific (optional) peer expectations and live behind their own subpaths,
 * whose module graphs are independent of this one. The permitted root surface is
 * pinned as DATA in `export-budget.ts` and enforced by the
 * `gauntlet/facade-export-budget` gate. You can still import from the individual
 * scopes (`@liteship/core`, `@liteship/quantizer`, …) exactly as the docs show.
 *
 * @module
 */

// ── Curated root VALUES — the authoring verbs (P6/P7 + verb-grammar-sweep-2) ──
// The `define*` declaration constructors + `schema`, the reactive `create*` /
// `computed` builders, the `chooseTier` / `tierTargets` escalation readers, and
// the `inspectReceipt` debug facade, re-anchored from `@liteship/core`; the
// quantizer verbs from `@liteship/quantizer`.
export {
  defineConfig,
  defineBoundary,
  defineToken,
  defineTheme,
  defineStyle,
  defineAdaptive,
  schema,
  createCell,
  computed,
  createStore,
  createSignal,
  createTimeline,
  createLifetime,
  chooseTier,
  tierTargets,
  inspectReceipt,
} from '@liteship/core';
export { defineQuantizer, createQuantizer } from '@liteship/quantizer';
// The diagnostic explainer — the one reader that turns any emitted LiteShip
// diagnostic code into its title/explanation/remediation.
export { explainDiagnostic } from '@liteship/error';

// ── Curated root TYPES — the domain nouns as types (no value namespace on root) ─
// Each is re-exported TYPE-ONLY: the root hands you the SHAPE to annotate against,
// while the value namespace-objects (`Boundary`, `Token`, …) stay on their domain
// subpaths. `Config`/`Boundary`/`Token`/`Theme`/`Style`/`Lifetime` are value+type
// pairs in core; `export type` narrows the root re-export to the type meaning.
export type {
  Boundary,
  Quantizer,
  Token,
  Theme,
  Style,
  Adaptive,
  Config,
  Cell,
  Store,
  Timeline,
  Lifetime,
  TierChoice,
  CapTier,
} from '@liteship/core';
export type { Finding } from '@liteship/gauntlet';
export type { DiagnosticCode } from '@liteship/error';

/**
 * Every `@liteship/*` package this umbrella installs, in dependency order.
 * Consumed by audit/doctor/release tooling that needs the canonical fleet
 * list; app authors never need to import it for layers 1–3.
 *
 * Membership, dependency order, and package metadata are authored once in
 * `scripts/package-catalog.ts`. `scripts/gen-roster.ts` materializes this
 * tarball-safe const because a published package cannot import a repository
 * script. Audit, package-smoke, release, documentation, and this const are
 * sibling generated projections; package manifests remain the independent
 * physical packaging oracle.
 */
/* BEGIN gen-roster: LITESHIP_PACKAGES — generated by scripts/gen-roster.ts (renderLiteshipPackages); do not hand-edit inside these markers. */
// prettier-ignore
export const LITESHIP_PACKAGES = [
  "@liteship/_spine",
  "@liteship/error",
  "@liteship/canonical",
  "@liteship/core",
  "@liteship/genui",
  "@liteship/quantizer",
  "@liteship/compiler",
  "@liteship/web",
  "@liteship/detect",
  "@liteship/edge",
  "@liteship/vite",
  "@liteship/worker",
  "@liteship/remotion",
  "@liteship/scene",
  "@liteship/astro",
  "@liteship/cloudflare",
  "@liteship/stage",
  "@liteship/assets",
  "@liteship/gauntlet",
  "@liteship/audit",
  "@liteship/command",
  "@liteship/cli",
  "@liteship/mcp-server",
] as const;
/* END gen-roster: LITESHIP_PACKAGES */

/** Union of the package names installed by `liteship`. */
export type LiteshipPackageName = (typeof LITESHIP_PACKAGES)[number];
