/**
 * `liteship` — the umbrella package for the LiteShip stack.
 *
 * Installing `liteship` brings every publishable `@liteship/*` package into
 * your node_modules in one dependency; you still import from the
 * individual scopes (`@liteship/core`, `@liteship/quantizer`, `@liteship/astro`, …)
 * exactly as the docs show. This module deliberately re-exports NOTHING:
 * the host integrations (`@liteship/astro`, `@liteship/vite`, `@liteship/cloudflare`)
 * carry host-specific peer expectations, and a barrel that imported them
 * would force every consumer to satisfy all of them at once. Pick your
 * entry points; this package just makes sure they're installed.
 *
 * @module
 */

/**
 * Every `@liteship/*` package this umbrella installs, in dependency order.
 * Consumed by audit/doctor/release tooling that needs the canonical fleet
 * list; app authors never need to import it for layers 1–3.
 *
 * This is the tarball-shipped mirror of the canonical `@liteship/*` fleet roster
 * owned by `scripts/gen-roster.ts` (`CANONICAL_ROSTER`). The const stays local
 * because `liteship` ships in the published tarball and cannot import a
 * dev-only script; the `BEGIN/END gen-roster` block below is regenerated by
 * `pnpm tsx scripts/gen-roster.ts` (its `renderLiteshipPackages()` output) and
 * the `liteship-packages-roster` drift-guard byte-compares it against that
 * generator, so the two can never silently diverge.
 *
 * The single fleet-roster OWNER these names re-anchor to is `@liteship/audit`'s
 * `LITESHIP_PACKAGE_ROSTER` (the scoped `@liteship/*` fleet). This copy stays local by the
 * SAME shipping constraint — `liteship` ships in the tarball and cannot import the
 * devops-layer `@liteship/audit` — and its parity with that anchor is held by the
 * `liteship-packages-roster` drift-guard, not a shared import.
 */
/* BEGIN gen-roster: LITESHIP_PACKAGES — generated by scripts/gen-roster.ts (renderLiteshipPackages); do not hand-edit inside these markers. */
export const LITESHIP_PACKAGES = [
  '@liteship/_spine',
  '@liteship/error',
  '@liteship/canonical',
  '@liteship/core',
  '@liteship/genui',
  '@liteship/quantizer',
  '@liteship/compiler',
  '@liteship/web',
  '@liteship/detect',
  '@liteship/edge',
  '@liteship/vite',
  '@liteship/worker',
  '@liteship/remotion',
  '@liteship/scene',
  '@liteship/astro',
  '@liteship/cloudflare',
  '@liteship/stage',
  '@liteship/assets',
  '@liteship/gauntlet',
  '@liteship/audit',
  '@liteship/command',
  '@liteship/cli',
  '@liteship/mcp-server',
] as const;
/* END gen-roster: LITESHIP_PACKAGES */

/** Union of the package names installed by `liteship`. */
export type LiteshipPackageName = (typeof LITESHIP_PACKAGES)[number];
