/** @generated by scripts/gen-roster.ts from scripts/package-catalog.ts; do not hand-edit. */
// prettier-ignore
export const GENERATED_PACKAGE_METADATA = {
  "@liteship/_spine": {
    description: "Install-only TypeScript declaration spine for LiteShip: the shared type anchor that `@liteship/core` and `@liteship/scene` reference from their published `.d.ts` — there is nothing to import at runtime.",
    keywords: ["liteship", "typescript", "types", "declarations"],
  },
  "@liteship/error": {
    description: "The one error algebra for LiteShip: build tagged error values that work as thrown Errors and as errors-as-values (a Result err-arm), and compose your own variants on top with zero dependencies.",
    keywords: ["liteship", "error-handling", "tagged-union", "typescript"],
  },
  "@liteship/canonical": {
    description: "The content-addressing kernel for LiteShip: canonical CBOR encoding and stable digests so the same definition always hashes to the same address.",
    keywords: ["liteship", "content-addressing", "cbor", "hashing", "typescript"],
  },
  "@liteship/core": {
    description: "The heart of LiteShip: define UI boundaries, tokens, themes, and signals once as a content-addressed graph, then drive the engine that keeps every rendered output in sync.",
    keywords: ["liteship", "adaptive-rendering", "constraint-based", "ui-framework", "typescript"],
  },
  "@liteship/genui": {
    description: "Render AI-generated UI safely in LiteShip: validate a model's proposed component tree against a host-owned catalog and draw only trusted, whitelisted components.",
    keywords: ["liteship", "generative-ui", "ai-safety", "component-catalog", "typescript"],
  },
  "@liteship/quantizer": {
    description: "Turn continuous signals into a few named UI states for LiteShip: evaluate boundaries, animate the transitions between states, and gate motion by device tier.",
    keywords: ["liteship", "adaptive-rendering", "state-machine", "boundary", "typescript"],
  },
  "@liteship/compiler": {
    description: "Compile one LiteShip boundary definition into many outputs at once — CSS, GLSL, WGSL, ARIA, AI descriptions, and Tailwind — so every target stays in sync.",
    keywords: ["liteship", "css", "shaders", "aria", "compiler", "typescript"],
  },
  "@liteship/web": {
    description: "The browser runtime for LiteShip: apply CSS, streamed HTML, worker output, and LLM chunks to a live DOM with focus- and scroll-preserving morphing.",
    keywords: ["liteship", "dom", "browser-runtime", "streaming", "typescript"],
  },
  "@liteship/detect": {
    description: "Detect device capabilities for LiteShip: probe GPU tier, CPU, memory, motion preference, and network, then map them to the tiers that select which UI state renders.",
    keywords: ["liteship", "device-detection", "capability-probe", "gpu-tier", "typescript"],
  },
  "@liteship/edge": {
    description: "Choose the right UI state at the CDN edge for LiteShip: read Client Hints into a device tier, serve a content-addressed boundary cache, and compile the theme for first paint.",
    keywords: ["liteship", "edge", "cdn", "client-hints", "typescript"],
  },
  "@liteship/vite": {
    description: "The Vite plugin for LiteShip: compile `@token`, `@theme`, `@style`, and `@quantize` blocks into native CSS and hot-reload boundary definitions as you edit.",
    keywords: ["liteship", "vite-plugin", "css", "hmr", "typescript"],
  },
  "@liteship/worker": {
    description: "Move LiteShip's heavy work off the main thread: compositor and render workers plus a lock-free ring buffer that stream state and frames without janking the UI.",
    keywords: ["liteship", "web-worker", "off-main-thread", "offscreen-canvas", "typescript"],
  },
  "@liteship/remotion": {
    description: "Use LiteShip inside Remotion: React hooks and composition helpers that drive video frames and shader surfaces from the same boundary state used everywhere else.",
    keywords: ["liteship", "remotion", "video", "react", "typescript"],
  },
  "@liteship/scene": {
    description: "Author video timelines for LiteShip: a typed scene and track model built on the entity-component substrate in `@liteship/core`.",
    keywords: ["liteship", "scene", "timeline", "video", "typescript"],
  },
  "@liteship/astro": {
    description: "The Astro integration for LiteShip: render adaptive UI as islands with the `client:adaptive` directive and resolve device tiers on the server for first paint.",
    keywords: ["liteship", "astro", "integration", "islands", "typescript"],
  },
  "@liteship/cloudflare": {
    description: "Run LiteShip on Cloudflare Workers: a site adapter with a KV-backed edge cache and the Astro middleware glue that caches boundaries at the edge.",
    keywords: ["liteship", "cloudflare", "workers", "edge", "typescript"],
  },
  "@liteship/stage": {
    description: "Export one LiteShip document graph to many carriers: prove a single source renders to both a static Astro page and a video, joined under one receipt.",
    keywords: ["liteship", "dual-export", "video", "static-site", "typescript"],
  },
  "@liteship/assets": {
    description: "Manage media assets for LiteShip: declare audio, video, and image assets and read cached analysis such as waveforms, beat markers, and onsets.",
    keywords: ["liteship", "assets", "audio", "waveform", "typescript"],
  },
  "@liteship/gauntlet": {
    description: "The rigor engine behind LiteShip's release gates: define quality gates that report findings and earn blocking power only by proving themselves against their own fixtures.",
    keywords: ["liteship", "quality-gate", "fitness-function", "static-analysis", "typescript"],
  },
  "@liteship/audit": {
    description: "Audit a LiteShip project's structure, integrity, and public surface: a downstream-installable engine that builds a model of the repository and runs configurable checks over it.",
    keywords: ["liteship", "audit", "static-analysis", "code-quality", "typescript"],
  },
  "@liteship/command": {
    description: "The shared command registry behind LiteShip's tooling: one source of command definitions that both the `liteship` CLI and the MCP server project from.",
    keywords: ["liteship", "cli", "mcp", "command-registry", "typescript"],
  },
  "@liteship/cli": {
    description: "The programmatic command dispatcher and terminal implementation behind the facade-owned `liteship` executable: JSON-in, JSON-out verbs with a human-friendly terminal mode.",
    keywords: ["liteship", "cli", "command-line", "json", "typescript"],
  },
  "@liteship/mcp-server": {
    description: "The Model Context Protocol server for LiteShip: exposes the `liteship` commands and capsule catalog as MCP tools that AI assistants can call.",
    keywords: ["liteship", "mcp", "model-context-protocol", "ai-tooling", "typescript"],
  },
  "create-liteship": {
    description: "Scaffold a new LiteShip project: run `npm create liteship` to get a minimal Astro app wired to the framework in one step.",
    keywords: ["create-liteship", "liteship", "scaffold", "astro", "typescript"],
  },
  "liteship": {
    description: "The curated public facade and executable owner for LiteShip: one dependency, one command, and one import path over the whole `@liteship/*` adaptive rendering stack.",
    keywords: ["liteship", "adaptive-rendering", "framework", "meta-package", "typescript"],
  },
} as const;
