// Worker, edge and server children, including the H1-H3 provider paths.
//
// Mutations carried verbatim from the ratified verification kit; only the
// plumbing changed. Each entry rewrites one exact span of the live tree and
// must die on a named law. An entry whose anchor text is absent reports
// MISSING and fails the bank -- a bank that has drifted off the source must
// never be mistaken for a bank that passed.

import { runBank } from '../harness.mjs';

const TD = 'types.d.ts';
const WK = (h) => `01_hosts/worker/${h}/types.ts`;
const ED = (h) => `01_hosts/edge/${h}/types.ts`;
const SV = (h) => `01_hosts/server/${h}/types.ts`;
const WKU = '01_hosts/worker/types.ts';
const EDU = '01_hosts/edge/types.ts';
const SVU = '01_hosts/server/types.ts';
const HU = '01_hosts/types.ts';
const OP = '00_core/07_operation/types.ts';

const M = [
  // --- worker ---
  ['W-IDENT: the envelope grounding borrows the realm-scope identity', WK('00_bootstrap'),
    "  readonly id: GroundingId<'liteship.worker.grounding.bootstrap-envelope'>;",
    "  readonly id: GroundingId<'liteship.worker.grounding.realm-scope'>;"],
  ['W-IDENT: the queue offer borrows the messaging identity', WK('05_queue'),
    "  readonly id: RealizationOfferId<'liteship.worker.offer.queue-authority'>;",
    "  readonly id: RealizationOfferId<'liteship.worker.offer.messaging-authority'>;"],
  ['W-PLACE: webgpu returns to the worker backends', WK('00_bootstrap'),
    "export type WorkerPlacedBackend = Extract<ExecutionBackend, 'javascript' | 'wasm'>;",
    "export type WorkerPlacedBackend = Extract<ExecutionBackend, 'javascript' | 'wasm' | 'webgpu'>;"],
  ['W-PLACE: remote settlement returns to worker offers', WK('00_bootstrap'),
    "export type WorkerSettlementLocation = Extract<SettlementLocation, 'local' | 'live'>;",
    "export type WorkerSettlementLocation = Extract<SettlementLocation, 'local' | 'live' | 'remote'>;"],
  ['W-CUSTODY: the realm-scope grounding loses its custody pin', WK('00_bootstrap'),
    "  extends WorkerGroundingDefinition<readonly [RealmScopeRequirement], unknown, 'intrinsic', 'unowned'> {",
    "  extends WorkerGroundingDefinition<readonly [RealmScopeRequirement], unknown, 'intrinsic'> {"],
  ["W-MSG: opening decorrelates to the union", WK('02_message'),
    "  readonly open: <Decoded, Id extends ChannelId>(\n    request: ChannelOpenRequest<Decoded, Id>,\n  ) => Result<WorkerChannel<Decoded, Id>, NonEmptyTuple<Diagnostic>>;",
    "  readonly open: <Decoded, Id extends ChannelId>(\n    request: ChannelOpenRequest<Decoded, Id>,\n  ) => Result<WorkerChannel<Decoded, ChannelId>, NonEmptyTuple<Diagnostic>>;"],
  ["W-MSG: the receipt decorrelates from its correlation", WK('02_message'),
    "export interface DeliveryReceipt<C extends CorrelationId> {\n  readonly correlation: C;\n}",
    "export interface DeliveryReceipt<C extends CorrelationId> {\n  readonly correlation: CorrelationId;\n}"],
  ["W-TRANSFER: detachment accepts any ticket", WK('03_transfer'),
    "  readonly detachment: Signature<TransferTicket<'moved'>, DetachmentEvidence, NonEmptyTuple<Diagnostic>>;",
    "  readonly detachment: Signature<TransferTicket<TagOf<CustodyMode>>, DetachmentEvidence, NonEmptyTuple<Diagnostic>>;"],
  ["W-TRANSFER: consummation decorrelates", WK('03_transfer'),
    "  readonly consummate: <Mode extends TagOf<CustodyMode>>(\n    ticket: TransferTicket<Mode>,\n  ) => Result<CustodyReceipt<Mode>, NonEmptyTuple<Diagnostic>>;",
    "  readonly consummate: <Mode extends TagOf<CustodyMode>>(\n    ticket: TransferTicket<Mode>,\n  ) => Result<CustodyReceipt<TagOf<CustodyMode>>, NonEmptyTuple<Diagnostic>>;"],
  ['W-MEM: a view loses its buffer identity', WK('04_memory'),
    "export interface SharedMemoryView<\n  Role extends SharedMemoryRole,\n  Id extends SharedBufferId,\n> {\n  readonly buffer: SharedBufferReference<Id>;",
    "export interface SharedMemoryView<\n  Role extends SharedMemoryRole,\n  Id extends SharedBufferId,\n> {\n  readonly buffer: SharedBufferReference;"],
  ['W-QUEUE: the consumer becomes a second producer', WK('05_queue'),
    "  readonly consumer: QueueEndpoint<'consumer', Id>;",
    "  readonly consumer: QueueEndpoint<'producer', Id>;"],
  ['W-EXEC: scheduling becomes a commit identity', WK('06_execution'),
    "  readonly schedule: Signature<ExecutionRequest, ExecutionRequest, NonEmptyTuple<Diagnostic>>;",
    "  readonly schedule: Signature<RuntimeCommit, RuntimeCommit, NonEmptyTuple<Diagnostic>>;"],
  ['W-TOPO: the transfer home vanishes from the roster', WKU,
    "  | '02_message'\n  | '03_transfer'\n  | '04_memory'",
    "  | '02_message'\n  | '04_memory'"],
  ['W-POP: the queue offer vanishes from the population', WKU,
    "    readonly queueAuthority: QueueAuthorityOffer;\n",
    ""],

  // --- edge ---
  ['E-IDENT: the response facility borrows the request identity', ED('09_response'),
    "  readonly id: GroundingId<'liteship.edge.grounding.response-facility'>;",
    "  readonly id: GroundingId<'liteship.edge.grounding.request'>;"],
  ['E-IDENT: the cache offer borrows the store identity', ED('06_cache'),
    "  readonly id: RealizationOfferId<'liteship.edge.offer.cache-authority'>;",
    "  readonly id: RealizationOfferId<'liteship.edge.offer.store'>;"],
  ['E-PLACE: local settlement returns to edge offers', ED('00_bootstrap'),
    "export type EdgeSettlementLocation = Extract<SettlementLocation, 'request'>;",
    "export type EdgeSettlementLocation = Extract<SettlementLocation, 'request' | 'local'>;"],
  ['E-REQ: consumption forgets its address', ED('01_request'),
    "  consumed: { readonly through: ContentAddress<'application/vnd.liteship.edge-body+cbor'> };",
    "  consumed: {};"],
  ['E-EVID: the update source decorrelates', ED('02_evidence'),
    "  extends EvidenceUpdate {\n  readonly source: EvidenceReference<Source>;\n}",
    "  extends EvidenceUpdate {\n  readonly source: EvidenceReference;\n}"],
  ['E-POLICY: origin refusals forget their policy', ED('03_policy'),
    "  origin: { readonly origin: AllowedOrigin; readonly policy: EdgeResponsePolicy['address'] };",
    "  origin: { readonly origin: AllowedOrigin };"],
  ['E-SETTLE: the refusal arm loses its receipt', ED('04_settlement'),
    "  refused: {\n    readonly request: EdgeRequestReference<Id>;\n    readonly diagnostics: NonEmptyTuple<Diagnostic>;\n    readonly receipt: RequestSettlementAddress;\n  };",
    "  refused: {\n    readonly request: EdgeRequestReference<Id>;\n    readonly diagnostics: NonEmptyTuple<Diagnostic>;\n  };"],
  ['E-NET: networking drops the policy', ED('05_network'),
    "    readonly [EdgeNetworkFacilityRequirement, EdgePolicyRequirement],\n    unknown,",
    "    readonly [EdgeNetworkFacilityRequirement],\n    unknown,"],
  ['E-CACHE: keys lose their partition', ED('06_cache'),
    "  readonly variations: NonEmptyTuple<CacheVariation>;\n  readonly partition: CachePartitionKey;",
    "  readonly variations: NonEmptyTuple<CacheVariation>;"],
  ['E-CACHE: a foreign variation arm appears', ED('06_cache'),
    "export type CacheVariation = Algebra<{\n  tenant: {};",
    "export type CacheVariation = Algebra<{\n  session: {};\n  tenant: {};"],
  ['E-EXEC: a handler serves any operation', ED('08_execution'),
    "  readonly id: EdgeHandlerReference;\n  readonly operation: Op;",
    "  readonly id: EdgeHandlerReference;\n  readonly operation: OperationId;"],
  ["E-RESP: a plan becomes committable by itself", ED('09_response'),
    "export interface CommittedResponse<Id extends EdgeRequestId> {\n  readonly plan: ResponsePlan<Id>;\n  readonly receipt: ResponseCommitAddress;\n}",
    "export interface CommittedResponse<Id extends EdgeRequestId> {\n  readonly plan: ResponsePlan<Id>;\n}"],
  ['E-DEFER: a task forgets its ancestry', ED('10_deferred'),
    "  readonly id: DeferredTaskReference;\n  readonly ancestry: EdgeInvocationContext['address'];",
    "  readonly id: DeferredTaskReference;"],
  ['E-TOPO: settlement and network swap surfaces', EDU,
    "  EdgeTypeHome<'04_settlement', EdgeSettlementTypeSurface>,\n  EdgeTypeHome<'05_network', EdgeNetworkTypeSurface>,",
    "  EdgeTypeHome<'04_settlement', EdgeNetworkTypeSurface>,\n  EdgeTypeHome<'05_network', EdgeSettlementTypeSurface>,"],

  // --- server ---
  ['S-IDENT: the tool catalog borrows the operation-catalog identity', SV('07_tool'),
    "  readonly id: GroundingId<'liteship.server.grounding.tool-catalog'>;",
    "  readonly id: GroundingId<'liteship.server.grounding.operation-catalog'>;"],
  ['S-IDENT: the media offer borrows the execution identity', SV('10_media'),
    "  readonly id: RealizationOfferId<'liteship.server.offer.media-authority'>;",
    "  readonly id: RealizationOfferId<'liteship.server.offer.execution-host'>;"],
  ['S-PLACE: webgpu returns to server backends', SV('00_bootstrap'),
    "export type ServerPlacedBackend = Extract<ExecutionBackend, 'javascript' | 'wasm' | 'host-native'>;",
    "export type ServerPlacedBackend = Extract<ExecutionBackend, 'javascript' | 'wasm' | 'host-native' | 'webgpu'>;"],
  ["S-SECRET: a revealed secret grows a serialization surface", SV('02_secret'),
    "export interface RevealedSecret<Id extends SecretId> {\n  readonly reveals: SecretScopedReference<Id>;",
    "export interface RevealedSecret<Id extends SecretId> {\n  readonly serialized: string;\n  readonly reveals: SecretScopedReference<Id>;"],
  ['S-SECRET: revelation decorrelates', SV('02_secret'),
    "  readonly resolve: <Id extends SecretId>(\n    reference: SecretScopedReference<Id>,\n  ) => Result<RevealedSecret<Id>, NonEmptyTuple<Diagnostic>>;",
    "  readonly resolve: <Id extends SecretId>(\n    reference: SecretScopedReference<Id>,\n  ) => Result<RevealedSecret<SecretId>, NonEmptyTuple<Diagnostic>>;"],
  ['S-FS: a path forgets its root', SV('03_filesystem'),
    "> & { readonly root: FilesystemRootReference<Root> };",
    ">;"],
  ['S-DB: the lease becomes eternal', SV('05_database'),
    "export interface TransactionLease {\n  readonly connection: DatabaseConnectionReference;\n  readonly generation: TransactionGeneration;",
    "export interface TransactionLease {\n  readonly connection: DatabaseConnectionReference;"],
  ['S-DB: construction returns a loose array', SV('05_database'),
    "  readonly construct: <Row extends ServerStoreRow>(\n    row: UniqueRequirements<Row>,\n  ) => Result<BindingsFor<Row>, NonEmptyTuple<Diagnostic>>;",
    "  readonly construct: (row: ServerStoreRow) => Result<readonly unknown[], NonEmptyTuple<Diagnostic>>;"],
  ['S-SVC: health loses its stopped receipt', SV('06_service'),
    "  stopped: { readonly receipt: ContentAddress<'application/vnd.liteship.server-service-stop+cbor'> };",
    "  stopped: {};"],
  ['S-TOOL: invocations lose their sandbox', SV('07_tool'),
    "  readonly output: SchemaReference<SchemaId, unknown>;\n  readonly sandbox: ToolSandbox;",
    "  readonly output: SchemaReference<SchemaId, unknown>;"],
  ['S-TOOL: invocation decorrelates', SV('07_tool'),
    "  readonly invoke: <Tool extends ToolId, Profile extends ToolProfileId>(\n    request: ToolInvocationRequest<Tool, Profile>,\n  ) => Result<ToolExecution<Tool, Profile>, NonEmptyTuple<Diagnostic>>;",
    "  readonly invoke: <Tool extends ToolId, Profile extends ToolProfileId>(\n    request: ToolInvocationRequest<Tool, Profile>,\n  ) => Result<ToolExecution<ToolId, Profile>, NonEmptyTuple<Diagnostic>>;"],
  ['S-EXEC: the native driver kind decouples', SV('08_execution'),
    "  ? { readonly backend: Backend; readonly driver: ExecutionBackendDriver & { readonly kind: Backend } }",
    "  ? { readonly backend: Backend; readonly driver: ExecutionBackendDriver }"],
  ['S-OP: a handler loses idempotency', SV('09_operation'),
    "  readonly capabilities: BindingsFor<Requirements>;\n  readonly idempotency: IdempotencyResource;\n  readonly handle:",
    "  readonly capabilities: BindingsFor<Requirements>;\n  readonly handle:"],
  ['S-MEDIA: a job forgets its source revision', SV('10_media'),
    "  readonly id: MediaJobReference<Id>;\n  readonly source: ContentAddress<'application/vnd.liteship.program+cbor'>;",
    "  readonly id: MediaJobReference<Id>;"],
  ['S-POP: the secret provider vanishes from the offers', SVU,
    "    readonly secretProvider: SecretProviderOffer;\n",
    ""],

  ["F2: an instance closes any instance", WK('01_instance'),
    "  readonly close: Signature<\n    WorkerInstanceReference<Id>,",
    "  readonly close: Signature<\n    WorkerInstanceReference,"],
  ["F2: an envelope forgets its channel identity", WK('02_message'),
    "> {\n  readonly channel: ChannelReference<Channel>;\n  readonly correlation: C;",
    "> {\n  readonly channel: ChannelReference;\n  readonly correlation: C;"],
  ["F3: the bare ticket form returns", WK('03_transfer'),
    "/** Type summary consumed by the worker topology. */",
    "export type TheBareTicketFormStaysIllegal = TransferTicket extends {\n  readonly channel: ChannelReference;\n}\n  ? true\n  : false;\n\n/** Type summary consumed by the worker topology. */"],
  ["F3: transfer stops requiring messaging", WK('03_transfer'),
    "    readonly [TransferFacilityRequirement, MessagingRequirement],",
    "    readonly [TransferFacilityRequirement],"],
  ["F3: the view regrows its own layout", WK('04_memory'),
    "  readonly buffer: SharedBufferReference<Id>;\n  readonly role: Role;\n  readonly generation: TransactionGeneration;",
    "  readonly buffer: SharedBufferReference<Id>;\n  readonly role: Role;\n  readonly layout: SharedMemoryLayoutAddress;\n  readonly generation: TransactionGeneration;"],
  ["F3: the worker host loses its session path", WK('06_execution'),
    "  readonly begin: <Id extends WorkerTaskId>(\n    request: WorkerExecutionRequest<Id>,\n  ) => Result<WorkerExecutionSession<Id>, NonEmptyTuple<Diagnostic>>;\n",
    ""],
  ["F3: a worker session loses its result", WK('06_execution'),
    "  readonly result: Signature<WorkerTaskReference<Id>, ExecutionResultEnvelope<Id>, NonEmptyTuple<Diagnostic>>;\n",
    ""],
  ["F4: settlement forgets its request", ED('04_settlement'),
    "export interface RequestSettlementRequest<Id extends EdgeRequestId> {\n  readonly request: EdgeRequestReference<Id>;\n",
    "export interface RequestSettlementRequest<Id extends EdgeRequestId> {\n"],
  ["F4: request consumption goes broad", ED('01_request'),
    "  readonly consume: Signature<\n    EdgeRequestReference<Id>,",
    "  readonly consume: Signature<\n    EdgeRequestReference,"],
  ["F5: the edge connection loses its send", ED('05_network'),
    "  readonly send: Signature<EdgeEncodedChunk, OutboundConnectionReference, NonEmptyTuple<Diagnostic>>;\n",
    ""],
  ["F5: streaming loses its finish", ED('09_response'),
    "  readonly finish: Signature<ResponsePlan<Id>, CommittedResponse<Id>, NonEmptyTuple<Diagnostic>>;\n",
    ""],
  ["F5: deferred work loses its work", ED('10_deferred'),
    "  readonly ancestry: EdgeInvocationContext['address'];\n  readonly work: OperationInvocation;\n  readonly scope: RequirementRow;\n  readonly bound: DeferredBound;\n  readonly outcome: DeferredOutcome;",
    "  readonly ancestry: EdgeInvocationContext['address'];\n  readonly scope: RequirementRow;\n  readonly bound: DeferredBound;\n  readonly outcome: DeferredOutcome;"],
  ["F6: the invocation identity erases in core", OP,
    "export interface OperationInvocation<Input = unknown, Op extends OperationId = OperationId> {\n  readonly operation: OperationReference<Op>;",
    "export interface OperationInvocation<Input = unknown, Op extends OperationId = OperationId> {\n  readonly operation: OperationReference;"],
  ["F6: the definition identity erases in core", OP,
    "  Op extends OperationId = OperationId,\n> {\n  readonly id: Op;",
    "  Op extends OperationId = OperationId,\n> {\n  readonly id: OperationId;"],
  ["C4: the use path vanishes", SV('02_secret'),
    "  readonly use: Signature<SecretConsumer<Id>, SecretUseReceipt<Id>, NonEmptyTuple<Diagnostic>>;\n",
    ""],
  ["F7: the filesystem loses its stream family", SV('03_filesystem'),
    "  readonly stream: <Root extends FilesystemRootId>(\n    request: FileOpenRequest<Root>,\n  ) => Result<FileStream<Root>, NonEmptyTuple<Diagnostic>>;\n",
    ""],
  ["F8: the listener returns bare references again", SV('04_network'),
    "  readonly accept: Signature<\n    ServerBufferBound,\n    readonly ServerConnection<Uint8Array>[],\n    NonEmptyTuple<Diagnostic>\n  >;",
    "  readonly accept: Signature<\n    ServerBufferBound,\n    readonly ServerConnectionReference[],\n    NonEmptyTuple<Diagnostic>\n  >;"],
  ["F8: the provider loses its statement path", SV('05_database'),
    "  readonly statement: Signature<StatementRequest, StatementResource, NonEmptyTuple<Diagnostic>>;\n",
    ""],
  ["F8: a service owns nothing again", SV('06_service'),
    "  readonly configuration: ContentAddress<'application/vnd.liteship.server-service-configuration+cbor'>;\n  readonly owns: NonEmptyTuple<OperationInvocation>;\n  readonly health: ServiceHealth;",
    "  readonly configuration: ContentAddress<'application/vnd.liteship.server-service-configuration+cbor'>;\n  readonly health: ServiceHealth;"],
  ["F9: a tool invocation loses its value", SV('07_tool'),
    "  readonly input: SchemaReference<SchemaId, unknown>;\n  readonly value: CanonicalValue;\n",
    "  readonly input: SchemaReference<SchemaId, unknown>;\n"],
  ["F9: the server host loses its session path", SV('08_execution'),
    "  readonly begin: Signature<ExecutionRequest, ServerExecutionSession<ServerTaskId>, NonEmptyTuple<Diagnostic>>;\n",
    ""],
  ["C5: the media contract regresses to a coordinate", SV('10_media'),
    "  readonly contract: SchemaReference<Contract, Frame>;\n  readonly render: ServerRenderProfile<Render>;\n  readonly tool: ToolProfile<Tool, Profile>;\n  readonly destination: AdmittedPath<Out>;\n  readonly frames:",
    "  readonly contract: SchemaReference<Contract, ServerSamplePosition>;\n  readonly render: ServerRenderProfile<Render>;\n  readonly tool: ToolProfile<Tool, Profile>;\n  readonly destination: AdmittedPath<Out>;\n  readonly frames:"],

  ["C1: the edge handler hardcodes empty requirements again", ED('08_execution'),
    "  readonly operation: Op;\n  readonly definition: OperationDefinition<Input, Output, Failure, Requirements, Op>;\n  readonly capabilities: BindingsFor<Requirements>;\n  readonly handle:",
    "  readonly operation: Op;\n  readonly definition: OperationDefinition<Input, Output, Failure, readonly [], Op>;\n  readonly capabilities: BindingsFor<Requirements>;\n  readonly handle:"],
  ["C1: the edge capabilities go free", ED('08_execution'),
    "  readonly capabilities: BindingsFor<Requirements>;\n  readonly handle:",
    "  readonly capabilities: RequirementRow;\n  readonly handle:"],
  ["C1: the server handler hardcodes empty requirements again", SV('09_operation'),
    "  readonly operation: Op;\n  readonly definition: OperationDefinition<Input, Output, Failure, Requirements, Op>;\n  readonly capabilities: BindingsFor<Requirements>;\n  readonly idempotency:",
    "  readonly operation: Op;\n  readonly definition: OperationDefinition<Input, Output, Failure, readonly [], Op>;\n  readonly capabilities: BindingsFor<Requirements>;\n  readonly idempotency:"],
  ["C1: the server capabilities go free", SV('09_operation'),
    "  readonly capabilities: BindingsFor<Requirements>;\n  readonly idempotency:",
    "  readonly capabilities: RequirementRow;\n  readonly idempotency:"],
  ["C2: construction forgets its layout", WK('04_memory'),
    "  readonly construct: <L extends MemoryLayoutId, Id extends SharedBufferId>(\n    request: SharedMemoryRequest<L, Id>,\n  ) => Result<SharedMemoryBuffer<L, Id>, NonEmptyTuple<Diagnostic>>;",
    "  readonly construct: <L extends MemoryLayoutId, Id extends SharedBufferId>(\n    request: SharedMemoryRequest<L, Id>,\n  ) => Result<SharedMemoryBuffer<MemoryLayoutId, Id>, NonEmptyTuple<Diagnostic>>;"],
  ["C2: a batch forgets its queue", WK('05_queue'),
    "export interface QueueBatch<Payload, Id extends QueueId> {\n  readonly queue: QueueReference<Id>;\n",
    "export interface QueueBatch<Payload, Id extends QueueId> {\n"],
  ["C2: the queue buffer decorrelates", WK('05_queue'),
    "> {\n  readonly id: QueueReference<Id>;\n  readonly buffer: SharedBufferReference<Buf>;\n  readonly admission:",
    "> {\n  readonly id: QueueReference<Id>;\n  readonly buffer: SharedBufferReference;\n  readonly admission:"],
  ["C2: the envelope forgets its session", WK('06_execution'),
    "export interface ExecutionResultEnvelope<Id extends WorkerTaskId> {\n  readonly session: WorkerTaskReference<Id>;\n",
    "export interface ExecutionResultEnvelope<Id extends WorkerTaskId> {\n"],
  ["C3: clone regresses to a state flip", ED('01_request'),
    "  readonly clone: Signature<EdgeRequestReference<Id>, RequestClone<Id>, NonEmptyTuple<Diagnostic>>;",
    "  readonly clone: Signature<EdgeRequestReference<Id>, CaseOf<BodyConsumption, 'cloned'>, NonEmptyTuple<Diagnostic>>;"],
  ["C3: the request loses its trace", ED('01_request'),
    "  readonly trace: ContentAddress<'application/vnd.liteship.edge-request-trace+cbor'>;\n",
    ""],
  ["C3: the outbound connection forgets its request", ED('05_network'),
    "  readonly id: OutboundConnectionReference;\n  readonly request: OutboundRequestReference<Rid>;\n",
    "  readonly id: OutboundConnectionReference;\n"],
  ["C3: the commit authority goes universal again", ED('09_response'),
    "export interface ResponseCommitAuthority<Id extends EdgeRequestId> {\n  readonly request: EdgeRequestReference<Id>;\n",
    "export interface ResponseCommitAuthority<Id extends EdgeRequestId> {\n"],
  ["C4: the material field returns to the revelation", SV('02_secret'),
    "export interface RevealedSecret<Id extends SecretId> {\n  readonly reveals: SecretScopedReference<Id>;\n",
    "export interface RevealedSecret<Id extends SecretId> {\n  readonly reveals: SecretScopedReference<Id>;\n  readonly material: SecretMaterial;\n"],
  ["C5: statements lose their deadline", SV('05_database'),
    "  readonly output: SchemaReference<SchemaId, unknown>;\n  readonly deadline: Deadline;\n}",
    "  readonly output: SchemaReference<SchemaId, unknown>;\n}"],
  ["C5: the media job forgets its input", SV('10_media'),
    "  readonly tool: ToolProfile<Tool, Profile>;\n  readonly destination: AdmittedPath<Out>;\n  readonly frames: MediaSource<ServerPhysicalFrame<Representation, Frame, Render>, Source>;",
    "  readonly tool: ToolProfile<Tool, Profile>;\n  readonly frames: MediaSource<ServerPhysicalFrame<Representation, Frame, Render>, Source>;"],

  // --- seal ---
  ['SEAL: a fifth child sneaks into the roster', HU,
    "export type HostChildRoster = readonly ['web', 'worker', 'edge', 'server'];",
    "export type HostChildRoster = readonly ['web', 'worker', 'edge', 'server', 'native'];"],
  ['H-EXEC: begin decorrelates to the broad session', WK('06_execution'),
    "  ) => Result<WorkerExecutionSession<Id>, NonEmptyTuple<Diagnostic>>;",
    "  ) => Result<WorkerExecutionSession<WorkerTaskId>, NonEmptyTuple<Diagnostic>>;"],
  ['H-EXEC: the session request drops its task identity', WK('06_execution'),
    "export interface WorkerExecutionRequest<Id extends WorkerTaskId> {\n  readonly task: WorkerTaskReference<Id>;",
    "export interface WorkerExecutionRequest<Id extends WorkerTaskId> {\n  readonly task: WorkerTaskReference;"],
  ['H-MEM: the constructed buffer id broadens', WK('04_memory'),
    "export interface SharedMemoryBuffer<L extends MemoryLayoutId, Id extends SharedBufferId> {\n  readonly id: SharedBufferReference<Id>;",
    "export interface SharedMemoryBuffer<L extends MemoryLayoutId, Id extends SharedBufferId> {\n  readonly id: SharedBufferReference;"],
  ['H-MEM: the construction request forgets its identity', WK('04_memory'),
    "export interface SharedMemoryRequest<L extends MemoryLayoutId, Id extends SharedBufferId> {\n  readonly buffer: SharedBufferReference<Id>;",
    "export interface SharedMemoryRequest<L extends MemoryLayoutId, Id extends SharedBufferId> {\n  readonly buffer: SharedBufferReference;"],
  ['H-RESP: the requirement re-carries the broad authority', ED('09_response'),
    "export type ResponseCommitRequirement = Hole<'liteship.edge.response-commit', ResponseCommitGrant>;",
    "export type ResponseCommitRequirement = Hole<'liteship.edge.response-commit', ResponseCommitAuthority<EdgeRequestId>>;"],
  ['H-RESP: the grant decorrelates', ED('09_response'),
    "  ) => Result<ResponseCommitAuthority<Id>, ResponseFailure>;",
    "  ) => Result<ResponseCommitAuthority<EdgeRequestId>, ResponseFailure>;"],
  ['H-MEDIA: render decorrelates from its request', SV('10_media'),
    "    ServerRenderJob<Representation, Contract, Frame, Render, Tool, Profile, Out, Id, Source>,",
    "    ServerRenderJob<Representation, Contract, Frame, Render, Tool, ToolProfileId, Out, Id, Source>,"],
  ['H-MEDIA: the output stream forgets its job', SV('10_media'),
    "  readonly frames: MediaSource<ServerPhysicalFrame<Representation, Frame, Render>, Source>;",
    "  readonly frames: MediaSource<ServerPhysicalFrame<Representation, Frame, Render>, MediaSourceId>;"],
  ['H-MEDIA: the request erases its input stream', SV('10_media'),
    "  readonly tool: ToolProfile<Tool, Profile>;\n  readonly destination: AdmittedPath<Out>;\n}",
    "  readonly tool: ToolProfile<Tool, Profile>;\n  readonly destination: AdmittedPath<FilesystemRootId>;\n}"],
  ['H-MEDIA: the request job identity goes free', SV('10_media'),
    "  readonly id: MediaJobReference<Id>;\n  readonly source:",
    "  readonly id: MediaJobReference;\n  readonly source:"],
  ['SEAL: the worker child vanishes from the roster', HU,
    "export type HostChildName = 'web' | 'worker' | 'edge' | 'server';",
    "export type HostChildName = 'web' | 'edge' | 'server';"],
];

process.exit(runBank('hosts3', M).clean ? 0 : 1);
