// The web host child.
//
// Mutations carried verbatim from the ratified verification kit; only the
// plumbing changed. Each entry rewrites one exact span of the live tree and
// must die on a named law. An entry whose anchor text is absent reports
// MISSING and fails the bank -- a bank that has drifted off the source must
// never be mistaken for a bank that passed.

import { runBank } from '../harness.mjs';

const TD = 'types.d.ts';
const W = (h) => `01_hosts/web/${h}/types.ts`;
const UM = '01_hosts/web/types.ts';
const RT = '00_core/16_runtime/types.ts';
const ST = '00_core/13_stream/types.ts';
const CM2 = '00_core/14_compiler/types.ts';

const M = [
  // --- bootstrap: realm, placement, origin, identity pins ---
  ['BOOT: web realm widens to every host realm', W('00_bootstrap'),
    `export type WebRealm = Extract<HostRealm, 'web'>;`,
    `export type WebRealm = HostRealm;`],
  ['BOOT: a grounding loses its realm pin', W('00_bootstrap'),
    `  readonly host: WebHostReference;\n  readonly realm: WebRealm;\n  readonly origin:`,
    `  readonly host: WebHostReference;\n  readonly origin:`],
  ['BOOT: a grounding slot loses its origin pin', W('00_bootstrap'),
    `  readonly realm: WebRealm;\n  readonly origin: CaseOf<HostGroundingOrigin, Origin>;`,
    `  readonly realm: WebRealm;`],
  ['PLACEMENT: html-css returns as a residual backend', W('00_bootstrap'),
    `export type WebPlacedBackend = Extract<ExecutionBackend, 'javascript' | 'wasm' | 'webgpu'>;`,
    `export type WebPlacedBackend = Extract<ExecutionBackend, 'javascript' | 'wasm' | 'webgpu' | 'html-css'>;`],
  ['PLACEMENT: remote is excluded from web settlement', W('00_bootstrap'),
    `export type WebSettlementLocation = Extract<SettlementLocation, 'local' | 'live' | 'remote'>;`,
    `export type WebSettlementLocation = Extract<SettlementLocation, 'local' | 'live'>;`],
  ['PLACEMENT: a web offer advertises another realm', W('00_bootstrap'),
    `  readonly realms: NonEmptyTuple<WebRealm>;\n  readonly locations: NonEmptyTuple<WebSettlementLocation>;`,
    `  readonly locations: NonEmptyTuple<WebSettlementLocation>;`],

  // --- region: manager, boundary-bearing membership, lease ---
  ['REGION: authority accepts a committee of writers', W('01_region'),
    `  readonly region: RegionReference;\n  readonly writer: RegionWriterReference;\n  readonly boundary: RegionBoundary;`,
    `  readonly region: RegionReference;\n  readonly writer: readonly RegionWriterReference[];\n  readonly boundary: RegionBoundary;`],
  ['REGION: a foreign region grows a writer', W('01_region'),
    `  foreign: {};\n}>;`,
    `  foreign: { readonly writer: RegionWriterReference };\n}>;`],
  ['REGION: a raw selector subject sneaks in', W('01_region'),
    `  target: { readonly target: ProjectionTargetReference };\n}>;`,
    `  target: { readonly target: ProjectionTargetReference };\n  selector: { readonly css: string };\n}>;`],
  ['REGION: a membership loses its physical boundary', W('01_region'),
    `  readonly writer: RegionWriterReference;\n  readonly boundary: RegionBoundary;\n}`,
    `  readonly writer: RegionWriterReference;\n}`],
  ['REGION: a claim stops consuming an admitted mount', W('01_region'),
    `export interface RegionClaimRequest {\n  readonly mount: MountRegion;`,
    `export interface RegionClaimRequest {`],
  ['REGION: release constructs a provider again', W('01_region'),
    `  readonly release: Signature<RegionMembership, RegionReference, NonEmptyTuple<Diagnostic>>;`,
    `  readonly release: Signature<RegionClaimRequest, RegionMembership, NonEmptyTuple<Diagnostic>>;`],
  ['REGION: a lease floats free of its membership', W('01_region'),
    `export interface RegionLeaseRequest {\n  readonly membership: RegionMembership;`,
    `export interface RegionLeaseRequest {`],
  ['REGION: the lease restates region and writer', W('01_region'),
    `export interface RegionWriteAuthority {\n  readonly membership: RegionMembership;`,
    `export interface RegionWriteAuthority {\n  readonly membership: RegionMembership;\n  readonly region: RegionReference;`],
  ['REGION: discovery goes revision-blind', W('01_region'),
    `export interface RegionResolveRequest {\n  readonly region: RegionReference;\n  readonly revision: RevisionReference;`,
    `export interface RegionResolveRequest {\n  readonly region: RegionReference;`],
  ['REGION: the manager offer borrows another identity', W('01_region'),
    `  readonly id: RealizationOfferId<'liteship.web.offer.region-authority'>;`,
    `  readonly id: RealizationOfferId;`],

  // --- security ---
  ['SEC: the policy turns into a denylist', W('02_security'),
    `  readonly schemes: readonly AllowedUrlScheme[];`,
    `  readonly denied: readonly string[];`],
  ['SEC: the network edge escapes the allowlists', W('02_security'),
    `  readonly origins: readonly AllowedEndpointOrigin[];\n  readonly credentials: readonly CredentialsMode[];`,
    `  readonly credentials: readonly CredentialsMode[];`],
  ['SEC: a scheme refusal claims it happened at a listener', W('02_security'),
    `  'scheme-refused': { readonly sink: 'url'; readonly diagnostics: NonEmptyTuple<Diagnostic> };`,
    `  'scheme-refused': { readonly sink: WebSinkKind; readonly diagnostics: NonEmptyTuple<Diagnostic> };`],

  // --- event ---
  ['EVENT: a free callback arm appears', W('03_event'),
    `}>;\n\n/** One live subscription: identified, attached to persistent membership, owned once. */`,
    `  callback: { readonly handler: (value: unknown) => void };\n}>;\n\n/** One live subscription: identified, attached to persistent membership, owned once. */`],
  ['EVENT: observation loses its target', W('03_event'),
    `export interface EventObservationRequest {\n  readonly target: WebNodeReference;`,
    `export interface EventObservationRequest {`],
  ['EVENT: observation loses its payload contract', W('03_event'),
    `  readonly descriptor: WebEventDescriptor;\n  readonly payload: SchemaReference;\n}`,
    `  readonly descriptor: WebEventDescriptor;\n}`],
  ['EVENT: the operation projection stops producing an invocation', W('03_event'),
    `    readonly project: Signature<\n      AdmittedEventObservation,\n      OperationInvocation,\n      NonEmptyTuple<Diagnostic>\n    >;`,
    `    readonly project: Signature<\n      AdmittedEventObservation,\n      unknown,\n      NonEmptyTuple<Diagnostic>\n    >;`],
  ['EVENT: subscribing stops consuming the complete request', W('03_event'),
    `  readonly subscribe: Signature<EventSubscriptionRequest, EventSubscription, NonEmptyTuple<Diagnostic>>;`,
    `  readonly subscribe: Signature<unknown, EventSubscription, NonEmptyTuple<Diagnostic>>;`],
  ['EVENT: a listener stops being owned', W('03_event'),
    `  readonly owner: RealizationInstanceReference;\n  readonly lifecycle: CaseOf<RealizationLifecycle, 'owned'>;`,
    `  readonly owner: RealizationInstanceReference;\n  readonly lifecycle: RealizationLifecycle;`],
  ['EVENT: the authority stops requiring the region manager', W('03_event'),
    `    readonly [EventFacilityRequirement, RegionAuthorityRequirement],\n    unknown,`,
    `    readonly [EventFacilityRequirement],\n    unknown,`],

  // --- projection ---
  ['PROJ: foreign output becomes writable', W('04_projection'),
    `    readonly content: GeneratedStructureSnapshot | GeneratedStructurePatch;\n  };\n}>;`,
    `    readonly content: GeneratedStructureSnapshot | GeneratedStructurePatch;\n  };\n  foreign: {};\n}>;`],
  ['PROJ: a trusted fragment degrades to raw markup', W('04_projection'),
    `  'trusted-fragment': { readonly patch: TrustedFragmentPatch };`,
    `  'trusted-fragment': { readonly patch: string };`],
  ['PROJ: a sibling admission returns beside the content', W('04_projection'),
    `  'generated-structure': {\n    readonly content: GeneratedStructureSnapshot | GeneratedStructurePatch;\n  };`,
    `  'generated-structure': {\n    readonly admission: GeneratedStructureAdmission;\n    readonly content: GeneratedStructureSnapshot | GeneratedStructurePatch;\n  };`],
  ['PROJ: the renderer mints a neighboring catalog species', W('04_projection'),
    `export interface ComponentRendererCatalog {\n  readonly catalog: ComponentCatalogAddress;`,
    `export interface ComponentRendererCatalog {\n  readonly catalog: ContentAddress<'application/vnd.liteship.web-component-catalog+cbor'>;`],
  ['PROJ: the physical commit drops the semantic commit', W('04_projection'),
    `export interface ProjectionCommit {\n  readonly commit: RuntimeCommit;\n  readonly lease: RegionWriteAuthority;`,
    `export interface ProjectionCommit {\n  readonly lease: RegionWriteAuthority;`],
  ['PROJ: a sibling revision returns to the commit', W('04_projection'),
    `  readonly lease: RegionWriteAuthority;\n  readonly families: readonly WebWriteFamily[];`,
    `  readonly lease: RegionWriteAuthority;\n  readonly revision: RevisionReference;\n  readonly families: readonly WebWriteFamily[];`],
  ['PROJ: application stops requiring the renderer catalog', W('04_projection'),
    `      RegionAuthorityRequirement,\n      SinkPolicyRequirement,\n      RendererCatalogRequirement,\n      EventAuthorityRequirement,\n    ],\n    unknown,`,
    `      RegionAuthorityRequirement,\n      SinkPolicyRequirement,\n      EventAuthorityRequirement,\n    ],\n    unknown,`],

  // --- evidence ---
  ["EVID: a producer asserts an undeclared source", W('05_evidence'),
    "  readonly produces: Source;\n  readonly lifecycle: CaseOf<RealizationLifecycle, 'unowned'>;",
    "  readonly produces: string;\n  readonly lifecycle: CaseOf<RealizationLifecycle, 'unowned'>;"],
  ["EVID: a probe starts owning resources", W('05_evidence'),
    "  readonly produces: Source;\n  readonly lifecycle: CaseOf<RealizationLifecycle, 'unowned'>;\n}",
    "  readonly produces: Source;\n  readonly lifecycle: CaseOf<RealizationLifecycle, 'owned'>;\n}"],
  ["EVID: the facility loses its watch operation", W('05_evidence'),
    "  readonly read: <Source extends EvidenceSourceId>(\n    source: Source,\n  ) => Result<SourcedEvidenceUpdate<Source>, NonEmptyTuple<Diagnostic>>;\n  readonly watch: <Source extends EvidenceSourceId>(\n    source: Source,\n  ) => Result<WebWatcher<Source>, NonEmptyTuple<Diagnostic>>;",
    "  readonly read: <Source extends EvidenceSourceId>(\n    source: Source,\n  ) => Result<SourcedEvidenceUpdate<Source>, NonEmptyTuple<Diagnostic>>;"],

  // --- transport ---
  ["TRANS: fetch grows replay machinery", W('06_transport'),
    "export type TransportOpenRequest<Decoded = CanonicalValue> = Algebra<{\n  fetch: OpenRequestCommon<Decoded>;",
    "export type TransportOpenRequest<Decoded = CanonicalValue> = Algebra<{\n  fetch: OpenRequestCommon<Decoded> & { readonly resume: StreamResumeRequest };"],
  ["TRANS: the decoder degrades to a bare tag", W('06_transport'),
    "interface OpenRequestCommon<Decoded> {\n  readonly endpoint: TransportEndpoint;\n  readonly decoder: CarrierDecodeContract<Decoded>;",
    "interface OpenRequestCommon<Decoded> {\n  readonly endpoint: TransportEndpoint;\n  readonly decoder: TagOf<CarrierDecoder>;"],
  ['TRANS: a carrier stops decoding', W('06_transport'),
    `  json: { readonly contract: CarrierDecodeContract<CanonicalValue> };`,
    `  json: {};`],
  ['TRANS: a stealth carrier appears', W('06_transport'),
    `  binary: { readonly contract: CarrierDecodeContract<Uint8Array> };\n}>;`,
    `  binary: { readonly contract: CarrierDecodeContract<Uint8Array> };\n  'eval-script': {};\n}>;`],
  ["TRANS: receive regresses to raw bytes", W('06_transport'),
    "  readonly receive: Signature<BufferBound, readonly Decoded[], NonEmptyTuple<Diagnostic>>;",
    "  readonly receive: Signature<BufferBound, readonly EncodedChunk[], NonEmptyTuple<Diagnostic>>;"],
  ['TRANS: event-source resumption drops stream identity', W('06_transport'),
    `    readonly reconnection: ReconnectionPolicy;\n    readonly resume: StreamResumeRequest;`,
    `    readonly reconnection: ReconnectionPolicy;`],
  ["TRANS: connections become unbounded", W('06_transport'),
    "  readonly decoder: CarrierDecodeContract<Decoded>;\n  readonly buffer: BufferBound;\n  readonly receive:",
    "  readonly decoder: CarrierDecodeContract<Decoded>;\n  readonly receive:"],

  // --- persistence ---
  ['PERSIST: the store row admits any hole', W('07_persistence'),
    `export type BrowserStoreRow = readonly [BrowserStoreRequirement, ...BrowserStoreRequirement[]];`,
    `export type BrowserStoreRow = readonly [Hole<string, unknown>, ...Hole<string, unknown>[]];`],
  ["PERSIST: construction returns a loose union array", W('07_persistence'),
    "  readonly construct: <Row extends BrowserStoreRow>(\n    row: UniqueRequirements<Row>,\n  ) => Result<BindingsFor<Row>, NonEmptyTuple<Diagnostic>>;",
    "  readonly construct: (row: BrowserStoreRow) => Result<readonly unknown[], NonEmptyTuple<Diagnostic>>;"],
  ["F7: duplicate store requests become acceptable again", W('07_persistence'),
    "(\n    row: UniqueRequirements<Row>,\n  )",
    "(\n    row: Row,\n  )"],
  ['PERSIST: the database opens to a bare lifetime', W('07_persistence'),
    `  readonly open: Signature<BrowserDatabaseName, BrowserDatabase, NonEmptyTuple<Diagnostic>>;`,
    `  readonly open: Signature<BrowserDatabaseName, OwnedResource, NonEmptyTuple<Diagnostic>>;`],
  ['PERSIST: a store provider constructs itself from nothing', W('07_persistence'),
    `    Provides,\n    readonly [DatabaseFacilityRequirement],`,
    `    Provides,\n    readonly [],`],

  // --- media ---
  ['MEDIA: the sample clock degrades to monotonic time', W('08_media'),
    `  readonly position: SamplePosition;\n  readonly scheduled: MonotonicNanoseconds;`,
    `  readonly position: MonotonicNanoseconds;\n  readonly scheduled: MonotonicNanoseconds;`],
  ["MEDIA: the generic provider starts supplying the clock", W('08_media'),
    "  readonly construct: Signature<\n    Exclude<WebMediaResourceKind, AudioResourceKind>,\n    WebMediaResource<'owned'>,",
    "  readonly construct: Signature<\n    Exclude<WebMediaResourceKind, AudioResourceKind>,\n    AudioRuntimeInstance,"],
  ["MEDIA: the audio runtime stops carrying the clock", W('08_media'),
    "  readonly construct: Signature<\n    AudioResourceKind,\n    AudioRuntimeInstance,",
    "  readonly construct: Signature<\n    AudioResourceKind,\n    WebMediaResource<'owned'>,"],
  ["MEDIA: retained custody becomes unrepresentable", W('08_media'),
    "  readonly kind: Kind;\n  readonly lifecycle: CaseOf<RealizationLifecycle, Life>;\n}",
    "  readonly kind: Kind;\n  readonly lifecycle: CaseOf<RealizationLifecycle, Life & 'owned'>;\n}"],

  // --- graphics ---
  ['GFX: loss fabricates a failure', W('09_graphics'),
    `  'context-lost': {\n    readonly resource: GraphicsResourceReference;\n    readonly evidence: EvidenceUpdate;`,
    `  'context-lost': {\n    readonly resource: GraphicsResourceReference;\n    readonly failure: unknown;\n    readonly evidence: EvidenceUpdate;`],
  ['GFX: acquisition goes target-blind', W('09_graphics'),
    `export interface GraphicsAcquisitionRequest {\n  readonly kind: GraphicsContextKind;\n  readonly target: WebNodeReference;`,
    `export interface GraphicsAcquisitionRequest {\n  readonly kind: GraphicsContextKind;`],
  ['GFX: the injected path to the egress disappears', W('09_graphics'),
    `  readonly adopt: Signature<WebGraphicsResource, WebGraphicsResource, NonEmptyTuple<Diagnostic>>;\n  readonly egress: GraphicsEgress;`,
    `  readonly egress: GraphicsEgress;`],
  ["GFX: the egress applies loose writes", W('09_graphics'),
    "  readonly apply: Signature<\n    GraphicsApplication,",
    "  readonly apply: Signature<\n    unknown,"],
  ["F9: the graphics application forgets its resource", W('09_graphics'),
    "export interface GraphicsApplication {\n  readonly commit: RuntimeCommit;\n  readonly resource: GraphicsResourceReference;\n}",
    "export interface GraphicsApplication {\n  readonly commit: RuntimeCommit;\n}"],

  // --- execution ---
  ['EXEC: a backend and its driver disagree', W('10_execution'),
    `type DriverBinding<Backend> = Backend extends BrowserExecutionBackend\n  ? { readonly backend: Backend; readonly driver: ExecutionBackendDriver & { readonly kind: Backend } }\n  : never;`,
    `type DriverBinding<Backend> = Backend extends BrowserExecutionBackend\n  ? { readonly backend: Backend; readonly driver: ExecutionBackendDriver }\n  : never;`],
  ['EXEC: the host loses its execution operation', W('10_execution'),
    `  readonly drivers: NonEmptyTuple<BoundDriver>;\n  readonly executor: RuntimeExecutor;`,
    `  readonly drivers: NonEmptyTuple<BoundDriver>;`],
  ["F11: scheduling becomes a commit identity function again", W('10_execution'),
    "  readonly schedule: Signature<ExecutionRequest, ExecutionRequest, NonEmptyTuple<Diagnostic>>;",
    "  readonly schedule: Signature<RuntimeCommit, RuntimeCommit, NonEmptyTuple<Diagnostic>>;"],
  ['EXEC: execution drops the projection authority', W('10_execution'),
    `    readonly [SchedulingFacilityRequirement, CommitApplicationRequirement],\n    NonEmptyTuple<BrowserExecutionBackend>,`,
    `    readonly [SchedulingFacilityRequirement],\n    NonEmptyTuple<BrowserExecutionBackend>,`],
  ['EXEC: the handoff loses its runtime commit', W('10_execution'),
    `  readonly commit: RuntimeCommit;\n  readonly applied: WebCommitAddress;`,
    `  readonly commit: unknown;\n  readonly applied: WebCommitAddress;`],
  ["SPECULATE: prepared work becomes un-discardable", W('10_execution'),
    "  readonly discard: Signature<PreparedWork, SpeculativeCandidateReference, NonEmptyTuple<Diagnostic>>;",
    "  readonly discard: Signature<unknown, SpeculativeCandidateReference, NonEmptyTuple<Diagnostic>>;"],
  ["F13: preparation loses its commit path", W('10_execution'),
    "  readonly consume: Signature<PreparationConsumption, PreparationDisposition, NonEmptyTuple<Diagnostic>>;\n",
    ""],

  // --- island ---
  ['ISLAND: an inactive island fabricates diagnostics', W('11_island'),
    `  inactive: { readonly join: IslandJoin };`,
    `  inactive: { readonly join: IslandJoin; readonly diagnostics: readonly unknown[] };`],
  ['ISLAND: the active instance blurs to unknown', W('11_island'),
    `  active: { readonly instance: IslandInstance };`,
    `  active: { readonly instance: unknown };`],
  ['ISLAND: a sibling stream returns to the resume window', W('11_island'),
    `export interface IslandResumeWindow {\n  readonly resume: StreamResumeRequest;`,
    `export interface IslandResumeWindow {\n  readonly stream: unknown;\n  readonly resume: StreamResumeRequest;`],
  ["ISLAND: a frozen transaction authority returns to the island", W('11_island'),
    "  readonly receipt: ContentAddress<'application/vnd.liteship.web-island-activation+cbor'>;\n  readonly lifecycle:",
    "  readonly receipt: ContentAddress<'application/vnd.liteship.web-island-activation+cbor'>;\n  readonly authority: unknown;\n  readonly lifecycle:"],
  ['ISLAND: activation stops being repeatable', W('11_island'),
    `  readonly activate: Signature<IslandJoin, IslandInstance, NonEmptyTuple<Diagnostic>>;`,
    `  readonly activate: Signature<unknown, IslandInstance, NonEmptyTuple<Diagnostic>>;`],
  ['ISLAND: activation stops composing the host', W('11_island'),
    `    readonly [\n      RegionAuthorityRequirement,\n      CommitApplicationRequirement,\n      WebExecutionRequirement,\n      ...Extra,\n    ],`,
    `    readonly [...Extra],`],
  ['ISLAND: the membership restates itself as a twin', W('11_island'),
    `  readonly membership: RegionMembership;\n  readonly address: ContentAddress<'application/vnd.liteship.web-island-join+cbor'>;`,
    `  readonly membership: { readonly region: unknown; readonly writer: unknown };\n  readonly address: ContentAddress<'application/vnd.liteship.web-island-join+cbor'>;`],
  ['ISLAND: activation joins a floating revision', W('11_island'),
    `  readonly revision: RevisionReference;\n  readonly window: IslandResumeWindow;`,
    `  readonly revision: string;\n  readonly window: IslandResumeWindow;`],

  ["F4: application mount borrows the sink-policy identity", W('01_region'),
    "  readonly id: GroundingId<'liteship.web.grounding.application-mount'>;",
    "  readonly id: GroundingId<'liteship.web.grounding.sink-policy'>;"],
  ["F4: invocation mount borrows the sink-policy identity", W('01_region'),
    "  readonly id: GroundingId<'liteship.web.grounding.invocation-mount'>;",
    "  readonly id: GroundingId<'liteship.web.grounding.sink-policy'>;"],
  ["F4: renderer catalog borrows the sink-policy identity", W('04_projection'),
    "  readonly id: GroundingId<'liteship.web.grounding.renderer-catalog'>;",
    "  readonly id: GroundingId<'liteship.web.grounding.sink-policy'>;"],
  ["F4: event facility borrows the sink-policy identity", W('03_event'),
    "  readonly id: GroundingId<'liteship.web.grounding.event-facility'>;",
    "  readonly id: GroundingId<'liteship.web.grounding.sink-policy'>;"],
  ["F4: probe facility borrows the sink-policy identity", W('05_evidence'),
    "  readonly id: GroundingId<'liteship.web.grounding.probe-facility'>;",
    "  readonly id: GroundingId<'liteship.web.grounding.sink-policy'>;"],
  ["F4: database facility borrows the sink-policy identity", W('07_persistence'),
    "  readonly id: GroundingId<'liteship.web.grounding.database-facility'>;",
    "  readonly id: GroundingId<'liteship.web.grounding.sink-policy'>;"],
  ["F4: audio facility borrows the sink-policy identity", W('08_media'),
    "  readonly id: GroundingId<'liteship.web.grounding.audio-facility'>;",
    "  readonly id: GroundingId<'liteship.web.grounding.sink-policy'>;"],
  ["F4: injected audio runtime borrows the sink-policy identity", W('08_media'),
    "  readonly id: GroundingId<'liteship.web.grounding.injected-audio-runtime'>;",
    "  readonly id: GroundingId<'liteship.web.grounding.sink-policy'>;"],
  ["F4: gpu access borrows the sink-policy identity", W('09_graphics'),
    "  readonly id: GroundingId<'liteship.web.grounding.gpu-access'>;",
    "  readonly id: GroundingId<'liteship.web.grounding.sink-policy'>;"],
  ["F4: scheduling facility borrows the sink-policy identity", W('10_execution'),
    "  readonly id: GroundingId<'liteship.web.grounding.scheduling-facility'>;",
    "  readonly id: GroundingId<'liteship.web.grounding.sink-policy'>;"],
  ["F4: a grounding borrows an offer identity string", W('05_evidence'),
    "  readonly id: GroundingId<'liteship.web.grounding.probe-facility'>;",
    "  readonly id: GroundingId<'liteship.web.offer.store'>;"],
  ["F2: the region offer advertises the whole web placement", W('01_region'),
    "  readonly id: RealizationOfferId<'liteship.web.offer.region-authority'>;\n  readonly locations: NonEmptyTuple<'local' | 'live'>;\n  readonly backends: NonEmptyTuple<'javascript'>;\n}",
    "  readonly id: RealizationOfferId<'liteship.web.offer.region-authority'>;\n}"],
  ["F2: transport loses its remote placement pin", W('06_transport'),
    "  readonly locations: NonEmptyTuple<'remote'>;",
    "  readonly locations: NonEmptyTuple<'local' | 'live' | 'remote'>;"],
  ["F2: the sink-policy grounding loses its custody pin", W('02_security'),
    "  extends WebGroundingDefinition<readonly [SinkPolicyRequirement], WebSinkPolicy, 'deployment', 'unowned'> {",
    "  extends WebGroundingDefinition<readonly [SinkPolicyRequirement], WebSinkPolicy, 'deployment'> {"],
  ["F5: the watcher loses its update path", W('05_evidence'),
    "  readonly next: Signature<\n    WebProducerReference,\n    SourcedEvidenceUpdate<Source>,\n    NonEmptyTuple<Diagnostic>\n  >;\n",
    ""],
  ["F5: a watcher for source A emits source B", W('05_evidence'),
    "    WebProducerReference,\n    SourcedEvidenceUpdate<Source>,",
    "    WebProducerReference,\n    EvidenceUpdate,"],
  ["F5: the advertised source decorrelates from the parameter", W('05_evidence'),
    "  readonly produces: Source;\n  readonly next: Signature<",
    "  readonly produces: EvidenceSourceId;\n  readonly next: Signature<"],
  ["F5: the facility stands up an uncorrelated watcher", W('05_evidence'),
    "  ) => Result<WebWatcher<Source>, NonEmptyTuple<Diagnostic>>;",
    "  ) => Result<WebWatcher<EvidenceSourceId>, NonEmptyTuple<Diagnostic>>;"],
  ["F5: the plain watcher form accepts a source split", W('05_evidence'),
    "  readonly facility: ProbeFacilityGrounding;\n}",
    "  readonly facility: ProbeFacilityGrounding;\n}\n\nexport type TheBroadWatcherFormStaysIllegal = {\n  readonly id: WebProducerReference;\n  readonly produces: EvidenceSourceId<'liteship.evidence.mutant.source-a'>;\n  readonly next: Signature<\n    WebProducerReference,\n    SourcedEvidenceUpdate<EvidenceSourceId<'liteship.evidence.mutant.source-b'>>,\n    NonEmptyTuple<Diagnostic>\n  >;\n  readonly lifecycle: CaseOf<RealizationLifecycle, 'owned'>;\n} extends WebWatcher ? true : false;"],
  ["F6: transport opening decorrelates to the union", W('06_transport'),
    "export interface TransportAuthority {\n  readonly open: <Kind extends WebTransportKind, Decoded>(\n    request: CaseOf<TransportOpenRequest<Decoded>, Kind>,\n  ) => Result<CaseOf<WebConnection<Decoded>, Kind>, NonEmptyTuple<Diagnostic>>;\n}",
    "export interface TransportAuthority {\n  readonly open: Signature<TransportOpenRequest, WebConnection, NonEmptyTuple<Diagnostic>>;\n}"],
  ["F6: transport drops the network policy", W('06_transport'),
    "    readonly [TransportFacilityRequirement, SinkPolicyRequirement],\n    unknown,",
    "    readonly [TransportFacilityRequirement],\n    unknown,"],
  ["F8: the media provider loses its adoption path", W('08_media'),
    "  readonly adopt: Signature<WebMediaResource, WebMediaResource, NonEmptyTuple<Diagnostic>>;\n}",
    "}"],
  ["F8: the audio runtime constructs non-audio kinds", W('08_media'),
    "  readonly construct: Signature<\n    AudioResourceKind,",
    "  readonly construct: Signature<\n    WebMediaResourceKind,"],
  ["F8: the clock regrows a runtime claim", W('08_media'),
    "export interface SampleClock {\n  readonly read:",
    "export interface SampleClock {\n  readonly runtime: MediaResourceReference;\n  readonly read:"],
  ["F8: the clock reads arbitrary runtimes again", W('08_media'),
    "  readonly read: Signature<void, SampleClockTransport, NonEmptyTuple<Diagnostic>>;",
    "  readonly read: Signature<MediaResourceReference, SampleClockTransport, NonEmptyTuple<Diagnostic>>;"],
  ["F8: the instance splits its runtime from its clock", W('08_media'),
    "  readonly runtime: WebMediaResource<'owned', MediaResourceId, AudioResourceKind>;\n  readonly clock: SampleClock;",
    "  readonly runtime: WebMediaResource<'owned', MediaResourceId, AudioResourceKind>;\n  readonly clock: SampleClock & { readonly runtime: MediaResourceReference };"],
  ["F8: a foreign clock is assembled into the plain instance form", W('08_media'),
    "  readonly mediaOffer: MediaAuthorityOffer;\n}",
    "  readonly mediaOffer: MediaAuthorityOffer;\n}\n\nexport type TheAssembledForeignClockIsRefused = never;\ndeclare const mutantRuntime: WebMediaResource<'owned', MediaResourceId, AudioResourceKind>;\ndeclare const mutantForeignReference: MediaResourceReference;\ndeclare const mutantRead: SampleClock['read'];\nexport const mutantAssembledInstance: AudioRuntimeInstance = {\n  runtime: mutantRuntime,\n  clock: { runtime: mutantForeignReference, read: mutantRead },\n};"],
  ["F10: the execution request loses its transaction", RT,
    "  readonly baseRevision: RevisionReference;\n  readonly generation: TransactionGeneration;",
    "  readonly baseRevision: RevisionReference;"],
  ["F14: the runtime surface omits the executor", RT,
    "  readonly executionRequest: ExecutionRequest;\n  readonly executor: RuntimeExecutor;",
    "  readonly executionRequest: ExecutionRequest;"],
  ["F14: the stream surface omits the component catalog", ST,
    "  readonly catalogComponent: CatalogComponentDefinition;\n  readonly componentCatalog: ComponentCatalog;",
    "  readonly catalogComponent: CatalogComponentDefinition;"],
  ["F14: the compiler surface omits speculation", CM2,
    "  readonly speculativeCandidate: SpeculativeCandidate;\n  readonly preparedWork: PreparedWork;",
    "  readonly speculativeCandidate: SpeculativeCandidate;"],
  ["F12: the island forgets its selected resources", W('11_island'),
    "  readonly execution: RealizationInstanceReference;\n  readonly projection: RealizationInstanceReference;",
    "  readonly execution: RealizationInstanceReference;"],
  ["F1: the erased catalog vanishes from the topology", UM,
    "  readonly erased: RealizationCatalog;\n}",
    "}"],

  // --- umbrella ---
  ['TOPO: the topology reorders', UM,
    `  WebTypeHome<'00_bootstrap', WebBootstrapTypeSurface>,\n  WebTypeHome<'01_region', WebRegionTypeSurface>,`,
    `  WebTypeHome<'01_region', WebRegionTypeSurface>,\n  WebTypeHome<'00_bootstrap', WebBootstrapTypeSurface>,`],
  ['TOPO: security and event surfaces swap', UM,
    `  WebTypeHome<'02_security', WebSecurityTypeSurface>,\n  WebTypeHome<'03_event', WebEventTypeSurface>,`,
    `  WebTypeHome<'02_security', WebEventTypeSurface>,\n  WebTypeHome<'03_event', WebSecurityTypeSurface>,`],
  ['TOPO: media and graphics surfaces swap', UM,
    `  WebTypeHome<'08_media', WebMediaTypeSurface>,\n  WebTypeHome<'09_graphics', WebGraphicsTypeSurface>,`,
    `  WebTypeHome<'08_media', WebGraphicsTypeSurface>,\n  WebTypeHome<'09_graphics', WebMediaTypeSurface>,`],
  ['TOPO: a home vanishes from the tuple', UM,
    `  WebTypeHome<'10_execution', WebExecutionTypeSurface>,\n  WebTypeHome<'11_island', WebIslandTypeSurface>\n]>;`,
    `  WebTypeHome<'10_execution', WebExecutionTypeSurface>\n]>;`],
  ['TOPO: a thirteenth home is asserted in the roster only', UM,
    `  | '11_island';\n\n/** One owner and the semantic surface`,
    `  | '11_island'\n  | '12_imaginary';\n\n/** One owner and the semantic surface`],
  ['POPULATION: the renderer catalog vanishes from the groundings', UM,
    `    readonly rendererCatalog: RendererCatalogGrounding;\n    readonly eventFacility: EventFacilityGrounding;`,
    `    readonly eventFacility: EventFacilityGrounding;`],
  ['POPULATION: the preparation offer vanishes', UM,
    `    readonly preparation: PreparationOffer;\n    readonly islandActivation: IslandActivationOffer;`,
    `    readonly islandActivation: IslandActivationOffer;`],
  ['IDENTITY: an offer borrows another identity', UM,
    `      RealizationOfferId<'liteship.web.offer.transport-authority'>,`,
    `      RealizationOfferId<'liteship.web.offer.store'>,`],
  ["SURFACE: the media clock blurs to unknown", W('08_media'),
    "  readonly clock: SampleClockTransport;\n  readonly instance: AudioRuntimeInstance;",
    "  readonly clock: unknown;\n  readonly instance: AudioRuntimeInstance;"],
  ['SURFACE: the graphics loss relation blurs to unknown', W('09_graphics'),
    `  readonly loss: GraphicsLoss;\n  readonly egress: GraphicsEgress;\n  readonly authority: GraphicsAuthority;`,
    `  readonly loss: unknown;\n  readonly egress: GraphicsEgress;\n  readonly authority: GraphicsAuthority;`],
];

process.exit(runBank('web', M).clean ? 0 : 1);
