/**
 * `create-liteship/templates` and `examples` are the authored fragment owners;
 * the CLI's publishable tree is a byte-identical generated projection.
 *
 * @module
 */

import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';
import {
  CLI_FRAGMENT_ROOT,
  cliFragmentProjections,
  collectCliFragmentProjectionDrift,
} from '../../../scripts/gen-roster.js';

const REPO = resolve(import.meta.dirname, '..', '..', '..');

describe('CLI fragment projection', () => {
  it('is current byte-for-byte with every canonical tracked source', () => {
    expect(collectCliFragmentProjectionDrift()).toEqual([]);
    const projections = cliFragmentProjections();
    expect(projections.length).toBeGreaterThan(0);
    expect(projections).toEqual(
      expect.arrayContaining([
        {
          source: 'packages/create-liteship/templates/default/package.json',
          destination: `${CLI_FRAGMENT_ROOT}/template/default/package.json`,
        },
        {
          source: 'examples/07-stagger-reveal/stagger-preset.ts',
          destination: `${CLI_FRAGMENT_ROOT}/example/07-stagger-reveal/stagger-preset.ts`,
        },
      ]),
    );
  });

  it('detects stale, missing, and orphaned generated bytes without mutating the checkout', () => {
    const projections = cliFragmentProjections();
    const generated = new Map(
      projections.map((projection) => [
        projection.destination,
        new Uint8Array(readFileSync(resolve(REPO, projection.source))),
      ]),
    );
    const stale = projections[0]!;
    const missing = projections[1]!;
    generated.set(stale.destination, new TextEncoder().encode('stale'));
    generated.delete(missing.destination);
    generated.set(`${CLI_FRAGMENT_ROOT}/template/orphan.txt`, new TextEncoder().encode('orphan'));

    const drift = collectCliFragmentProjectionDrift((path) => generated.get(path), [...generated.keys()], projections);
    expect(drift).toEqual(
      expect.arrayContaining([
        expect.objectContaining({ copy: stale.destination, detail: expect.stringContaining('stale') }),
        expect.objectContaining({ copy: missing.destination, detail: expect.stringContaining('missing') }),
        expect.objectContaining({
          copy: `${CLI_FRAGMENT_ROOT}/template/orphan.txt`,
          detail: expect.stringContaining('orphaned'),
        }),
      ]),
    );
  });

  it('ships the projection and runs the canonical drift check before packing', () => {
    const manifest = JSON.parse(readFileSync(resolve(REPO, 'packages/cli/package.json'), 'utf8')) as {
      readonly files?: readonly string[];
      readonly scripts?: Readonly<Record<string, string>>;
    };
    expect(manifest.files).toContain('fragments');
    expect(manifest.scripts?.prepack).toContain('scripts/gen-roster.ts --check');
  });
});
