/**
 * `create-liteship/templates` and `examples` are the authored fragment owners;
 * the CLI's publishable tree is a byte-identical generated projection.
 *
 * @module
 */

import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { describe, expect, it } from 'vitest';
import {
  CLI_FRAGMENT_ROOT,
  cliFragmentProjections,
  collectCliFragmentProjectionDrift,
  renderCliFragmentProjection,
} from '../../../scripts/gen-roster.js';
import { DERIVED_ARTIFACTS } from '../../../scripts/lib/derived-artifacts.js';
import { W111_SUBJECT_FLOORS } from '../../../scripts/lib/tracked-subject-census.js';
import {
  assertCliFragmentProjectionWriterInput,
  collectCliFragmentProjectionAuthorityDrift,
  readCliFragmentProjectionAuthority,
  writeCliFragmentProjections,
} from '../../../scripts/gen-cli-fragments.js';

const REPO = resolve(import.meta.dirname, '..', '..', '..');
const FLEET_VERSION = (JSON.parse(readFileSync(resolve(REPO, 'package.json'), 'utf8')) as { readonly version: string })
  .version;

describe('CLI fragment projection', () => {
  it('is a dedicated L4 projection with one writer and one drift authority', () => {
    expect(DERIVED_ARTIFACTS.find((artifact) => artifact.id === 'cli-fragments')).toMatchObject({
      kind: 'projection',
      paths: [CLI_FRAGMENT_ROOT],
      regen: ['exec', 'tsx', 'scripts/gen-cli-fragments.ts', '--write'],
      enforcedBy: 'tests/unit/devops/cli-fragment-projection.test.ts',
      inPreflight: true,
    });
  });

  it('is current with every canonical tracked source and release-projects workspace manifests', () => {
    expect(collectCliFragmentProjectionDrift()).toEqual([]);
    const projections = cliFragmentProjections();
    expect(projections.length).toBeGreaterThan(0);
    expect(projections).toEqual(
      expect.arrayContaining([
        {
          source: 'packages/create-liteship/templates/default/package.json',
          destination: `${CLI_FRAGMENT_ROOT}/template/default/package.json`,
        },
        {
          source: 'examples/07-stagger-reveal/stagger-preset.ts',
          destination: `${CLI_FRAGMENT_ROOT}/example/07-stagger-reveal/stagger-preset.ts`,
        },
      ]),
    );
    const showcase = projections.find((projection) => projection.source === 'examples/showcase/package.json');
    expect(showcase).toBeDefined();
    const manifest = JSON.parse(new TextDecoder().decode(renderCliFragmentProjection(showcase!))) as {
      readonly dependencies: Readonly<Record<string, string>>;
    };
    expect(Object.values(manifest.dependencies)).not.toContain('workspace:*');
    expect(manifest.dependencies['@liteship/core']).toBe(FLEET_VERSION);
  });

  it('is an exact, non-vacuous projection of the tracked fragment census', async () => {
    const authority = await readCliFragmentProjectionAuthority(REPO);

    expect(collectCliFragmentProjectionAuthorityDrift(authority)).toEqual([]);
    expect(authority.subjects.fragments.length).toBeGreaterThanOrEqual(W111_SUBJECT_FLOORS.fragments);
    expect(authority.projections.length).toBeGreaterThanOrEqual(W111_SUBJECT_FLOORS.fragments);
    expect(authority.projections.map((projection) => projection.destination).sort()).toEqual(
      authority.subjects.fragments,
    );
  });

  it('the writer refuses an escaping plan before mutating its fragment tree', () => {
    const projections = cliFragmentProjections();
    expect(projections.length).toBeGreaterThanOrEqual(W111_SUBJECT_FLOORS.fragments);
    const scratch = mkdtempSync(join(tmpdir(), 'liteship-cli-fragment-writer-'));
    const sentinel = resolve(scratch, CLI_FRAGMENT_ROOT, 'sentinel.txt');
    mkdirSync(resolve(sentinel, '..'), { recursive: true });
    writeFileSync(sentinel, 'untouched');
    try {
      const escapingPlan = [
        ...projections.slice(1),
        { source: projections[0]!.source, destination: 'packages/cli/outside.txt' },
      ];
      expect(() => assertCliFragmentProjectionWriterInput(escapingPlan)).toThrow(/outside packages\/cli\/fragments/u);
      expect(() => writeCliFragmentProjections(escapingPlan, scratch)).toThrow(/outside packages\/cli\/fragments/u);
      expect(readFileSync(sentinel, 'utf8')).toBe('untouched');
    } finally {
      rmSync(scratch, { recursive: true, force: true });
    }
  });

  it('detects stale, missing, and orphaned generated bytes without mutating the checkout', () => {
    const projections = cliFragmentProjections();
    const generated = new Map(
      projections.map((projection) => [projection.destination, renderCliFragmentProjection(projection)]),
    );
    const stale = projections[0]!;
    const missing = projections[1]!;
    generated.set(stale.destination, new TextEncoder().encode('stale'));
    generated.delete(missing.destination);
    generated.set(`${CLI_FRAGMENT_ROOT}/template/orphan.txt`, new TextEncoder().encode('orphan'));

    const drift = collectCliFragmentProjectionDrift((path) => generated.get(path), [...generated.keys()], projections);
    expect(drift).toEqual(
      expect.arrayContaining([
        expect.objectContaining({ copy: stale.destination, detail: expect.stringContaining('stale') }),
        expect.objectContaining({ copy: missing.destination, detail: expect.stringContaining('missing') }),
        expect.objectContaining({
          copy: `${CLI_FRAGMENT_ROOT}/template/orphan.txt`,
          detail: expect.stringContaining('orphaned'),
        }),
      ]),
    );
  });

  it('ships the projection and runs the canonical drift check before packing', () => {
    const manifest = JSON.parse(readFileSync(resolve(REPO, 'packages/cli/package.json'), 'utf8')) as {
      readonly files?: readonly string[];
      readonly scripts?: Readonly<Record<string, string>>;
    };
    expect(manifest.files).toContain('fragments');
    expect(manifest.scripts?.prepack).toContain('scripts/gen-roster.ts --check');
    expect(manifest.scripts?.prepack).toContain('scripts/gen-cli-fragments.ts --check');
  });
});
