/** GENERATED by scripts/gen-event-protocol.ts from owner-local protocol declarations. */
/** Package that owns an event identity and its semantic payload contract. */
export type LiteShipEventOwner = "astro" | "detect" | "scene" | "vite" | "web";
/** Transport channel on which a fleet event is delivered. */
export type LiteShipEventChannel = "dom" | "vite-hmr";
/** One event protocol row carrying provenance, transport, and detail. */
export interface ProtocolEvent<Owner extends LiteShipEventOwner, Channel extends LiteShipEventChannel, Detail> { readonly owner: Owner; readonly channel: Channel; readonly detail: Detail }
/** Generated fleet-wide event identity map. Owner catalogs are its only authored source. */
export interface LiteShipEventMap {
  "liteship:adaptive-state": ProtocolEvent<"astro", "dom", {
  readonly discrete?: Readonly<Record<string, string>>;
  readonly css?: Readonly<Record<string, string | number>>;
  readonly glsl?: Readonly<Record<string, number>>;
  readonly wgsl?: Readonly<Record<string, unknown>>;
  readonly aria?: Readonly<Record<string, string>>;
  readonly state?: string;
}>;
  "liteship:detect-ready": ProtocolEvent<"detect", "dom", import("./detect.js").DetectReadyDetail>;
  "liteship:gpu-ready": ProtocolEvent<"astro", "dom", undefined>;
  "liteship:graph-state": ProtocolEvent<"astro", "dom", {
  readonly discrete?: Readonly<Record<string, string>>;
  readonly css?: Readonly<Record<string, string | number>>;
  readonly glsl?: Readonly<Record<string, number>>;
  readonly wgsl?: Readonly<Record<string, unknown>>;
  readonly aria?: Readonly<Record<string, string>>;
  readonly state?: string;
}>;
  "liteship:llm-done": ProtocolEvent<"astro", "dom", { readonly accumulated: string }>;
  "liteship:llm-error": ProtocolEvent<"astro", "dom", { readonly message: string } | { readonly reason: string; readonly strategy: string }>;
  "liteship:llm-frame": ProtocolEvent<"astro", "dom", import("./core.js").UIFrame>;
  "liteship:llm-genui": ProtocolEvent<"astro", "dom", { readonly node: import("./genui.js").GeneratedUINode; readonly renderHash: string }>;
  "liteship:llm-start": ProtocolEvent<"astro", "dom", undefined>;
  "liteship:llm-token": ProtocolEvent<"astro", "dom", { readonly text: string; readonly accumulated: string }>;
  "liteship:llm-tool-end": ProtocolEvent<"astro", "dom", { readonly name: string; readonly args: unknown }>;
  "liteship:llm-tool-start": ProtocolEvent<"astro", "dom", { readonly name: string }>;
  "liteship:morph-rejected": ProtocolEvent<"web", "dom", import("./web.js").MorphRejection & { readonly recovery?: string }>;
  "liteship:mutation": ProtocolEvent<"web", "dom", import("./core.js").GraphMutationResponse>;
  "liteship:reinit": ProtocolEvent<"astro", "dom", undefined>;
  "liteship:request-snapshot": ProtocolEvent<"web", "dom", { readonly reason: string; readonly domStale?: boolean }>;
  "liteship:scene-update": ProtocolEvent<"scene", "vite-hmr", { readonly sceneId: string }>;
  "liteship:signal": ProtocolEvent<"astro", "dom", unknown>;
  "liteship:slot-mounted": ProtocolEvent<"web", "dom", {
      readonly path: import("./web.js").SlotPath;
      readonly mode: import("./web.js").IslandMode;
    }>;
  "liteship:slot-unmounted": ProtocolEvent<"web", "dom", {
      readonly path: import("./web.js").SlotPath;
      readonly mode?: import("./web.js").IslandMode;
    }>;
  "liteship:state": ProtocolEvent<"astro", "dom", {
  readonly discrete?: Readonly<Record<string, string>>;
  readonly css?: Readonly<Record<string, string | number>>;
  readonly glsl?: Readonly<Record<string, number>>;
  readonly wgsl?: Readonly<Record<string, unknown>>;
  readonly aria?: Readonly<Record<string, string>>;
  readonly state?: string;
}>;
  "liteship:stream-connected": ProtocolEvent<"astro", "dom", undefined>;
  "liteship:stream-disconnected": ProtocolEvent<"astro", "dom", undefined>;
  "liteship:stream-error": ProtocolEvent<"web", "dom", { readonly reason: string; readonly message?: string }>;
  "liteship:stream-morph": ProtocolEvent<"astro", "dom", undefined>;
  "liteship:teardown": ProtocolEvent<"astro", "dom", undefined>;
  "liteship:uniform-update": ProtocolEvent<"web", "dom", {
      readonly discrete?: Readonly<Record<string, string>>;
      readonly css?: Readonly<Record<string, string | number>>;
      readonly glsl?: Readonly<Record<string, number>>;
      readonly wgsl?: Readonly<Record<string, unknown>>;
      readonly aria?: Readonly<Record<string, string>>;
      readonly state?: string;
    }>;
  "liteship:update": ProtocolEvent<"vite", "vite-hmr", import("./vite.js").HMRPayload>;
  "liteship:wasm-error": ProtocolEvent<"astro", "dom", { readonly url: string; readonly reason: string }>;
  "liteship:wasm-ready": ProtocolEvent<"astro", "dom", { readonly url: string }>;
  "liteship:worker-ready": ProtocolEvent<"astro", "dom", undefined>;
  "liteship:worker-state": ProtocolEvent<"astro", "dom", {
  readonly discrete?: Readonly<Record<string, string>>;
  readonly css?: Readonly<Record<string, string | number>>;
  readonly glsl?: Readonly<Record<string, number>>;
  readonly wgsl?: Readonly<Record<string, unknown>>;
  readonly aria?: Readonly<Record<string, string>>;
  readonly state?: string;
}>;
}
/** Every event identity admitted by the generated fleet protocol. */
export type LiteShipEventName = keyof LiteShipEventMap;
/** Payload detail for one admitted event identity. */
export type EventDetail<Name extends LiteShipEventName> = LiteShipEventMap[Name]['detail'];
/** Event identities owned by one semantic package owner. */
export type EventsOwnedBy<Owner extends LiteShipEventOwner> = { [Name in LiteShipEventName]: LiteShipEventMap[Name]['owner'] extends Owner ? Name : never }[LiteShipEventName];
/** Event identities delivered through one transport channel. */
export type EventsInChannel<Channel extends LiteShipEventChannel> = { [Name in LiteShipEventName]: LiteShipEventMap[Name]['channel'] extends Channel ? Name : never }[LiteShipEventName];
