/** @generated by scripts/gen-roster.ts from scripts/package-catalog.ts; do not hand-edit. */
// prettier-ignore
export const GENERATED_DOC_PACKAGE_GROUPS = {
  "foundations": ["@liteship/core", "@liteship/canonical", "@liteship/error", "@liteship/genui", "@liteship/quantizer", "@liteship/compiler"],
  "hosts": ["@liteship/vite", "@liteship/astro", "@liteship/edge", "@liteship/cloudflare"],
  "runtime": ["@liteship/web", "@liteship/detect", "@liteship/worker", "@liteship/remotion", "@liteship/scene", "@liteship/assets", "@liteship/stage", "@liteship/cli", "@liteship/mcp-server", "@liteship/_spine"],
  "tooling": ["@liteship/command", "@liteship/audit", "@liteship/gauntlet"],
} as const;
export const GENERATED_PROSE_ONLY = ["liteship", "create-liteship"] as const;
export const GENERATED_NO_SURFACE_SECTION = ["@liteship/_spine"] as const;
