/** @generated by scripts/gen-public-surface-context.ts from packages/liteship/src/export-budget.ts; do not hand-edit. */
// prettier-ignore
export const GENERATED_PUBLIC_SURFACE_CONTEXT = {
  "root": [
    {
      "kind": "root",
      "symbol": "defineConfig",
      "specifier": "liteship",
      "owner": "@liteship/core/authoring",
      "audience": "application-author",
      "category": "authoring",
      "surfaceClass": "paved-road",
      "producer": "@liteship/core",
      "relatedInvariant": "INV-FACADE-EXPORT-BUDGET",
      "replacement": "none",
      "userStory": "Define the one immutable project configuration consumed by host integrations.",
      "lifecycle": "immutable-definition",
      "failureContract": "Invalid configuration is rejected before host projection.",
      "failureProof": null,
      "example": "defineConfig(input)",
      "stability": "stable",
      "expertRoutes": [
        "liteship/reactive",
        "liteship/compiler"
      ],
      "checkIds": [
        "check/test",
        "check/hermetic",
        "check/test-vite",
        "check/test-astro"
      ],
      "proofRefs": [
        "tests/unit/liteship/facade-inhabitation.test.ts",
        "tests/unit/liteship/facade-subpaths.test.ts",
        "tests/unit/liteship/root-failure-contract.test.ts"
      ],
      "remediation": "Correct the input at @liteship/core/authoring, retry defineConfig(input), then run check/test and check/hermetic and check/test-vite and check/test-astro."
    },
    {
      "kind": "root",
      "symbol": "defineBoundary",
      "specifier": "liteship",
      "owner": "@liteship/core/authoring",
      "audience": "application-author",
      "category": "authoring",
      "surfaceClass": "paved-road",
      "producer": "@liteship/core",
      "relatedInvariant": "INV-FACADE-EXPORT-BUDGET",
      "replacement": "none",
      "userStory": "Partition a continuous input into named application states.",
      "lifecycle": "immutable-definition",
      "failureContract": "Invalid thresholds or states are rejected at definition time.",
      "failureProof": null,
      "example": "defineBoundary(input)",
      "stability": "stable",
      "expertRoutes": [
        "liteship/reactive",
        "liteship/compiler"
      ],
      "checkIds": [
        "check/test",
        "check/hermetic"
      ],
      "proofRefs": [
        "tests/unit/liteship/facade-inhabitation.test.ts",
        "tests/unit/liteship/facade-subpaths.test.ts",
        "tests/unit/liteship/root-failure-contract.test.ts"
      ],
      "remediation": "Correct the input at @liteship/core/authoring, retry defineBoundary(input), then run check/test and check/hermetic."
    },
    {
      "kind": "root",
      "symbol": "defineQuantizer",
      "specifier": "liteship",
      "owner": "@liteship/quantizer",
      "audience": "application-author",
      "category": "authoring",
      "surfaceClass": "paved-road",
      "producer": "@liteship/quantizer",
      "relatedInvariant": "INV-FACADE-EXPORT-BUDGET",
      "replacement": "none",
      "userStory": "Attach target outputs to a boundary without starting a runtime.",
      "lifecycle": "immutable-definition",
      "failureContract": "Incomplete or invalid output maps are rejected before runtime allocation.",
      "failureProof": null,
      "example": "defineQuantizer(boundary, options)",
      "stability": "stable",
      "expertRoutes": [
        "liteship/reactive",
        "liteship/compiler"
      ],
      "checkIds": [
        "check/test",
        "check/hermetic"
      ],
      "proofRefs": [
        "tests/unit/liteship/facade-inhabitation.test.ts",
        "tests/unit/liteship/facade-subpaths.test.ts"
      ],
      "remediation": "Correct the input at @liteship/quantizer, retry defineQuantizer(boundary, options), then run check/test and check/hermetic."
    },
    {
      "kind": "root",
      "symbol": "defineToken",
      "specifier": "liteship",
      "owner": "@liteship/core/authoring",
      "audience": "application-author",
      "category": "authoring",
      "surfaceClass": "paved-road",
      "producer": "@liteship/core",
      "relatedInvariant": "INV-FACADE-EXPORT-BUDGET",
      "replacement": "none",
      "userStory": "Define one content-addressed design token.",
      "lifecycle": "immutable-definition",
      "failureContract": "Invalid token identity or values are rejected at definition time.",
      "failureProof": null,
      "example": "defineToken(input)",
      "stability": "stable",
      "expertRoutes": [
        "liteship/reactive",
        "liteship/compiler"
      ],
      "checkIds": [
        "check/test",
        "check/hermetic"
      ],
      "proofRefs": [
        "tests/unit/liteship/facade-inhabitation.test.ts",
        "tests/unit/liteship/facade-subpaths.test.ts"
      ],
      "remediation": "Correct the input at @liteship/core/authoring, retry defineToken(input), then run check/test and check/hermetic."
    },
    {
      "kind": "root",
      "symbol": "defineTheme",
      "specifier": "liteship",
      "owner": "@liteship/core/authoring",
      "audience": "application-author",
      "category": "authoring",
      "surfaceClass": "paved-road",
      "producer": "@liteship/core",
      "relatedInvariant": "INV-FACADE-EXPORT-BUDGET",
      "replacement": "none",
      "userStory": "Define named token variants as one immutable theme.",
      "lifecycle": "immutable-definition",
      "failureContract": "Invalid variants or token references are rejected at definition time.",
      "failureProof": null,
      "example": "defineTheme(input)",
      "stability": "stable",
      "expertRoutes": [
        "liteship/reactive",
        "liteship/compiler"
      ],
      "checkIds": [
        "check/test",
        "check/hermetic"
      ],
      "proofRefs": [
        "tests/unit/liteship/facade-inhabitation.test.ts",
        "tests/unit/liteship/facade-subpaths.test.ts"
      ],
      "remediation": "Correct the input at @liteship/core/authoring, retry defineTheme(input), then run check/test and check/hermetic."
    },
    {
      "kind": "root",
      "symbol": "defineStyle",
      "specifier": "liteship",
      "owner": "@liteship/core/authoring",
      "audience": "application-author",
      "category": "authoring",
      "surfaceClass": "paved-road",
      "producer": "@liteship/core",
      "relatedInvariant": "INV-FACADE-EXPORT-BUDGET",
      "replacement": "none",
      "userStory": "Define base and state-layer declarations against one boundary.",
      "lifecycle": "immutable-definition",
      "failureContract": "Invalid declarations or state ownership are rejected at definition time.",
      "failureProof": null,
      "example": "defineStyle(input)",
      "stability": "stable",
      "expertRoutes": [
        "liteship/reactive",
        "liteship/compiler"
      ],
      "checkIds": [
        "check/test",
        "check/hermetic"
      ],
      "proofRefs": [
        "tests/unit/liteship/facade-inhabitation.test.ts",
        "tests/unit/liteship/facade-subpaths.test.ts",
        "tests/unit/liteship/root-failure-contract.test.ts"
      ],
      "remediation": "Correct the input at @liteship/core/authoring, retry defineStyle(input), then run check/test and check/hermetic."
    },
    {
      "kind": "root",
      "symbol": "defineAdaptive",
      "specifier": "liteship",
      "owner": "liteship",
      "audience": "application-author",
      "category": "authoring",
      "surfaceClass": "paved-road",
      "producer": "./adaptive.js",
      "relatedInvariant": "INV-FACADE-EXPORT-BUDGET",
      "replacement": "none",
      "userStory": "Define adaptive behavior, apply its attributes, inspect state, and emit its compiled plan.",
      "lifecycle": "immutable-definition",
      "failureContract": "Lowering rejects invalid definitions and explanation follows the live quantizer contract.",
      "failureProof": null,
      "example": "defineAdaptive(spec)",
      "stability": "stable",
      "expertRoutes": [
        "liteship/reactive",
        "liteship/motion",
        "liteship/compiler",
        "liteship/astro",
        "liteship/vite"
      ],
      "checkIds": [
        "check/test",
        "check/hermetic",
        "check/journey",
        "check/test-e2e"
      ],
      "proofRefs": [
        "tests/unit/liteship/facade-inhabitation.test.ts",
        "tests/unit/liteship/facade-subpaths.test.ts",
        "tests/unit/liteship/root-failure-contract.test.ts",
        "tests/property/adaptive-lowering-equivalence.prop.test.ts",
        "tests/e2e/astro-directives.e2e.ts"
      ],
      "remediation": "Correct the input at liteship, retry defineAdaptive(spec), then run check/test and check/hermetic and check/journey and check/test-e2e."
    },
    {
      "kind": "root",
      "symbol": "schema",
      "specifier": "liteship",
      "owner": "@liteship/core/schema",
      "audience": "application-author",
      "category": "authoring",
      "surfaceClass": "paved-road",
      "producer": "@liteship/core",
      "relatedInvariant": "INV-FACADE-EXPORT-BUDGET",
      "replacement": "none",
      "userStory": "Describe and decode typed data at a semantic boundary.",
      "lifecycle": "immutable-definition",
      "failureContract": "Decode returns structured issues instead of accepting malformed data.",
      "failureProof": null,
      "example": "schema.struct(fields)",
      "stability": "stable",
      "expertRoutes": [
        "liteship/schema"
      ],
      "checkIds": [
        "check/test",
        "check/hermetic"
      ],
      "proofRefs": [
        "tests/unit/liteship/facade-inhabitation.test.ts",
        "tests/unit/liteship/facade-subpaths.test.ts"
      ],
      "remediation": "Correct the input at @liteship/core/schema, retry schema.struct(fields), then run check/test and check/hermetic."
    },
    {
      "kind": "root",
      "symbol": "explainDiagnostic",
      "specifier": "liteship",
      "owner": "@liteship/error",
      "audience": "operator",
      "category": "inspection",
      "surfaceClass": "paved-road",
      "producer": "@liteship/error",
      "relatedInvariant": "INV-FACADE-EXPORT-BUDGET",
      "replacement": "none",
      "userStory": "Turn a stable diagnostic code into meaning and remediation.",
      "lifecycle": "pure-reader",
      "failureContract": "Unknown codes return no invented explanation.",
      "failureProof": null,
      "example": "explainDiagnostic(code)",
      "stability": "stable",
      "expertRoutes": [
        "liteship/evidence"
      ],
      "checkIds": [
        "check/test",
        "check/hermetic"
      ],
      "proofRefs": [
        "tests/unit/liteship/facade-inhabitation.test.ts",
        "tests/unit/liteship/facade-subpaths.test.ts"
      ],
      "remediation": "Correct the input at @liteship/error, retry explainDiagnostic(code), then run check/test and check/hermetic."
    },
    {
      "kind": "root",
      "symbol": "Config",
      "specifier": "liteship",
      "owner": "@liteship/core/authoring",
      "audience": "application-author",
      "category": "authoring",
      "surfaceClass": "paved-road",
      "producer": "@liteship/core",
      "relatedInvariant": "INV-FACADE-EXPORT-BUDGET",
      "replacement": "none",
      "userStory": "Annotate an authored project configuration.",
      "lifecycle": "compile-time-only",
      "failureContract": "Type checking rejects incompatible configuration shapes.",
      "failureProof": null,
      "example": "Config",
      "stability": "stable",
      "expertRoutes": [
        "liteship/reactive",
        "liteship/compiler"
      ],
      "checkIds": [
        "check/typecheck",
        "check/hermetic",
        "check/test-vite",
        "check/test-astro"
      ],
      "proofRefs": [
        "tests/unit/liteship/facade-subpaths.test.ts",
        "tests/unit/meta/api-surface.test.ts"
      ],
      "remediation": "Correct the input at @liteship/core/authoring, retry Config, then run check/typecheck and check/hermetic and check/test-vite and check/test-astro."
    },
    {
      "kind": "root",
      "symbol": "Boundary",
      "specifier": "liteship",
      "owner": "@liteship/core/authoring",
      "audience": "application-author",
      "category": "authoring",
      "surfaceClass": "paved-road",
      "producer": "@liteship/core",
      "relatedInvariant": "INV-FACADE-EXPORT-BUDGET",
      "replacement": "none",
      "userStory": "Annotate a named-state boundary definition.",
      "lifecycle": "compile-time-only",
      "failureContract": "Type checking preserves the input and state vocabulary.",
      "failureProof": null,
      "example": "Boundary<'viewport.width', readonly ['mobile', 'desktop']>",
      "stability": "stable",
      "expertRoutes": [
        "liteship/reactive",
        "liteship/compiler"
      ],
      "checkIds": [
        "check/typecheck",
        "check/hermetic"
      ],
      "proofRefs": [
        "tests/unit/liteship/facade-subpaths.test.ts",
        "tests/unit/meta/api-surface.test.ts"
      ],
      "remediation": "Correct the input at @liteship/core/authoring, retry Boundary<'viewport.width', readonly ['mobile', 'desktop']>, then run check/typecheck and check/hermetic."
    },
    {
      "kind": "root",
      "symbol": "Quantizer",
      "specifier": "liteship",
      "owner": "@liteship/core/schema",
      "audience": "application-author",
      "category": "authoring",
      "surfaceClass": "paved-road",
      "producer": "@liteship/core",
      "relatedInvariant": "INV-FACADE-EXPORT-BUDGET",
      "replacement": "none",
      "userStory": "Annotate the structural mapping from boundary states to outputs.",
      "lifecycle": "compile-time-only",
      "failureContract": "Type checking rejects state or output mismatches.",
      "failureProof": null,
      "example": "Quantizer<Boundary>",
      "stability": "stable",
      "expertRoutes": [
        "liteship/schema"
      ],
      "checkIds": [
        "check/typecheck",
        "check/hermetic"
      ],
      "proofRefs": [
        "tests/unit/liteship/facade-subpaths.test.ts",
        "tests/unit/meta/api-surface.test.ts"
      ],
      "remediation": "Correct the input at @liteship/core/schema, retry Quantizer<Boundary>, then run check/typecheck and check/hermetic."
    },
    {
      "kind": "root",
      "symbol": "Token",
      "specifier": "liteship",
      "owner": "@liteship/core/authoring",
      "audience": "application-author",
      "category": "authoring",
      "surfaceClass": "paved-road",
      "producer": "@liteship/core",
      "relatedInvariant": "INV-FACADE-EXPORT-BUDGET",
      "replacement": "none",
      "userStory": "Annotate a content-addressed token definition.",
      "lifecycle": "compile-time-only",
      "failureContract": "Type checking preserves the token value contract.",
      "failureProof": null,
      "example": "Token<'brand-accent'>",
      "stability": "stable",
      "expertRoutes": [
        "liteship/reactive",
        "liteship/compiler"
      ],
      "checkIds": [
        "check/typecheck",
        "check/hermetic"
      ],
      "proofRefs": [
        "tests/unit/liteship/facade-subpaths.test.ts",
        "tests/unit/meta/api-surface.test.ts"
      ],
      "remediation": "Correct the input at @liteship/core/authoring, retry Token<'brand-accent'>, then run check/typecheck and check/hermetic."
    },
    {
      "kind": "root",
      "symbol": "Theme",
      "specifier": "liteship",
      "owner": "@liteship/core/authoring",
      "audience": "application-author",
      "category": "authoring",
      "surfaceClass": "paved-road",
      "producer": "@liteship/core",
      "relatedInvariant": "INV-FACADE-EXPORT-BUDGET",
      "replacement": "none",
      "userStory": "Annotate named token variants.",
      "lifecycle": "compile-time-only",
      "failureContract": "Type checking preserves variant names and token values.",
      "failureProof": null,
      "example": "Theme<readonly ['default', 'dark']>",
      "stability": "stable",
      "expertRoutes": [
        "liteship/reactive",
        "liteship/compiler"
      ],
      "checkIds": [
        "check/typecheck",
        "check/hermetic"
      ],
      "proofRefs": [
        "tests/unit/liteship/facade-subpaths.test.ts",
        "tests/unit/meta/api-surface.test.ts"
      ],
      "remediation": "Correct the input at @liteship/core/authoring, retry Theme<readonly ['default', 'dark']>, then run check/typecheck and check/hermetic."
    },
    {
      "kind": "root",
      "symbol": "Style",
      "specifier": "liteship",
      "owner": "@liteship/core/authoring",
      "audience": "application-author",
      "category": "authoring",
      "surfaceClass": "paved-road",
      "producer": "@liteship/core",
      "relatedInvariant": "INV-FACADE-EXPORT-BUDGET",
      "replacement": "none",
      "userStory": "Annotate state-aware style declarations.",
      "lifecycle": "compile-time-only",
      "failureContract": "Type checking binds style states to the boundary vocabulary.",
      "failureProof": null,
      "example": "Style<Boundary>",
      "stability": "stable",
      "expertRoutes": [
        "liteship/reactive",
        "liteship/compiler"
      ],
      "checkIds": [
        "check/typecheck",
        "check/hermetic"
      ],
      "proofRefs": [
        "tests/unit/liteship/facade-subpaths.test.ts",
        "tests/unit/meta/api-surface.test.ts"
      ],
      "remediation": "Correct the input at @liteship/core/authoring, retry Style<Boundary>, then run check/typecheck and check/hermetic."
    },
    {
      "kind": "root",
      "symbol": "Adaptive",
      "specifier": "liteship",
      "owner": "@liteship/core",
      "audience": "application-author",
      "category": "authoring",
      "surfaceClass": "paved-road",
      "producer": "@liteship/core",
      "relatedInvariant": "INV-FACADE-EXPORT-BUDGET",
      "replacement": "none",
      "userStory": "Annotate the flagship define, apply, and inspect aggregate.",
      "lifecycle": "compile-time-only",
      "failureContract": "Type checking keeps attrs, explanation, and plan outputs coherent.",
      "failureProof": null,
      "example": "Adaptive",
      "stability": "stable",
      "expertRoutes": [],
      "checkIds": [
        "check/typecheck",
        "check/hermetic",
        "check/journey",
        "check/test-e2e"
      ],
      "proofRefs": [
        "tests/unit/liteship/facade-subpaths.test.ts",
        "tests/unit/meta/api-surface.test.ts",
        "tests/property/adaptive-lowering-equivalence.prop.test.ts",
        "tests/e2e/astro-directives.e2e.ts"
      ],
      "remediation": "Correct the input at @liteship/core, retry Adaptive, then run check/typecheck and check/hermetic and check/journey and check/test-e2e."
    },
    {
      "kind": "root",
      "symbol": "DiagnosticCode",
      "specifier": "liteship",
      "owner": "@liteship/error",
      "audience": "operator",
      "category": "inspection",
      "surfaceClass": "paved-road",
      "producer": "@liteship/error",
      "relatedInvariant": "INV-FACADE-EXPORT-BUDGET",
      "replacement": "none",
      "userStory": "Annotate a stable code accepted by diagnostic inspection.",
      "lifecycle": "compile-time-only",
      "failureContract": "Type checking rejects unknown diagnostic identifiers.",
      "failureProof": null,
      "example": "DiagnosticCode",
      "stability": "stable",
      "expertRoutes": [
        "liteship/evidence"
      ],
      "checkIds": [
        "check/typecheck",
        "check/hermetic"
      ],
      "proofRefs": [
        "tests/unit/liteship/facade-subpaths.test.ts",
        "tests/unit/meta/api-surface.test.ts"
      ],
      "remediation": "Correct the input at @liteship/error, retry DiagnosticCode, then run check/typecheck and check/hermetic."
    }
  ],
  "subpaths": [
    {
      "kind": "subpath",
      "symbol": "schema",
      "specifier": "liteship/schema",
      "owner": "@liteship/core/schema",
      "audience": "application-author",
      "category": "schema",
      "surfaceClass": "advanced-module",
      "producer": "@liteship/core/schema",
      "relatedInvariant": "INV-CONSUMER-SUBPATH-CLOSURE",
      "replacement": "none",
      "role": "schema",
      "userStory": "Define, decode, and project transport-agnostic schemas.",
      "lifecycle": "immutable definitions and pure decoders",
      "failureContract": "Malformed data returns structured decode issues.",
      "failureProof": null,
      "example": "schema.struct(fields)",
      "stability": "stable",
      "dependencyCost": "pure core schema kernel",
      "packedProof": "check/hermetic:runtime-import+node16+bundler",
      "reason": "Schema authoring is a coherent expert domain beyond the first adaptive feature.",
      "expertRoutes": [
        "liteship/schema"
      ],
      "checkIds": [
        "check/hermetic",
        "check/test"
      ],
      "proofRefs": [
        "tests/unit/liteship/facade-subpaths.test.ts"
      ],
      "remediation": "Correct the input at @liteship/core/schema, retry schema.struct(fields), then run check/hermetic and check/test."
    },
    {
      "kind": "subpath",
      "symbol": "createCell",
      "specifier": "liteship/reactive",
      "owner": "@liteship/core/reactive",
      "audience": "application-author",
      "category": "reactive-runtime",
      "surfaceClass": "advanced-module",
      "producer": "@liteship/core/reactive",
      "relatedInvariant": "INV-CONSUMER-SUBPATH-CLOSURE",
      "replacement": "none",
      "role": "reactive-runtime",
      "userStory": "Allocate and dispose cells, signals, stores, lifetimes, and live quantizers.",
      "lifecycle": "owned resources require disposal",
      "failureContract": "Disposed resources stop work and invalid state transitions fail loudly.",
      "failureProof": null,
      "example": "createCell(initial)",
      "stability": "stable",
      "dependencyCost": "stateful core and quantizer runtime",
      "packedProof": "check/hermetic:runtime-import+node16+bundler",
      "reason": "Runtime allocation is intentionally distinct from immutable root authoring.",
      "expertRoutes": [
        "liteship/reactive"
      ],
      "checkIds": [
        "check/hermetic",
        "check/test"
      ],
      "proofRefs": [
        "tests/unit/liteship/facade-subpaths.test.ts",
        "tests/unit/core/reactive/runtime-coordinator.test.ts",
        "tests/unit/core/reactive/state-cell.test.ts",
        "tests/unit/core/reactive/cell.test.ts",
        "tests/unit/core/reactive/dirty-flags-runtime.test.ts",
        "tests/unit/core/reactive/lifetime.test.ts",
        "tests/unit/core/reactive/disposed-write-inert.test.ts",
        "tests/unit/quantizer/animated-quantizer.test.ts",
        "tests/unit/core/reactive/signal.test.ts",
        "tests/unit/core/reactive/store.test.ts"
      ],
      "remediation": "Correct the input at @liteship/core/reactive, retry createCell(initial), then run check/hermetic and check/test."
    },
    {
      "kind": "subpath",
      "symbol": "createTimeline",
      "specifier": "liteship/motion",
      "owner": "@liteship/core/motion",
      "audience": "application-author",
      "category": "motion",
      "surfaceClass": "advanced-module",
      "producer": "@liteship/core/motion",
      "relatedInvariant": "INV-CONSUMER-SUBPATH-CLOSURE",
      "replacement": "none",
      "role": "motion",
      "userStory": "Define and execute transitions, timelines, easing, reveal, and stagger behavior.",
      "lifecycle": "timeline resources require disposal",
      "failureContract": "Unsupported or invalid motion intent is refused before execution.",
      "failureProof": null,
      "example": "createTimeline(boundary, options)",
      "stability": "stable",
      "dependencyCost": "motion kernels",
      "packedProof": "check/hermetic:runtime-import+node16+bundler",
      "reason": "Motion is an expert capability with its own lifecycle and vocabulary.",
      "expertRoutes": [
        "liteship/motion"
      ],
      "checkIds": [
        "check/hermetic",
        "check/test"
      ],
      "proofRefs": [
        "tests/unit/liteship/facade-subpaths.test.ts",
        "tests/unit/core/motion/blend-tree.test.ts",
        "tests/unit/liteship/facade-lifecycle-contract.test.ts"
      ],
      "remediation": "Correct the input at @liteship/core/motion, retry createTimeline(boundary, options), then run check/hermetic and check/test."
    },
    {
      "kind": "subpath",
      "symbol": "DAG",
      "specifier": "liteship/graph",
      "owner": "@liteship/core/graph",
      "audience": "application-author",
      "category": "document-graph",
      "surfaceClass": "advanced-module",
      "producer": "@liteship/core/graph",
      "relatedInvariant": "INV-CONSUMER-SUBPATH-CLOSURE",
      "replacement": "none",
      "role": "document-graph",
      "userStory": "Seal, validate, patch, query, and replay the document graph.",
      "lifecycle": "immutable sealed graphs plus explicit clients",
      "failureContract": "Invalid nodes, patches, or receipts are rejected before application.",
      "failureProof": null,
      "example": "DAG.empty()",
      "stability": "stable",
      "dependencyCost": "graph and evidence kernels",
      "packedProof": "check/hermetic:runtime-import+node16+bundler",
      "reason": "Graph mutation is an advanced engine workflow, not first-hour authoring.",
      "expertRoutes": [
        "liteship/graph"
      ],
      "checkIds": [
        "check/hermetic",
        "check/test"
      ],
      "proofRefs": [
        "tests/unit/liteship/facade-subpaths.test.ts",
        "tests/unit/core/graph/graph-mutation-client.test.ts",
        "tests/unit/core/graph/graph-query.test.ts"
      ],
      "remediation": "Correct the input at @liteship/core/graph, retry DAG.empty(), then run check/hermetic and check/test."
    },
    {
      "kind": "subpath",
      "symbol": "Compositor",
      "specifier": "liteship/media",
      "owner": "@liteship/core/media",
      "audience": "application-author",
      "category": "media-runtime",
      "surfaceClass": "advanced-module",
      "producer": "@liteship/core/media",
      "relatedInvariant": "INV-CONSUMER-SUBPATH-CLOSURE",
      "replacement": "none",
      "role": "media-runtime",
      "userStory": "Resolve responsive media and run compositor, audio, video, and frame-budget paths.",
      "lifecycle": "owned buffers and renderers require disposal",
      "failureContract": "Invalid media inputs and exhausted budgets are surfaced explicitly.",
      "failureProof": null,
      "example": "Compositor.create(options)",
      "stability": "stable",
      "dependencyCost": "media and compositor runtime",
      "packedProof": "check/hermetic:runtime-import+node16+bundler",
      "reason": "Media processing has runtime and performance costs unsuitable for root.",
      "expertRoutes": [
        "liteship/media"
      ],
      "checkIds": [
        "check/hermetic",
        "check/test"
      ],
      "proofRefs": [
        "tests/unit/liteship/facade-subpaths.test.ts",
        "tests/unit/core/media/compositor.test.ts",
        "tests/unit/core/media/compositor-pool.test.ts",
        "tests/unit/core/media/video.test.ts",
        "tests/unit/core/media/frame-budget-runtime.test.ts",
        "tests/unit/core/media/token-buffer.test.ts"
      ],
      "remediation": "Correct the input at @liteship/core/media, retry Compositor.create(options), then run check/hermetic and check/test."
    },
    {
      "kind": "subpath",
      "symbol": "inspectReceipt",
      "specifier": "liteship/evidence",
      "owner": "@liteship/core/evidence",
      "audience": "operator",
      "category": "evidence-and-quality",
      "surfaceClass": "advanced-module",
      "producer": "@liteship/core/evidence",
      "relatedInvariant": "INV-CONSUMER-SUBPATH-CLOSURE",
      "replacement": "none",
      "role": "evidence-and-quality",
      "userStory": "Inspect receipts, diagnostics, quality tiers, capabilities, and addressed evidence.",
      "lifecycle": "pure readers and immutable receipts",
      "failureContract": "Invalid chains, addresses, and capability decisions are refused with structured evidence.",
      "failureProof": null,
      "example": "inspectReceipt(receipt)",
      "stability": "stable",
      "dependencyCost": "pure evidence kernels",
      "packedProof": "check/hermetic:runtime-import+node16+bundler",
      "reason": "Receipts and tier policy are expert inspection surfaces.",
      "expertRoutes": [
        "liteship/evidence"
      ],
      "checkIds": [
        "check/hermetic",
        "check/test"
      ],
      "proofRefs": [
        "tests/unit/liteship/facade-subpaths.test.ts"
      ],
      "remediation": "Correct the input at @liteship/core/evidence, retry inspectReceipt(receipt), then run check/hermetic and check/test."
    },
    {
      "kind": "subpath",
      "symbol": "CSSCompiler",
      "specifier": "liteship/compiler",
      "owner": "@liteship/compiler",
      "audience": "application-author",
      "category": "projection-compiler",
      "surfaceClass": "advanced-module",
      "producer": "@liteship/compiler",
      "relatedInvariant": "INV-CONSUMER-SUBPATH-CLOSURE",
      "replacement": "none",
      "role": "projection-compiler",
      "userStory": "Compile definitions into CSS, shader, accessibility, AI, and motion targets.",
      "lifecycle": "pure compilation",
      "failureContract": "CSS state keys outside the boundary are omitted and emit the registered compiler/css/unknown-state-key diagnostic.",
      "failureProof": {
        "test": "tests/unit/liteship/facade-failure-contract.test.ts::liteship/compiler failure contract > CSSCompiler.compile omits an unknown state and emits its registered diagnostic",
        "importSource": "../../../packages/liteship/src/compiler.js",
        "operation": "CSSCompiler.compile",
        "observation": {
          "kind": "diagnostic-and-output-omission",
          "code": "compiler/css/unknown-state-key",
          "outputField": "raw"
        }
      },
      "example": "CSSCompiler.compile(boundary, input)",
      "stability": "stable",
      "dependencyCost": "compiler kernels",
      "packedProof": "check/hermetic:runtime-import+node16+bundler",
      "reason": "Projection targets are advanced escape hatches behind the default Adaptive plan.",
      "expertRoutes": [
        "liteship/compiler"
      ],
      "checkIds": [
        "check/hermetic",
        "check/test"
      ],
      "proofRefs": [
        "tests/unit/liteship/facade-subpaths.test.ts",
        "tests/unit/liteship/facade-failure-contract.test.ts"
      ],
      "remediation": "Correct the input at @liteship/compiler, retry CSSCompiler.compile(boundary, input), then run check/hermetic and check/test."
    },
    {
      "kind": "subpath",
      "symbol": "Morph",
      "specifier": "liteship/runtime",
      "owner": "@liteship/web",
      "audience": "application-author",
      "category": "browser-runtime",
      "surfaceClass": "advanced-module",
      "producer": "@liteship/web",
      "relatedInvariant": "INV-CONSUMER-SUBPATH-CLOSURE",
      "replacement": "none",
      "role": "browser-runtime",
      "userStory": "Apply streaming, morphing, recovery, integrity, and browser runtime behavior.",
      "lifecycle": "connections and observers require disposal",
      "failureContract": "Unsafe URLs, invalid patches, and broken resumptions fail closed.",
      "failureProof": null,
      "example": "Morph.morph(input, input)",
      "stability": "stable",
      "dependencyCost": "browser DOM runtime",
      "packedProof": "check/hermetic:runtime-import+node16+bundler",
      "reason": "Browser runtime code must never load through the host-free root.",
      "expertRoutes": [
        "liteship/runtime"
      ],
      "checkIds": [
        "check/hermetic",
        "check/test",
        "check/test-e2e"
      ],
      "proofRefs": [
        "tests/unit/liteship/facade-subpaths.test.ts",
        "tests/unit/web/llm-adapter.test.ts",
        "tests/unit/liteship/facade-lifecycle-contract.test.ts",
        "tests/unit/web/web-runtime-primitives.test.ts",
        "tests/unit/web/runtime-security-helpers.test.ts",
        "tests/unit/web/physical.test.ts",
        "tests/unit/web/web-capture.test.ts"
      ],
      "remediation": "Correct the input at @liteship/web, retry Morph.morph(input, input), then run check/hermetic and check/test and check/test-e2e."
    },
    {
      "kind": "subpath",
      "symbol": "adaptiveAttrs",
      "specifier": "liteship/astro",
      "owner": "@liteship/astro",
      "audience": "host-integrator",
      "category": "astro-host",
      "surfaceClass": "advanced-module",
      "producer": "@liteship/astro",
      "relatedInvariant": "INV-CONSUMER-SUBPATH-CLOSURE",
      "replacement": "none",
      "role": "astro-host",
      "userStory": "Install LiteShip into Astro and apply Adaptive attributes and server projections.",
      "lifecycle": "host integration lifecycle",
      "failureContract": "Invalid host configuration fails during integration setup or build.",
      "failureProof": null,
      "example": "adaptiveAttrs(input)",
      "stability": "stable",
      "dependencyCost": "optional Astro peer and host adapter",
      "packedProof": "check/hermetic:runtime-import+node16+bundler",
      "reason": "Astro ownership and peer cost require an explicit host subpath.",
      "expertRoutes": [
        "liteship/astro"
      ],
      "checkIds": [
        "check/hermetic",
        "check/test",
        "check/test-astro"
      ],
      "proofRefs": [
        "tests/unit/liteship/facade-subpaths.test.ts",
        "tests/unit/astro/astro-runtime.test.ts"
      ],
      "remediation": "Correct the input at @liteship/astro, retry adaptiveAttrs(input), then run check/hermetic and check/test and check/test-astro."
    },
    {
      "kind": "subpath",
      "symbol": "plugin",
      "specifier": "liteship/vite",
      "owner": "@liteship/vite",
      "audience": "host-integrator",
      "category": "vite-host",
      "surfaceClass": "advanced-module",
      "producer": "@liteship/vite",
      "relatedInvariant": "INV-CONSUMER-SUBPATH-CLOSURE",
      "replacement": "none",
      "role": "vite-host",
      "userStory": "Install LiteShip into Vite and compile directive and virtual-module projections.",
      "lifecycle": "host plugin lifecycle",
      "failureContract": "Invalid directives and configuration produce stable build diagnostics.",
      "failureProof": null,
      "example": "plugin(options)",
      "stability": "stable",
      "dependencyCost": "optional Vite peer and host plugin",
      "packedProof": "check/hermetic:runtime-import+node16+bundler",
      "reason": "Vite ownership and peer cost require an explicit host subpath.",
      "expertRoutes": [
        "liteship/vite"
      ],
      "checkIds": [
        "check/hermetic",
        "check/test",
        "check/test-vite"
      ],
      "proofRefs": [
        "tests/unit/liteship/facade-subpaths.test.ts"
      ],
      "remediation": "Correct the input at @liteship/vite, retry plugin(options), then run check/hermetic and check/test and check/test-vite."
    },
    {
      "kind": "subpath",
      "symbol": "generatePureTransform",
      "specifier": "liteship/testing",
      "owner": "@liteship/core/harness",
      "audience": "package-author",
      "category": "test-tooling",
      "surfaceClass": "advanced-module",
      "producer": "@liteship/core/harness",
      "relatedInvariant": "INV-CONSUMER-SUBPATH-CLOSURE",
      "replacement": "none",
      "role": "test-tooling",
      "userStory": "Generate proof harnesses and inspect the installed fleet roster without exposing test tooling on the production root.",
      "lifecycle": "test process only",
      "failureContract": "Invalid harness declarations and stale fleet projections fail deterministically.",
      "failureProof": null,
      "example": "generatePureTransform(spec)",
      "stability": "stable",
      "dependencyCost": "test-only harness code and fast-check peer",
      "packedProof": "check/hermetic:runtime-import+node16+bundler",
      "reason": "Proof generators and fleet metadata are a public package-author contract that must remain isolated from production root imports.",
      "expertRoutes": [
        "liteship/testing"
      ],
      "checkIds": [
        "check/hermetic",
        "check/test",
        "check/capsule-verify"
      ],
      "proofRefs": [
        "tests/unit/liteship/facade-subpaths.test.ts"
      ],
      "remediation": "Correct the input at @liteship/core/harness, retry generatePureTransform(spec), then run check/hermetic and check/test and check/capsule-verify."
    },
    {
      "kind": "subpath",
      "symbol": "fromMediaQueries",
      "specifier": "liteship/migrate",
      "owner": "@liteship/compiler/migrate",
      "audience": "application-author",
      "category": "migration",
      "surfaceClass": "advanced-module",
      "producer": "@liteship/compiler/migrate",
      "relatedInvariant": "INV-CONSUMER-SUBPATH-CLOSURE",
      "replacement": "none",
      "role": "migration",
      "userStory": "Translate supported external syntax into ordinary LiteShip definitions.",
      "lifecycle": "pure migration",
      "failureContract": "Unrepresentable source is refused with stable diagnostics and no fabricated definition.",
      "failureProof": null,
      "example": "fromMediaQueries(css)",
      "stability": "stable",
      "dependencyCost": "compiler parser adapters",
      "packedProof": "check/hermetic:runtime-import+node16+bundler",
      "reason": "Migration grammar is an explicit expert boundary, not framework ontology.",
      "expertRoutes": [
        "liteship/migrate"
      ],
      "checkIds": [
        "check/hermetic",
        "check/test"
      ],
      "proofRefs": [
        "tests/unit/liteship/facade-subpaths.test.ts"
      ],
      "remediation": "Correct the input at @liteship/compiler/migrate, retry fromMediaQueries(css), then run check/hermetic and check/test."
    },
    {
      "kind": "subpath",
      "symbol": "defineComponentCatalog",
      "specifier": "liteship/genui",
      "owner": "@liteship/genui",
      "audience": "application-author",
      "category": "generated-ui",
      "surfaceClass": "advanced-module",
      "producer": "@liteship/genui",
      "relatedInvariant": "INV-CONSUMER-SUBPATH-CLOSURE",
      "replacement": "none",
      "role": "generated-ui",
      "userStory": "Define a trusted component catalog, validate generated UI, and render it without raw package discovery.",
      "lifecycle": "immutable catalog and pure validation/rendering",
      "failureContract": "Unknown components, props, or invalid generated trees are refused before rendering.",
      "failureProof": null,
      "example": "defineComponentCatalog(input)",
      "stability": "stable",
      "dependencyCost": "pure generated-UI catalog and renderer",
      "packedProof": "check/journey:one-install-runtime-reference-identity",
      "reason": "Generated UI is a documented product capability that deserves a discoverable facade subpath.",
      "expertRoutes": [
        "liteship/genui"
      ],
      "checkIds": [
        "check/hermetic",
        "check/test",
        "check/journey"
      ],
      "proofRefs": [
        "tests/unit/liteship/facade-subpaths.test.ts"
      ],
      "remediation": "Correct the input at @liteship/genui, retry defineComponentCatalog(input), then run check/hermetic and check/test and check/journey."
    }
  ],
  "lifecycle": [
    {
      "operation": "RuntimeCoordinator.create",
      "specifier": "liteship/reactive",
      "owner": "@liteship/core/reactive",
      "classification": "gc-owned-mutable",
      "disposal": "none",
      "postDispose": "not-applicable",
      "siblingCleanup": "not-applicable",
      "proof": "tests/unit/core/reactive/runtime-coordinator.test.ts",
      "rationale": "Bounded in-memory stores own no timer, subscription, process, or external handle.",
      "checkIds": [
        "check/hermetic",
        "check/test"
      ],
      "remediation": "Do not add artificial disposal; Bounded in-memory stores own no timer, subscription, process, or external handle. Verify tests/unit/core/reactive/runtime-coordinator.test.ts."
    },
    {
      "operation": "StateCellStore.create",
      "specifier": "liteship/reactive",
      "owner": "@liteship/core/reactive",
      "classification": "gc-owned-mutable",
      "disposal": "none",
      "postDispose": "not-applicable",
      "siblingCleanup": "not-applicable",
      "proof": "tests/unit/core/reactive/state-cell.test.ts",
      "rationale": "The registry is an in-memory authority over a coordinator and starts no background work.",
      "checkIds": [
        "check/hermetic",
        "check/test"
      ],
      "remediation": "Do not add artificial disposal; The registry is an in-memory authority over a coordinator and starts no background work. Verify tests/unit/core/reactive/state-cell.test.ts."
    },
    {
      "operation": "createCell",
      "specifier": "liteship/reactive",
      "owner": "@liteship/core/reactive",
      "classification": "active-owned",
      "disposal": "dispose-async",
      "postDispose": "inert",
      "siblingCleanup": "aggregate",
      "proof": "tests/unit/core/reactive/cell.test.ts",
      "rationale": "The cell owns subscriptions and exposes its Lifetime directly through dispose.",
      "checkIds": [
        "check/hermetic",
        "check/test"
      ],
      "remediation": "Dispose through dispose-async and verify tests/unit/core/reactive/cell.test.ts; cleanup must remain idempotent, inert, and attempt-all."
    },
    {
      "operation": "createDirtyFlags",
      "specifier": "liteship/reactive",
      "owner": "@liteship/core/reactive",
      "classification": "gc-owned-mutable",
      "disposal": "none",
      "postDispose": "not-applicable",
      "siblingCleanup": "not-applicable",
      "proof": "tests/unit/core/reactive/dirty-flags-runtime.test.ts",
      "rationale": "Dirty flags are bounded synchronous bit storage with no active resource.",
      "checkIds": [
        "check/hermetic",
        "check/test"
      ],
      "remediation": "Do not add artificial disposal; Dirty flags are bounded synchronous bit storage with no active resource. Verify tests/unit/core/reactive/dirty-flags-runtime.test.ts."
    },
    {
      "operation": "createLifetime",
      "specifier": "liteship/reactive",
      "owner": "@liteship/core/reactive",
      "classification": "active-owned",
      "disposal": "dispose-async",
      "postDispose": "inert",
      "siblingCleanup": "aggregate",
      "proof": "tests/unit/core/reactive/lifetime.test.ts",
      "rationale": "Lifetime is the aggregate exactly-once finalizer authority.",
      "checkIds": [
        "check/hermetic",
        "check/test"
      ],
      "remediation": "Dispose through dispose-async and verify tests/unit/core/reactive/lifetime.test.ts; cleanup must remain idempotent, inert, and attempt-all."
    },
    {
      "operation": "createLiveCell",
      "specifier": "liteship/reactive",
      "owner": "@liteship/core/reactive",
      "classification": "active-owned",
      "disposal": "dispose-async",
      "postDispose": "inert",
      "siblingCleanup": "aggregate",
      "proof": "tests/unit/core/reactive/disposed-write-inert.test.ts",
      "rationale": "The live cell owns its reactive kernel and closes writes and subscribers on disposal.",
      "checkIds": [
        "check/hermetic",
        "check/test"
      ],
      "remediation": "Dispose through dispose-async and verify tests/unit/core/reactive/disposed-write-inert.test.ts; cleanup must remain idempotent, inert, and attempt-all."
    },
    {
      "operation": "createLiveCellBoundary",
      "specifier": "liteship/reactive",
      "owner": "@liteship/core/reactive",
      "classification": "active-owned",
      "disposal": "dispose-async",
      "postDispose": "inert",
      "siblingCleanup": "aggregate",
      "proof": "tests/unit/core/reactive/disposed-write-inert.test.ts",
      "rationale": "The boundary live cell owns its reactive kernel and crossing stream.",
      "checkIds": [
        "check/hermetic",
        "check/test"
      ],
      "remediation": "Dispose through dispose-async and verify tests/unit/core/reactive/disposed-write-inert.test.ts; cleanup must remain idempotent, inert, and attempt-all."
    },
    {
      "operation": "createQuantizer",
      "specifier": "liteship/reactive",
      "owner": "@liteship/quantizer",
      "classification": "active-owned",
      "disposal": "dispose-async",
      "postDispose": "inert",
      "siblingCleanup": "aggregate",
      "proof": "tests/unit/quantizer/animated-quantizer.test.ts",
      "rationale": "A live quantizer owns input subscriptions, transition work, and output delivery.",
      "checkIds": [
        "check/hermetic",
        "check/test"
      ],
      "remediation": "Dispose through dispose-async and verify tests/unit/quantizer/animated-quantizer.test.ts; cleanup must remain idempotent, inert, and attempt-all."
    },
    {
      "operation": "createSignal",
      "specifier": "liteship/reactive",
      "owner": "@liteship/core/reactive",
      "classification": "active-owned",
      "disposal": "dispose-async",
      "postDispose": "inert",
      "siblingCleanup": "aggregate",
      "proof": "tests/unit/core/reactive/signal.test.ts",
      "rationale": "A signal owns source listeners and its delivery kernel.",
      "checkIds": [
        "check/hermetic",
        "check/test"
      ],
      "remediation": "Dispose through dispose-async and verify tests/unit/core/reactive/signal.test.ts; cleanup must remain idempotent, inert, and attempt-all."
    },
    {
      "operation": "createStore",
      "specifier": "liteship/reactive",
      "owner": "@liteship/core/reactive",
      "classification": "active-owned",
      "disposal": "dispose-async",
      "postDispose": "inert",
      "siblingCleanup": "aggregate",
      "proof": "tests/unit/core/reactive/store.test.ts",
      "rationale": "A store owns subscribers and reducer delivery through one Lifetime.",
      "checkIds": [
        "check/hermetic",
        "check/test"
      ],
      "remediation": "Dispose through dispose-async and verify tests/unit/core/reactive/store.test.ts; cleanup must remain idempotent, inert, and attempt-all."
    },
    {
      "operation": "createBlendTree",
      "specifier": "liteship/motion",
      "owner": "@liteship/core/motion",
      "classification": "active-owned",
      "disposal": "dispose-async",
      "postDispose": "inert",
      "siblingCleanup": "aggregate",
      "proof": "tests/unit/core/motion/blend-tree.test.ts",
      "rationale": "The blend tree owns its change kernel and derived subscriptions.",
      "checkIds": [
        "check/hermetic",
        "check/test"
      ],
      "remediation": "Dispose through dispose-async and verify tests/unit/core/motion/blend-tree.test.ts; cleanup must remain idempotent, inert, and attempt-all."
    },
    {
      "operation": "createTimeline",
      "specifier": "liteship/motion",
      "owner": "@liteship/core/motion",
      "classification": "active-owned",
      "disposal": "dispose-async",
      "postDispose": "inert",
      "siblingCleanup": "aggregate",
      "proof": "tests/unit/liteship/facade-lifecycle-contract.test.ts",
      "rationale": "The timeline owns its scheduler and state delivery kernel through direct disposal.",
      "checkIds": [
        "check/hermetic",
        "check/test"
      ],
      "remediation": "Dispose through dispose-async and verify tests/unit/liteship/facade-lifecycle-contract.test.ts; cleanup must remain idempotent, inert, and attempt-all."
    },
    {
      "operation": "createGraphMutationClient",
      "specifier": "liteship/graph",
      "owner": "@liteship/core/graph",
      "classification": "pure-allocation",
      "disposal": "none",
      "postDispose": "not-applicable",
      "siblingCleanup": "not-applicable",
      "proof": "tests/unit/core/graph/graph-mutation-client.test.ts",
      "rationale": "The client allocates request closures but owns no persistent connection or background work.",
      "checkIds": [
        "check/hermetic",
        "check/test"
      ],
      "remediation": "Do not add artificial disposal; The client allocates request closures but owns no persistent connection or background work. Verify tests/unit/core/graph/graph-mutation-client.test.ts."
    },
    {
      "operation": "createGraphQueryRefreshBase",
      "specifier": "liteship/graph",
      "owner": "@liteship/core/graph",
      "classification": "pure-allocation",
      "disposal": "none",
      "postDispose": "not-applicable",
      "siblingCleanup": "not-applicable",
      "proof": "tests/unit/core/graph/graph-query.test.ts",
      "rationale": "The helper creates immutable refresh metadata and no active resource.",
      "checkIds": [
        "check/hermetic",
        "check/test"
      ],
      "remediation": "Do not add artificial disposal; The helper creates immutable refresh metadata and no active resource. Verify tests/unit/core/graph/graph-query.test.ts."
    },
    {
      "operation": "Compositor.create",
      "specifier": "liteship/media",
      "owner": "@liteship/core/media",
      "classification": "active-owned",
      "disposal": "dispose-async",
      "postDispose": "inert",
      "siblingCleanup": "aggregate",
      "proof": "tests/unit/core/media/compositor.test.ts",
      "rationale": "The compositor owns reactive coordination, state delivery, and registered teardown.",
      "checkIds": [
        "check/hermetic",
        "check/test"
      ],
      "remediation": "Dispose through dispose-async and verify tests/unit/core/media/compositor.test.ts; cleanup must remain idempotent, inert, and attempt-all."
    },
    {
      "operation": "createCompositorStatePool",
      "specifier": "liteship/media",
      "owner": "@liteship/core/media",
      "classification": "gc-owned-mutable",
      "disposal": "none",
      "postDispose": "not-applicable",
      "siblingCleanup": "not-applicable",
      "proof": "tests/unit/core/media/compositor-pool.test.ts",
      "rationale": "The state pool is bounded reusable memory with no active external handle.",
      "checkIds": [
        "check/hermetic",
        "check/test"
      ],
      "remediation": "Do not add artificial disposal; The state pool is bounded reusable memory with no active external handle. Verify tests/unit/core/media/compositor-pool.test.ts."
    },
    {
      "operation": "createFrameSchedule",
      "specifier": "liteship/media",
      "owner": "@liteship/core/media",
      "classification": "pure-allocation",
      "disposal": "none",
      "postDispose": "not-applicable",
      "siblingCleanup": "not-applicable",
      "proof": "tests/unit/core/media/video.test.ts",
      "rationale": "The schedule is an immutable frame-coordinate projection and owns no clock, task, or external handle.",
      "checkIds": [
        "check/hermetic",
        "check/test"
      ],
      "remediation": "Do not add artificial disposal; The schedule is an immutable frame-coordinate projection and owns no clock, task, or external handle. Verify tests/unit/core/media/video.test.ts."
    },
    {
      "operation": "createFrameBudget",
      "specifier": "liteship/media",
      "owner": "@liteship/core/media",
      "classification": "active-owned",
      "disposal": "dispose-async",
      "postDispose": "inert",
      "siblingCleanup": "aggregate",
      "proof": "tests/unit/core/media/frame-budget-runtime.test.ts",
      "rationale": "The frame budget owns an animation-frame loop and must cancel it directly.",
      "checkIds": [
        "check/hermetic",
        "check/test"
      ],
      "remediation": "Dispose through dispose-async and verify tests/unit/core/media/frame-budget-runtime.test.ts; cleanup must remain idempotent, inert, and attempt-all."
    },
    {
      "operation": "createTokenBuffer",
      "specifier": "liteship/media",
      "owner": "@liteship/core/media",
      "classification": "gc-owned-mutable",
      "disposal": "none",
      "postDispose": "not-applicable",
      "siblingCleanup": "not-applicable",
      "proof": "tests/unit/core/media/token-buffer.test.ts",
      "rationale": "The token buffer is bounded synchronous storage and owns no active resource.",
      "checkIds": [
        "check/hermetic",
        "check/test"
      ],
      "remediation": "Do not add artificial disposal; The token buffer is bounded synchronous storage and owns no active resource. Verify tests/unit/core/media/token-buffer.test.ts."
    },
    {
      "operation": "createVideoRenderer",
      "specifier": "liteship/media",
      "owner": "@liteship/core/media",
      "classification": "pure-allocation",
      "disposal": "none",
      "postDispose": "not-applicable",
      "siblingCleanup": "not-applicable",
      "proof": "tests/unit/core/media/video.test.ts",
      "rationale": "The renderer is a caller-driven async projection over a compositor and immutable frame schedule; it starts no independent task.",
      "checkIds": [
        "check/hermetic",
        "check/test"
      ],
      "remediation": "Do not add artificial disposal; The renderer is a caller-driven async projection over a compositor and immutable frame schedule; it starts no independent task. Verify tests/unit/core/media/video.test.ts."
    },
    {
      "operation": "LLMAdapter.create",
      "specifier": "liteship/runtime",
      "owner": "@liteship/web",
      "classification": "gc-owned-mutable",
      "disposal": "none",
      "postDispose": "not-applicable",
      "siblingCleanup": "not-applicable",
      "proof": "tests/unit/web/llm-adapter.test.ts",
      "rationale": "The adapter transforms caller-driven iteration and starts no independent task or connection.",
      "checkIds": [
        "check/hermetic",
        "check/test",
        "check/test-e2e"
      ],
      "remediation": "Do not add artificial disposal; The adapter transforms caller-driven iteration and starts no independent task or connection. Verify tests/unit/web/llm-adapter.test.ts."
    },
    {
      "operation": "SSE.create",
      "specifier": "liteship/runtime",
      "owner": "@liteship/web",
      "classification": "active-owned",
      "disposal": "dispose-async",
      "postDispose": "inert",
      "siblingCleanup": "aggregate",
      "proof": "tests/unit/liteship/facade-lifecycle-contract.test.ts",
      "rationale": "The client owns timers, one EventSource generation, buffers, and two delivery streams.",
      "checkIds": [
        "check/hermetic",
        "check/test",
        "check/test-e2e"
      ],
      "remediation": "Dispose through dispose-async and verify tests/unit/liteship/facade-lifecycle-contract.test.ts; cleanup must remain idempotent, inert, and attempt-all."
    },
    {
      "operation": "SlotRegistry.create",
      "specifier": "liteship/runtime",
      "owner": "@liteship/web",
      "classification": "gc-owned-mutable",
      "disposal": "none",
      "postDispose": "not-applicable",
      "siblingCleanup": "not-applicable",
      "proof": "tests/unit/web/web-runtime-primitives.test.ts",
      "rationale": "The registry is inert storage; DOM observation is a separate operation returning its own disposer.",
      "checkIds": [
        "check/hermetic",
        "check/test",
        "check/test-e2e"
      ],
      "remediation": "Do not add artificial disposal; The registry is inert storage; DOM observation is a separate operation returning its own disposer. Verify tests/unit/web/web-runtime-primitives.test.ts."
    },
    {
      "operation": "createAudioProcessor",
      "specifier": "liteship/runtime",
      "owner": "@liteship/web",
      "classification": "active-owned",
      "disposal": "dispose-async",
      "postDispose": "inert",
      "siblingCleanup": "aggregate",
      "proof": "tests/unit/liteship/facade-lifecycle-contract.test.ts",
      "rationale": "The processor owns a worklet node, graph connection, and bridge running state.",
      "checkIds": [
        "check/hermetic",
        "check/test",
        "check/test-e2e"
      ],
      "remediation": "Dispose through dispose-async and verify tests/unit/liteship/facade-lifecycle-contract.test.ts; cleanup must remain idempotent, inert, and attempt-all."
    },
    {
      "operation": "createHtmlFragment",
      "specifier": "liteship/runtime",
      "owner": "@liteship/web",
      "classification": "pure-allocation",
      "disposal": "none",
      "postDispose": "not-applicable",
      "siblingCleanup": "not-applicable",
      "proof": "tests/unit/web/runtime-security-helpers.test.ts",
      "rationale": "The helper returns an inert document fragment and starts no observer or background work.",
      "checkIds": [
        "check/hermetic",
        "check/test",
        "check/test-e2e"
      ],
      "remediation": "Do not add artificial disposal; The helper returns an inert document fragment and starts no observer or background work. Verify tests/unit/web/runtime-security-helpers.test.ts."
    },
    {
      "operation": "createPhysicalStateTracker",
      "specifier": "liteship/runtime",
      "owner": "@liteship/web",
      "classification": "active-owned",
      "disposal": "dispose-async",
      "postDispose": "inert",
      "siblingCleanup": "aggregate",
      "proof": "tests/unit/web/physical.test.ts",
      "rationale": "The tracker owns three document composition listeners; disposal removes every listener and clears the active IME state.",
      "checkIds": [
        "check/hermetic",
        "check/test",
        "check/test-e2e"
      ],
      "remediation": "Dispose through dispose-async and verify tests/unit/web/physical.test.ts; cleanup must remain idempotent, inert, and attempt-all."
    },
    {
      "operation": "createWebCodecsCapture",
      "specifier": "liteship/runtime",
      "owner": "@liteship/web",
      "classification": "active-owned",
      "disposal": "dispose-async",
      "postDispose": "inert",
      "siblingCleanup": "aggregate",
      "proof": "tests/unit/web/web-capture.test.ts",
      "rationale": "The capture owns a VideoEncoder and mediabunny Output; terminal finalize and explicit disposal both release every host handle.",
      "checkIds": [
        "check/hermetic",
        "check/test",
        "check/test-e2e"
      ],
      "remediation": "Dispose through dispose-async and verify tests/unit/web/web-capture.test.ts; cleanup must remain idempotent, inert, and attempt-all."
    },
    {
      "operation": "createLLMSession",
      "specifier": "liteship/astro",
      "owner": "@liteship/astro/runtime",
      "classification": "active-owned",
      "disposal": "dispose-async",
      "postDispose": "inert",
      "siblingCleanup": "aggregate",
      "proof": "tests/unit/astro/astro-runtime.test.ts",
      "rationale": "The session owns pooled render runtime state and queued delivery work.",
      "checkIds": [
        "check/hermetic",
        "check/test",
        "check/test-astro"
      ],
      "remediation": "Dispose through dispose-async and verify tests/unit/astro/astro-runtime.test.ts; cleanup must remain idempotent, inert, and attempt-all."
    }
  ]
} as const;
export type GeneratedPublicSurfaceContext = typeof GENERATED_PUBLIC_SURFACE_CONTEXT;
