/**
 * Generated dependency-ordered scoped fleet roster for expert test and release
 * tooling. This module owns the data; `liteship/testing` only re-exports it.
 *
 * @module
 */

/* BEGIN gen-roster: LITESHIP_PACKAGES — generated by scripts/gen-roster.ts (renderLiteshipPackages); do not hand-edit inside these markers. */
// prettier-ignore
export const LITESHIP_PACKAGES = [
  "@liteship/_spine",
  "@liteship/error",
  "@liteship/canonical",
  "@liteship/core",
  "@liteship/genui",
  "@liteship/quantizer",
  "@liteship/compiler",
  "@liteship/web",
  "@liteship/detect",
  "@liteship/edge",
  "@liteship/vite",
  "@liteship/worker",
  "@liteship/remotion",
  "@liteship/scene",
  "@liteship/astro",
  "@liteship/cloudflare",
  "@liteship/stage",
  "@liteship/assets",
  "@liteship/gauntlet",
  "@liteship/audit",
  "@liteship/command",
  "@liteship/cli",
  "@liteship/mcp-server",
] as const;
/* END gen-roster: LITESHIP_PACKAGES */

export type LiteshipPackageName = (typeof LITESHIP_PACKAGES)[number];
