#!/usr/bin/env tsx
/**
 * Project the one authored package catalog into every package/runtime format
 * that cannot import the repo-local source directly.
 *
 * Authored truth: {@link PACKAGE_CATALOG} in `scripts/package-catalog.ts`.
 * Generated projections:
 *  - audit's scoped fleet roster
 *  - liteship's shipped fleet roster
 *  - command's package-smoke specifications
 *  - CLI package metadata
 *  - the release workflow's publish-order JSON
 *
 * The check mode independently reads package manifests and export maps, so a
 * catalog error cannot bless itself merely by regenerating its projections.
 *
 * @module
 */

import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { isDirectExecution, walkTrackedFiles } from './audit/shared.js';
import { PACKAGE_CATALOG, type PackageCatalogRecord } from './package-catalog.js';

const REPO_ROOT = resolve(fileURLToPath(import.meta.url), '..', '..');

export { PACKAGE_CATALOG } from './package-catalog.js';

/** The 23 scoped packages installed by the `liteship` facade. */
export const CANONICAL_ROSTER: readonly string[] = PACKAGE_CATALOG.filter((record) =>
  record.name.startsWith('@liteship/'),
).map((record) => record.name);

/** The two unscoped packages that publish after the scoped fleet. */
export const PUBLISHABLE_UMBRELLAS: readonly string[] = PACKAGE_CATALOG.filter(
  (record) => !record.name.startsWith('@liteship/'),
).map((record) => record.name);

/** The exact dependency-ordered 25-package publish roster. */
export const PUBLISHABLE_ROSTER: readonly string[] = PACKAGE_CATALOG.map((record) => record.name);

export const PUBLISH_ROSTER_JSON = 'scripts/ci/publish-roster.json';
export const AUDIT_ROSTER_TS = 'packages/audit/src/package-catalog.generated.ts';
export const COMMAND_SMOKE_TS = 'packages/command/src/commands/package-smoke-registry.generated.ts';
export const CLI_METADATA_TS = 'packages/cli/src/lib/package-metadata-catalog.generated.ts';
export const AUDIT_TOPOLOGY_TS = 'packages/audit/src/package-topology.generated.ts';
export const COMMAND_PLUMB_TS = 'packages/command/src/commands/plumb-registry.generated.ts';
export const DOC_PACKAGE_GROUPS_TS = 'scripts/lib/package-docs.generated.ts';
export const API_SURFACE_PACKAGES_TS = 'tests/fixtures/api-surface-packages.generated.ts';
export const ROOT_TSCONFIG_JSON = 'tsconfig.json';
export const TYPEDOC_JSON = 'typedoc.json';
const LITESHIP_INDEX_REL = 'packages/liteship/src/index.ts';

export interface CatalogManifest {
  readonly name?: string;
  readonly private?: boolean;
  readonly description?: string;
  readonly keywords?: readonly string[];
  readonly publishConfig?: Readonly<Record<string, unknown>>;
  readonly dependencies?: Readonly<Record<string, string>>;
  readonly exports?: string | Readonly<Record<string, unknown>>;
}

export interface CatalogDrift {
  readonly copy: string;
  readonly detail: string;
}

export interface CatalogSource {
  readonly path: string;
  readonly text: string;
}

function generatedHeader(source: string): string {
  return `/** @generated by ${source}; do not hand-edit. */\n`;
}

function quote(value: string): string {
  return JSON.stringify(value);
}

function renderStringArray(values: readonly string[], indent = '  '): string {
  if (values.length === 0) return '[]';
  return `[\n${values.map((value) => `${indent}${quote(value)},`).join('\n')}\n]`;
}

/** The `LITESHIP_PACKAGES` block shipped by the facade. */
export function renderLiteshipPackages(): string {
  const entries = CANONICAL_ROSTER.map((name) => `  ${quote(name)},`).join('\n');
  return `// prettier-ignore\nexport const LITESHIP_PACKAGES = [\n${entries}\n] as const;`;
}

export function renderAuditRoster(): string {
  return (
    generatedHeader('scripts/gen-roster.ts from scripts/package-catalog.ts') +
    `// prettier-ignore\nexport const GENERATED_LITESHIP_PACKAGE_ROSTER = ${renderStringArray(CANONICAL_ROSTER)} as const;\n`
  );
}

export function renderCommandSmokeRoster(): string {
  const rows = PACKAGE_CATALOG.map((record) => {
    const imports = record.smokeImports.map((specifier) => quote(specifier)).join(', ');
    return `  { dir: ${quote(record.dir)}, name: ${quote(record.name)}, imports: [${imports}] },`;
  }).join('\n');
  return (
    generatedHeader('scripts/gen-roster.ts from scripts/package-catalog.ts') +
    `// prettier-ignore\nexport const GENERATED_PACKAGE_SMOKE_SPECS = [\n${rows}\n] as const;\n`
  );
}

export function renderCliMetadataCatalog(): string {
  const rows = PACKAGE_CATALOG.map(
    (record) =>
      `  ${quote(record.name)}: {\n` +
      `    description: ${quote(record.description)},\n` +
      `    keywords: [${record.keywords.map((keyword) => quote(keyword)).join(', ')}],\n` +
      `  },`,
  ).join('\n');
  return (
    generatedHeader('scripts/gen-roster.ts from scripts/package-catalog.ts') +
    `// prettier-ignore\nexport const GENERATED_PACKAGE_METADATA = {\n${rows}\n} as const;\n`
  );
}

export function renderAuditTopology(): string {
  const rows = PACKAGE_CATALOG.map((record) => {
    const imports = record.audit.allowedInternalImports.map((name) => quote(name)).join(', ');
    const reason = record.audit.reason == null ? '' : `  // ${record.audit.reason}\n`;
    return `${reason}  ${quote(record.name)}: { kind: ${quote(record.audit.kind)}, allowedInternalImports: [${imports}] },`;
  }).join('\n');
  return `${generatedHeader('scripts/gen-roster.ts from scripts/package-catalog.ts')}// prettier-ignore\nexport const GENERATED_PACKAGE_TOPOLOGY = {\n${rows}\n} as const;\n`;
}

export function renderCommandPlumb(): string {
  const rows = PACKAGE_CATALOG.map((record) => {
    const issue = record.plumbIssue == null ? '' : `, issue: ${quote(record.plumbIssue)}`;
    return `  ${quote(record.name)}: { status: ${quote(record.plumbStatus)}, reason: ${quote(record.plumbReason)}${issue} },`;
  }).join('\n');
  return `${generatedHeader('scripts/gen-roster.ts from scripts/package-catalog.ts')}// prettier-ignore\nexport const GENERATED_PACKAGE_PLUMB = {\n${rows}\n} as const;\n`;
}

export function renderDocPackageGroups(): string {
  const groups = ['foundations', 'hosts', 'runtime', 'tooling'] as const;
  const rows = groups
    .map((group) => {
      const members = [...PACKAGE_CATALOG.filter((record) => record.docs.group === group)]
        .sort((left, right) => left.docs.order - right.docs.order)
        .map((record) => quote(record.name));
      return `  ${quote(group)}: [${members.join(', ')}],`;
    })
    .join('\n');
  const prose = [...PACKAGE_CATALOG.filter((record) => record.docs.group === 'prose-only')]
    .sort((left, right) => left.docs.order - right.docs.order)
    .map((record) => quote(record.name));
  const noSurface = PACKAGE_CATALOG.filter((record) => !record.docs.surface).map((record) => quote(record.name));
  return (
    generatedHeader('scripts/gen-roster.ts from scripts/package-catalog.ts') +
    `// prettier-ignore\nexport const GENERATED_DOC_PACKAGE_GROUPS = {\n${rows}\n} as const;\n` +
    `export const GENERATED_PROSE_ONLY = [${prose.join(', ')}] as const;\n` +
    `export const GENERATED_NO_SURFACE_SECTION = [${noSurface.join(', ')}] as const;\n`
  );
}

export function renderApiSurfacePackages(): string {
  const names = [...PACKAGE_CATALOG.filter((record) => record.apiSurface)]
    .sort((left, right) => (left.apiSurfaceOrder ?? 0) - (right.apiSurfaceOrder ?? 0))
    .map((record) => quote(record.name));
  return `${generatedHeader('scripts/gen-roster.ts from scripts/package-catalog.ts')}// prettier-ignore\nexport const GENERATED_API_SURFACE_PACKAGES = [\n${names.map((name) => `  ${name},`).join('\n')}\n] as const;\n`;
}

function renderRootTsconfig(): string {
  const parsed = JSON.parse(readFileSync(resolve(REPO_ROOT, ROOT_TSCONFIG_JSON), 'utf8')) as Record<string, unknown>;
  parsed.references = PACKAGE_CATALOG.map((record) => ({ path: `./${record.dir}` }));
  return `${JSON.stringify(parsed, null, 2)}\n`;
}

function renderTypedocJson(): string {
  const parsed = JSON.parse(readFileSync(resolve(REPO_ROOT, TYPEDOC_JSON), 'utf8')) as Record<string, unknown>;
  parsed.entryPoints = [...PACKAGE_CATALOG.filter((record) => record.typedocEntry !== null)]
    .sort((left, right) => (left.typedocOrder ?? 0) - (right.typedocOrder ?? 0))
    .map((record) => record.typedocEntry);
  return `${JSON.stringify(parsed, null, 2)}\n`;
}

export function renderPublishRosterJson(): string {
  return `${JSON.stringify(
    {
      $generated:
        'by scripts/gen-roster.ts from scripts/package-catalog.ts — do not hand-edit; regenerate with: pnpm exec tsx scripts/gen-roster.ts --write',
      expectedPublishable: PUBLISHABLE_ROSTER.length,
      packages: PUBLISHABLE_ROSTER,
    },
    null,
    2,
  )}\n`;
}

function readReleaseYaml(): string {
  return readFileSync(resolve(REPO_ROOT, '.github', 'workflows', 'release.yml'), 'utf8');
}

function stripGeneratedBlocks(source: string): string {
  return source
    .replace(/<!-- BEGIN [A-Z0-9_-]+[^]*?<!-- END [A-Z0-9_-]+ -->/g, '')
    .replace(/\/\* BEGIN gen-roster:[^]*?\/\* END gen-roster:[^]*?\*\//g, '');
}

function isSanctionedFleetSource(path: string): boolean {
  const normalized = path.replaceAll('\\', '/');
  const exactGenerated = new Set([
    ...renderGeneratedProjections().map(([relativePath]) => relativePath),
    'scripts/ci/publish-roster.json',
    'tests/fixtures/api-surface-snapshot.json',
    'tests/fixtures/type-export-surface.json',
  ]);
  return (
    normalized === 'scripts/package-catalog.ts' ||
    normalized === 'pnpm-lock.yaml' ||
    normalized.endsWith('/package.json') ||
    exactGenerated.has(normalized) ||
    normalized.startsWith('tests/fixtures/package-catalog-red/')
  );
}

/**
 * Reject a second authored scoped-fleet list. Generated marker blocks, package
 * manifests, lock data, API snapshots, and deliberate red fixtures are the
 * only sanctioned places where all 23 scoped names may appear together.
 */
export function findAuthoredFleetLists(sources: readonly CatalogSource[]): readonly CatalogDrift[] {
  const drift: CatalogDrift[] = [];
  for (const source of sources) {
    if (isSanctionedFleetSource(source.path)) continue;
    const text = stripGeneratedBlocks(source.text);
    const present = CANONICAL_ROSTER.filter((name) => text.includes(name));
    if (present.length === CANONICAL_ROSTER.length) {
      drift.push({
        copy: source.path,
        detail: 'contains a second authored full-fleet package list; project it from scripts/package-catalog.ts',
      });
    }
  }
  return drift;
}

function trackedCatalogSources(): readonly CatalogSource[] {
  const paths = walkTrackedFiles(REPO_ROOT).filter((path) => /\.(?:[cm]?[jt]sx?|json|ya?ml|md)$/u.test(path));
  return paths.map((path) => ({ path, text: readFileSync(resolve(REPO_ROOT, path), 'utf8') }));
}

/** The release publish job, isolated for literal-free checks. */
export function publishJobText(yaml: string): string {
  const index = yaml.indexOf('\n  publish:');
  if (index === -1) throw new Error('release.yml: `publish:` job not found');
  return yaml.slice(index);
}

export function renderGeneratedProjections(): ReadonlyArray<readonly [string, string]> {
  return [
    [AUDIT_ROSTER_TS, renderAuditRoster()],
    [COMMAND_SMOKE_TS, renderCommandSmokeRoster()],
    [CLI_METADATA_TS, renderCliMetadataCatalog()],
    [AUDIT_TOPOLOGY_TS, renderAuditTopology()],
    [COMMAND_PLUMB_TS, renderCommandPlumb()],
    [DOC_PACKAGE_GROUPS_TS, renderDocPackageGroups()],
    [API_SURFACE_PACKAGES_TS, renderApiSurfacePackages()],
    [ROOT_TSCONFIG_JSON, renderRootTsconfig()],
    [TYPEDOC_JSON, renderTypedocJson()],
    [PUBLISH_ROSTER_JSON, renderPublishRosterJson()],
  ];
}

function renderArchitectureDag(): string {
  const lines = PACKAGE_CATALOG.flatMap((record) =>
    record.dependencies.length === 0
      ? [`${record.name} (dependency root)`]
      : record.dependencies.map((dependency) => `${dependency} -> ${record.name}`),
  );
  return `\`\`\`text\n${lines.join('\n')}\n\`\`\``;
}

function renderPackageSurfaceIndex(): string {
  const rows = PACKAGE_CATALOG.map(
    (record) =>
      `| \`${record.name}\` | ${record.layer} | ${record.publicSubpaths.map((path) => `\`${path}\``).join(', ')} | ${record.capabilities.join(', ')} |`,
  );
  return ['| Package | Layer | Public subpaths | Capabilities |', '| --- | --- | --- | --- |', ...rows].join('\n');
}

function renderAgentPackageContext(): string {
  const rows = PACKAGE_CATALOG.map(
    (record) => `| \`${record.name}\` | \`${record.dir}\` | ${record.capabilities.join(', ')} |`,
  );
  return [
    '## Generated package context',
    '',
    'Use this index to find the semantic owner; public subpaths and dependency edges are generated in `PACKAGE-SURFACES.md` and `ARCHITECTURE.md`.',
    '',
    '| Package | Owner directory | Capabilities |',
    '| --- | --- | --- |',
    ...rows,
  ].join('\n');
}

const MARKDOWN_PROJECTIONS = [
  ['ARCHITECTURE.md', 'PACKAGE-DAG', renderArchitectureDag],
  ['PACKAGE-SURFACES.md', 'PACKAGE-SURFACE-INDEX', renderPackageSurfaceIndex],
  ['AGENTS.md', 'AGENT-PACKAGE-CONTEXT', renderAgentPackageContext],
] as const;

function applyMarkdownProjection(source: string, marker: string, rendered: string): string {
  const expression = new RegExp(`(<!-- BEGIN ${marker}[^]*?-->\\n)[^]*?(\\n<!-- END ${marker} -->)`);
  if (!expression.test(source)) throw new Error(`gen-roster: missing ${marker} markers`);
  return source.replace(expression, (_match, begin: string, end: string) => `${begin}${rendered}${end}`);
}

const LITESHIP_BLOCK =
  /(\/\* BEGIN gen-roster: LITESHIP_PACKAGES[^\n]*\*\/\n)[\s\S]*?(\n\/\* END gen-roster: LITESHIP_PACKAGES \*\/)/;

function writeIfChanged(relativePath: string, expected: string): void {
  const path = resolve(REPO_ROOT, relativePath);
  const current = existsSync(path) ? readFileSync(path, 'utf8') : undefined;
  if (current !== expected) writeFileSync(path, expected);
}

function write(): number {
  for (const [relativePath, expected] of renderGeneratedProjections()) writeIfChanged(relativePath, expected);

  for (const [relativePath, marker, render] of MARKDOWN_PROJECTIONS) {
    const path = resolve(REPO_ROOT, relativePath);
    const source = readFileSync(path, 'utf8');
    writeIfChanged(relativePath, applyMarkdownProjection(source, marker, render()));
  }

  const indexPath = resolve(REPO_ROOT, LITESHIP_INDEX_REL);
  const source = readFileSync(indexPath, 'utf8');
  if (!LITESHIP_BLOCK.test(source)) {
    process.stderr.write(`gen-roster: markers missing from ${LITESHIP_INDEX_REL}\n`);
    return 1;
  }
  const stamped = source.replace(
    LITESHIP_BLOCK,
    (_match, begin: string, end: string) => `${begin}${renderLiteshipPackages()}${end}`,
  );
  writeIfChanged(LITESHIP_INDEX_REL, stamped);
  process.stdout.write(
    `gen-roster: generated ${renderGeneratedProjections().length + 1} projections from ${PACKAGE_CATALOG.length} catalog records.\n`,
  );
  return 0;
}

function arrayEqual(left: readonly string[], right: readonly string[]): boolean {
  return left.length === right.length && left.every((value, index) => value === right[index]);
}

function setEqual(left: readonly string[], right: readonly string[]): boolean {
  return left.length === right.length && left.every((value) => right.includes(value));
}

function manifestExportSubpaths(exportsField: CatalogManifest['exports']): readonly string[] {
  if (typeof exportsField === 'string') return ['.'];
  if (exportsField == null) return [];
  return Object.entries(exportsField)
    .filter(([, target]) => target !== null)
    .map(([subpath]) => subpath);
}

function internalDependencies(manifest: CatalogManifest): readonly string[] {
  return Object.keys(manifest.dependencies ?? {}).filter(
    (name) => name.startsWith('@liteship/') || name === 'liteship' || name === 'create-liteship',
  );
}

function manifestFor(record: PackageCatalogRecord): CatalogManifest | undefined {
  const path = resolve(REPO_ROOT, record.dir, 'package.json');
  if (!existsSync(path)) return undefined;
  return JSON.parse(readFileSync(path, 'utf8')) as CatalogManifest;
}

/**
 * Validate a candidate catalog against an independent manifest/directory view.
 *
 * The parameters are explicit so red fixtures can prove every failure mode
 * without mutating the working tree or teaching the validator about its own
 * generated output.
 */
export function validatePackageCatalog(
  catalog: readonly PackageCatalogRecord[],
  manifests: ReadonlyMap<string, CatalogManifest>,
  publishableDirs: readonly string[],
): readonly CatalogDrift[] {
  const drift: CatalogDrift[] = [];
  const packageNames = catalog.map((record) => record.name);
  if (catalog.length !== 25) {
    drift.push({ copy: 'PACKAGE_CATALOG', detail: `expected exactly 25 records, found ${catalog.length}` });
  }
  if (new Set(packageNames).size !== packageNames.length) {
    drift.push({ copy: 'PACKAGE_CATALOG', detail: 'contains duplicate package names' });
  }
  if (new Set(catalog.map((record) => record.dir)).size !== catalog.length) {
    drift.push({ copy: 'PACKAGE_CATALOG', detail: 'contains duplicate package directories' });
  }

  const validateOrders = (label: string, orders: readonly (number | null)[]): void => {
    if (orders.some((order) => order == null)) {
      drift.push({ copy: 'PACKAGE_CATALOG', detail: `${label} has a missing order` });
      return;
    }
    const actual = (orders as readonly number[]).toSorted((left, right) => left - right);
    const expected = Array.from({ length: actual.length }, (_value, index) => index);
    if (!arrayEqual(actual.map(String), expected.map(String))) {
      drift.push({ copy: 'PACKAGE_CATALOG', detail: `${label} orders must be unique and contiguous from zero` });
    }
  };
  for (const group of ['foundations', 'hosts', 'runtime', 'tooling', 'prose-only'] as const) {
    validateOrders(
      `docs.${group}`,
      catalog.filter((record) => record.docs.group === group).map((record) => record.docs.order),
    );
  }
  validateOrders(
    'apiSurface',
    catalog.filter((record) => record.apiSurface).map((record) => record.apiSurfaceOrder),
  );
  validateOrders(
    'typedoc',
    catalog.filter((record) => record.typedocEntry !== null).map((record) => record.typedocOrder),
  );

  const seen = new Set<string>();
  const knownNames = new Set(packageNames);
  for (const record of catalog) {
    if (record.apiSurface !== (record.apiSurfaceOrder !== null)) {
      drift.push({ copy: `PACKAGE_CATALOG:${record.name}`, detail: 'apiSurface and apiSurfaceOrder disagree' });
    }
    if ((record.typedocEntry !== null) !== (record.typedocOrder !== null)) {
      drift.push({ copy: `PACKAGE_CATALOG:${record.name}`, detail: 'typedocEntry and typedocOrder disagree' });
    }
    if (record.plumbStatus === 'deferred' && record.plumbIssue == null) {
      drift.push({ copy: `PACKAGE_CATALOG:${record.name}`, detail: 'deferred plumb status requires plumbIssue' });
    }
    for (const [field, values] of [
      ['dependencies', record.dependencies],
      ['capabilities', record.capabilities],
      ['publicSubpaths', record.publicSubpaths],
      ['smokeImports', record.smokeImports],
      ['audit.allowedInternalImports', record.audit.allowedInternalImports],
    ] as const) {
      if (new Set(values).size !== values.length) {
        drift.push({ copy: `PACKAGE_CATALOG:${record.name}`, detail: `${field} contains duplicate entries` });
      }
    }
    const importablePublicSpecifiers = record.publicSubpaths.map((subpath) =>
      subpath === '.' ? record.name : `${record.name}${subpath.slice(1)}`,
    );
    for (const specifier of record.smokeImports) {
      if (!importablePublicSpecifiers.includes(specifier)) {
        drift.push({
          copy: `PACKAGE_CATALOG:${record.name}`,
          detail: `smoke import ${specifier} is not a positive publicSubpaths export`,
        });
      }
    }
    for (const dependency of record.dependencies) {
      if (!knownNames.has(dependency)) {
        drift.push({
          copy: `PACKAGE_CATALOG:${record.name}`,
          detail: `dependency ${dependency} is not a catalog package`,
        });
      } else if (!seen.has(dependency)) {
        drift.push({
          copy: `PACKAGE_CATALOG:${record.name}`,
          detail: `dependency ${dependency} does not precede its consumer in publish order`,
        });
      }
    }
    seen.add(record.name);

    const manifest = manifests.get(record.dir);
    if (!manifest) {
      drift.push({ copy: record.name, detail: `missing ${record.dir}/package.json` });
      continue;
    }
    if (manifest.name !== record.name)
      drift.push({ copy: record.name, detail: `manifest name is ${manifest.name ?? '<missing>'}` });
    if (manifest.private === true || manifest.publishConfig == null) {
      drift.push({
        copy: record.name,
        detail: 'catalog says publishable but manifest is private or lacks publishConfig',
      });
    }
    const deps = internalDependencies(manifest);
    if (!setEqual(record.dependencies, deps)) {
      drift.push({
        copy: record.name,
        detail: `dependencies differ: catalog=${record.dependencies.join(',')} manifest=${deps.join(',')}`,
      });
    }
    const subpaths = manifestExportSubpaths(manifest.exports);
    if (!arrayEqual(record.publicSubpaths, subpaths)) {
      drift.push({
        copy: record.name,
        detail: `publicSubpaths differ: catalog=${record.publicSubpaths.join(',')} manifest=${subpaths.join(',')}`,
      });
    }
    if (manifest.description !== record.description)
      drift.push({ copy: record.name, detail: 'description differs from catalog' });
    if (!arrayEqual(manifest.keywords ?? [], record.keywords))
      drift.push({ copy: record.name, detail: 'keywords differ from catalog' });
  }

  if (
    !setEqual(
      catalog.map((record) => record.dir),
      publishableDirs,
    )
  ) {
    drift.push({
      copy: 'PACKAGE_CATALOG',
      detail: `catalog/disk publishable directories differ: disk=${publishableDirs.join(',')}`,
    });
  }
  return drift;
}

function catalogDrift(): readonly CatalogDrift[] {
  const manifests = new Map<string, CatalogManifest>();
  for (const record of PACKAGE_CATALOG) {
    const manifest = manifestFor(record);
    if (manifest) manifests.set(record.dir, manifest);
  }
  const dirsOnDisk = readdirSync(resolve(REPO_ROOT, 'packages'), { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => `packages/${entry.name}`)
    .filter((dir) => {
      const path = resolve(REPO_ROOT, dir, 'package.json');
      if (!existsSync(path)) return false;
      const manifest = JSON.parse(readFileSync(path, 'utf8')) as CatalogManifest;
      return manifest.private !== true && manifest.publishConfig != null;
    });
  return validatePackageCatalog(PACKAGE_CATALOG, manifests, dirsOnDisk);
}

export type ProjectionReader = (relativePath: string) => string | undefined;

function readRepoProjection(relativePath: string): string | undefined {
  const path = resolve(REPO_ROOT, relativePath);
  return existsSync(path) ? readFileSync(path, 'utf8') : undefined;
}

/** Validate every generated projection against arbitrary source bytes. */
export function collectGeneratedProjectionDrift(
  readProjection: ProjectionReader = readRepoProjection,
): readonly CatalogDrift[] {
  const drift: CatalogDrift[] = [];
  for (const [relativePath, expected] of renderGeneratedProjections()) {
    if (readProjection(relativePath) !== expected) {
      drift.push({ copy: relativePath, detail: 'stale generated projection; run gen-roster --write' });
    }
  }
  for (const [relativePath, marker, render] of MARKDOWN_PROJECTIONS) {
    const source = readProjection(relativePath);
    if (source == null || applyMarkdownProjection(source, marker, render()) !== source) {
      drift.push({ copy: relativePath, detail: `stale generated ${marker} projection` });
    }
  }

  const indexSource = readProjection(LITESHIP_INDEX_REL);
  const match = indexSource == null ? null : LITESHIP_BLOCK.exec(indexSource);
  if (!match || !match[0].includes(renderLiteshipPackages())) {
    drift.push({ copy: LITESHIP_INDEX_REL, detail: 'stale generated LITESHIP_PACKAGES block' });
  }

  return drift;
}

/** Every mismatch between the catalog, package manifests, and generated projections. */
export function collectRosterDrift(): readonly CatalogDrift[] {
  const drift = [
    ...catalogDrift(),
    ...collectGeneratedProjectionDrift(),
    ...findAuthoredFleetLists(trackedCatalogSources()),
  ];

  const publishJob = publishJobText(readReleaseYaml());
  if (publishJob.includes('@liteship/')) {
    drift.push({ copy: 'release.yml publish job', detail: 'contains an authored @liteship package literal' });
  }
  if (!publishJob.includes(PUBLISH_ROSTER_JSON)) {
    drift.push({ copy: 'release.yml publish job', detail: `does not iterate ${PUBLISH_ROSTER_JSON}` });
  }
  return drift;
}

function emit(): void {
  for (const [relativePath, expected] of renderGeneratedProjections()) {
    process.stdout.write(`# ${relativePath}\n${expected}\n`);
  }
  process.stdout.write(`# ${LITESHIP_INDEX_REL}\n${renderLiteshipPackages()}\n`);
}

function check(): number {
  const drift = collectRosterDrift();
  if (drift.length === 0) {
    process.stdout.write(`gen-roster: ${PACKAGE_CATALOG.length} package records and all projections are current.\n`);
    return 0;
  }
  process.stderr.write('gen-roster: package catalog drift detected\n');
  for (const item of drift) process.stderr.write(`  - ${item.copy}: ${item.detail}\n`);
  return 1;
}

export function main(argv: readonly string[]): number {
  if (argv.includes('--check')) return check();
  if (argv.includes('--write')) return write();
  emit();
  return 0;
}

if (isDirectExecution(import.meta.url)) process.exit(main(process.argv.slice(2)));
