/**
 * The one authored package truth for LiteShip.
 *
 * Every package-level roster, metadata table, smoke specification, publish
 * order, and documentation projection is generated from this catalog. Package
 * manifests remain the independent on-disk oracle checked by gen-roster; they
 * are not a second catalog.
 *
 * Keep this list in dependency order. LiteShip intentionally has exactly 25
 * publishable packages; migration is the `@liteship/compiler/migrate` subpath,
 * never a package of its own.
 *
 * @module
 */

export type PackageLayer =
  'foundation' | 'semantic' | 'runtime' | 'host-adapter' | 'verification' | 'tooling' | 'facade';

export interface PackageCatalogRecord {
  readonly name: string;
  readonly dir: `packages/${string}`;
  readonly publishable: true;
  /** Whether consumers may import package exports as runtime modules. */
  readonly runtimeSurface: 'module' | 'types-only';
  readonly layer: PackageLayer;
  readonly audit: {
    readonly kind: 'core' | 'layered' | 'host-adjacent' | 'standalone';
    readonly allowedInternalImports: readonly string[];
    readonly reason?: string;
  };
  readonly docs: {
    readonly group: 'foundations' | 'hosts' | 'runtime' | 'tooling' | 'prose-only';
    readonly order: number;
    readonly surface: boolean;
  };
  readonly plumbStatus: 'runtime' | 'tooling' | 'deferred';
  readonly plumbReason: string;
  readonly plumbIssue?: string;
  readonly apiSurface: boolean;
  readonly apiSurfaceOrder: number | null;
  readonly typedocEntry: string | null;
  readonly typedocOrder: number | null;
  readonly dependencies: readonly string[];
  readonly capabilities: readonly string[];
  readonly publicSubpaths: readonly string[];
  readonly smokeImports: readonly string[];
  readonly description: string;
  readonly keywords: readonly string[];
}

const pkg = <const Record extends PackageCatalogRecord>(record: Record): Record => record;

export const PACKAGE_CATALOG = [
  pkg({
    name: '@liteship/_spine',
    dir: 'packages/_spine',
    publishable: true,
    runtimeSurface: 'types-only',
    layer: 'foundation',
    audit: { kind: 'standalone', allowedInternalImports: [] },
    docs: { group: 'runtime', order: 9, surface: false },
    plumbStatus: 'tooling',
    plumbReason: 'The published type spine — declarations only, no runtime.',
    apiSurface: false,
    apiSurfaceOrder: null,
    typedocEntry: 'packages/_spine/typedoc-entry.ts',
    typedocOrder: 22,
    dependencies: [],
    capabilities: ['shared-type-declarations'],
    publicSubpaths: ['.'],
    smokeImports: [],
    description:
      'Install-only TypeScript declaration spine for LiteShip: the shared type anchor that `@liteship/core` and `@liteship/scene` reference from their published `.d.ts` — there is nothing to import at runtime.',
    keywords: ['liteship', 'typescript', 'types', 'declarations'],
  }),
  pkg({
    name: '@liteship/error',
    dir: 'packages/error',
    publishable: true,
    runtimeSurface: 'module',
    layer: 'foundation',
    audit: { kind: 'standalone', allowedInternalImports: [] },
    docs: { group: 'foundations', order: 2, surface: true },
    plumbStatus: 'runtime',
    plumbReason:
      'The foundational error algebra — every live failure path (runtime, edge, worker) throws/returns a @liteship/error variant. Zero-dep; consumed by every package.',
    apiSurface: true,
    apiSurfaceOrder: 0,
    typedocEntry: 'packages/error/src/index.ts',
    typedocOrder: 0,
    dependencies: [],
    capabilities: ['tagged-error-algebra', 'diagnostic-codes'],
    publicSubpaths: ['.'],
    smokeImports: ['@liteship/error'],
    description:
      'The one error algebra for LiteShip: build tagged error values that work as thrown Errors and as errors-as-values (a Result err-arm), and compose your own variants on top with zero dependencies.',
    keywords: ['liteship', 'error-handling', 'tagged-union', 'typescript'],
  }),
  pkg({
    name: '@liteship/canonical',
    dir: 'packages/canonical',
    publishable: true,
    runtimeSurface: 'module',
    layer: 'foundation',
    audit: { kind: 'standalone', allowedInternalImports: [] },
    docs: { group: 'foundations', order: 1, surface: true },
    plumbStatus: 'runtime',
    plumbReason: 'Canonical CBOR/FNV identity — consumed by core on the live path.',
    apiSurface: true,
    apiSurfaceOrder: 2,
    typedocEntry: 'packages/canonical/src/index.ts',
    typedocOrder: 1,
    dependencies: ['@liteship/error'],
    capabilities: ['canonical-cbor', 'content-digests'],
    publicSubpaths: ['.'],
    smokeImports: ['@liteship/canonical'],
    description:
      'The content-addressing kernel for LiteShip: canonical CBOR encoding and stable digests so the same definition always hashes to the same address.',
    keywords: ['liteship', 'content-addressing', 'cbor', 'hashing', 'typescript'],
  }),
  pkg({
    name: '@liteship/core',
    dir: 'packages/core',
    publishable: true,
    runtimeSurface: 'module',
    layer: 'semantic',
    audit: {
      kind: 'core',
      allowedInternalImports: ['@liteship/_spine', '@liteship/canonical'],
      reason: '_spine owns shared public types; canonical owns the byte kernel core re-exports.',
    },
    docs: { group: 'foundations', order: 0, surface: true },
    plumbStatus: 'runtime',
    plumbReason: 'The kernel: signals, boundaries, evaluator, content-addressing, graph IR.',
    apiSurface: true,
    apiSurfaceOrder: 4,
    typedocEntry: 'packages/core/src/index.ts',
    typedocOrder: 3,
    dependencies: ['@liteship/_spine', '@liteship/canonical', '@liteship/error'],
    capabilities: ['adaptive-authoring', 'reactive-runtime', 'motion', 'document-graph', 'evidence'],
    publicSubpaths: [
      '.',
      './authoring',
      './reactive',
      './motion',
      './graph',
      './evidence',
      './schema',
      './media',
      './clock',
      './wasm',
      './testing',
      './harness',
      './simulation',
      './fs-walk',
    ],
    smokeImports: ['@liteship/core', '@liteship/core/testing', '@liteship/core/harness'],
    description:
      'The heart of LiteShip: define UI boundaries, tokens, themes, and signals once as a content-addressed graph, then drive the engine that keeps every rendered output in sync.',
    keywords: ['liteship', 'adaptive-rendering', 'constraint-based', 'ui-framework', 'typescript'],
  }),
  pkg({
    name: '@liteship/genui',
    dir: 'packages/genui',
    publishable: true,
    runtimeSurface: 'module',
    layer: 'semantic',
    audit: { kind: 'layered', allowedInternalImports: ['@liteship/canonical', '@liteship/_spine'] },
    docs: { group: 'foundations', order: 3, surface: true },
    plumbStatus: 'runtime',
    plumbReason: 'GenUI render pipeline — consumed by the astro llm runtime.',
    apiSurface: true,
    apiSurfaceOrder: 3,
    typedocEntry: 'packages/genui/src/index.ts',
    typedocOrder: 2,
    dependencies: ['@liteship/_spine', '@liteship/canonical', '@liteship/error'],
    capabilities: ['trusted-component-catalog', 'generated-ui-validation'],
    publicSubpaths: ['.'],
    smokeImports: ['@liteship/genui'],
    description:
      "Render AI-generated UI safely in LiteShip: validate a model's proposed component tree against a host-owned catalog and draw only trusted, whitelisted components.",
    keywords: ['liteship', 'generative-ui', 'ai-safety', 'component-catalog', 'typescript'],
  }),
  pkg({
    name: '@liteship/quantizer',
    dir: 'packages/quantizer',
    publishable: true,
    runtimeSurface: 'module',
    layer: 'semantic',
    audit: {
      kind: 'layered',
      allowedInternalImports: ['@liteship/core'],
    },
    docs: { group: 'foundations', order: 4, surface: true },
    plumbStatus: 'runtime',
    plumbReason: 'The output evaluator — consumed on the cast path.',
    apiSurface: true,
    apiSurfaceOrder: 5,
    typedocEntry: 'packages/quantizer/src/index.ts',
    typedocOrder: 4,
    dependencies: ['@liteship/core', '@liteship/error'],
    capabilities: ['signal-quantization', 'state-transition-runtime'],
    publicSubpaths: ['.', './testing'],
    smokeImports: ['@liteship/quantizer', '@liteship/quantizer/testing'],
    description:
      'Turn continuous signals into a few named UI states for LiteShip: evaluate boundaries, animate the transitions between states, and gate motion by device tier.',
    keywords: ['liteship', 'adaptive-rendering', 'state-machine', 'boundary', 'typescript'],
  }),
  pkg({
    name: '@liteship/compiler',
    dir: 'packages/compiler',
    publishable: true,
    runtimeSurface: 'module',
    layer: 'semantic',
    audit: {
      kind: 'layered',
      allowedInternalImports: ['@liteship/core'],
      reason: 'Compiler and quantizer are siblings; compiler deliberately imports core only.',
    },
    docs: { group: 'foundations', order: 5, surface: true },
    plumbStatus: 'runtime',
    plumbReason: 'CSS/ARIA/GLSL/WGSL dispatch arms — consumed via the boundary manifest.',
    apiSurface: true,
    apiSurfaceOrder: 6,
    typedocEntry: 'packages/compiler/src/index.ts',
    typedocOrder: 5,
    dependencies: ['@liteship/core', '@liteship/error'],
    capabilities: ['multi-target-compilation', 'source-parsing', 'migration-adapters'],
    publicSubpaths: ['.', './parse', './migrate'],
    smokeImports: ['@liteship/compiler'],
    description:
      'Compile one LiteShip boundary definition into many outputs at once — CSS, GLSL, WGSL, ARIA, AI descriptions, and Tailwind — so every target stays in sync.',
    keywords: ['liteship', 'css', 'shaders', 'aria', 'compiler', 'typescript'],
  }),
  pkg({
    name: '@liteship/web',
    dir: 'packages/web',
    publishable: true,
    runtimeSurface: 'module',
    layer: 'runtime',
    audit: { kind: 'layered', allowedInternalImports: ['@liteship/core', '@liteship/genui', '@liteship/canonical'] },
    docs: { group: 'runtime', order: 0, surface: true },
    plumbStatus: 'runtime',
    plumbReason: 'Browser-host security/morph/audio primitives consumed by the runtime.',
    apiSurface: true,
    apiSurfaceOrder: 7,
    typedocEntry: 'packages/web/src/index.ts',
    typedocOrder: 6,
    dependencies: ['@liteship/canonical', '@liteship/core', '@liteship/error', '@liteship/genui'],
    capabilities: ['dom-runtime', 'streaming', 'morphing'],
    publicSubpaths: ['.', './lite'],
    smokeImports: ['@liteship/web', '@liteship/web/lite'],
    description:
      'The browser runtime for LiteShip: apply CSS, streamed HTML, worker output, and LLM chunks to a live DOM with focus- and scroll-preserving morphing.',
    keywords: ['liteship', 'dom', 'browser-runtime', 'streaming', 'typescript'],
  }),
  pkg({
    name: '@liteship/detect',
    dir: 'packages/detect',
    publishable: true,
    runtimeSurface: 'module',
    layer: 'runtime',
    audit: { kind: 'layered', allowedInternalImports: ['@liteship/core'] },
    docs: { group: 'runtime', order: 1, surface: true },
    plumbStatus: 'runtime',
    plumbReason: 'Capability detection — consumed by the runtime + edge.',
    apiSurface: true,
    apiSurfaceOrder: 8,
    typedocEntry: 'packages/detect/src/index.ts',
    typedocOrder: 8,
    dependencies: ['@liteship/core'],
    capabilities: ['device-capability-detection'],
    publicSubpaths: ['.'],
    smokeImports: ['@liteship/detect'],
    description:
      'Detect device capabilities for LiteShip: probe GPU tier, CPU, memory, motion preference, and network, then map them to the tiers that select which UI state renders.',
    keywords: ['liteship', 'device-detection', 'capability-probe', 'gpu-tier', 'typescript'],
  }),
  pkg({
    name: '@liteship/edge',
    dir: 'packages/edge',
    publishable: true,
    runtimeSurface: 'module',
    layer: 'runtime',
    audit: { kind: 'host-adjacent', allowedInternalImports: ['@liteship/core', '@liteship/detect'] },
    docs: { group: 'hosts', order: 2, surface: true },
    plumbStatus: 'runtime',
    plumbReason: 'Edge tier detection + boundary cache — a live host surface.',
    apiSurface: true,
    apiSurfaceOrder: 9,
    typedocEntry: 'packages/edge/src/index.ts',
    typedocOrder: 9,
    dependencies: ['@liteship/core', '@liteship/detect', '@liteship/error'],
    capabilities: ['edge-tier-selection', 'boundary-cache'],
    publicSubpaths: ['.'],
    smokeImports: ['@liteship/edge'],
    description:
      'Choose the right UI state at the CDN edge for LiteShip: read Client Hints into a device tier, serve a content-addressed boundary cache, and compile the theme for first paint.',
    keywords: ['liteship', 'edge', 'cdn', 'client-hints', 'typescript'],
  }),
  pkg({
    name: '@liteship/vite',
    dir: 'packages/vite',
    publishable: true,
    runtimeSurface: 'module',
    layer: 'host-adapter',
    audit: {
      kind: 'host-adjacent',
      allowedInternalImports: ['@liteship/core', '@liteship/compiler', '@liteship/edge', '@liteship/web'],
      reason: 'edge owns the boundary-manifest handoff; web owns the shared wire-event dispatcher.',
    },
    docs: { group: 'hosts', order: 0, surface: true },
    plumbStatus: 'runtime',
    plumbReason: 'Build-time @quantize compile + the dev cast — part of the shipped pipeline.',
    apiSurface: true,
    apiSurfaceOrder: 11,
    typedocEntry: 'packages/vite/src/index.ts',
    typedocOrder: 10,
    dependencies: ['@liteship/core', '@liteship/compiler', '@liteship/edge', '@liteship/error', '@liteship/web'],
    capabilities: ['vite-integration', 'css-directive-compilation', 'hmr'],
    publicSubpaths: ['.', './html-transform', './virtual'],
    smokeImports: ['@liteship/vite', '@liteship/vite/html-transform'],
    description:
      'The Vite plugin for LiteShip: compile `@token`, `@theme`, `@style`, and `@quantize` blocks into native CSS and hot-reload boundary definitions as you edit.',
    keywords: ['liteship', 'vite-plugin', 'css', 'hmr', 'typescript'],
  }),
  pkg({
    name: '@liteship/worker',
    dir: 'packages/worker',
    publishable: true,
    runtimeSurface: 'module',
    layer: 'runtime',
    audit: { kind: 'host-adjacent', allowedInternalImports: ['@liteship/core'] },
    docs: { group: 'runtime', order: 2, surface: true },
    plumbStatus: 'runtime',
    plumbReason: 'Off-thread compositor — consumed by the runtime.',
    apiSurface: true,
    apiSurfaceOrder: 10,
    typedocEntry: 'packages/worker/src/index.ts',
    typedocOrder: 7,
    dependencies: ['@liteship/core', '@liteship/error'],
    capabilities: ['worker-runtime', 'offscreen-rendering', 'spsc-transport'],
    publicSubpaths: ['.'],
    smokeImports: ['@liteship/worker'],
    description:
      "Move LiteShip's heavy work off the main thread: compositor and render workers plus a lock-free ring buffer that stream state and frames without janking the UI.",
    keywords: ['liteship', 'web-worker', 'off-main-thread', 'offscreen-canvas', 'typescript'],
  }),
  pkg({
    name: '@liteship/remotion',
    dir: 'packages/remotion',
    publishable: true,
    runtimeSurface: 'module',
    layer: 'runtime',
    audit: { kind: 'standalone', allowedInternalImports: ['@liteship/core'] },
    docs: { group: 'runtime', order: 3, surface: true },
    plumbStatus: 'tooling',
    plumbReason: 'Remotion offline video integration — build-time render, not live runtime.',
    apiSurface: true,
    apiSurfaceOrder: 15,
    typedocEntry: 'packages/remotion/src/index.ts',
    typedocOrder: 13,
    dependencies: ['@liteship/core'],
    capabilities: ['remotion-integration', 'video-frame-runtime'],
    publicSubpaths: ['.'],
    smokeImports: ['@liteship/remotion'],
    description:
      'Use LiteShip inside Remotion: React hooks and composition helpers that drive video frames and shader surfaces from the same boundary state used everywhere else.',
    keywords: ['liteship', 'remotion', 'video', 'react', 'typescript'],
  }),
  pkg({
    name: '@liteship/scene',
    dir: 'packages/scene',
    publishable: true,
    runtimeSurface: 'module',
    layer: 'runtime',
    audit: { kind: 'layered', allowedInternalImports: ['@liteship/core', '@liteship/_spine'] },
    docs: { group: 'runtime', order: 4, surface: true },
    plumbStatus: 'runtime',
    plumbReason:
      'Plumbed live in 0.4.0: @liteship/astro imports it via the scene→live bridge (scene-bridge.ts) and the SVG directive (svg.ts → applySvgAttrs).',
    apiSurface: true,
    apiSurfaceOrder: 16,
    typedocEntry: 'packages/scene/src/index.ts',
    typedocOrder: 14,
    dependencies: ['@liteship/_spine', '@liteship/core', '@liteship/error'],
    capabilities: ['scene-authoring', 'timeline-runtime'],
    publicSubpaths: ['.', './dev'],
    smokeImports: ['@liteship/scene', '@liteship/scene/dev'],
    description:
      'Author video timelines for LiteShip: a typed scene and track model built on the entity-component substrate in `@liteship/core`.',
    keywords: ['liteship', 'scene', 'timeline', 'video', 'typescript'],
  }),
  pkg({
    name: '@liteship/astro',
    dir: 'packages/astro',
    publishable: true,
    runtimeSurface: 'module',
    layer: 'host-adapter',
    audit: {
      kind: 'host-adjacent',
      allowedInternalImports: [
        '@liteship/core',
        '@liteship/vite',
        '@liteship/detect',
        '@liteship/edge',
        '@liteship/web',
        '@liteship/worker',
        '@liteship/genui',
        '@liteship/scene',
        '@liteship/canonical',
      ],
      reason: 'Astro owns the host bridge; scene and canonical edges serve the live SVG and docs-byte paths.',
    },
    docs: { group: 'hosts', order: 1, surface: true },
    plumbStatus: 'runtime',
    plumbReason: 'The Astro integration + client runtime — the primary live cast surface.',
    apiSurface: true,
    apiSurfaceOrder: 12,
    typedocEntry: 'packages/astro/src/index.ts',
    typedocOrder: 11,
    dependencies: [
      '@liteship/core',
      '@liteship/canonical',
      '@liteship/error',
      '@liteship/vite',
      '@liteship/detect',
      '@liteship/edge',
      '@liteship/genui',
      '@liteship/scene',
      '@liteship/web',
      '@liteship/worker',
    ],
    capabilities: ['astro-integration', 'adaptive-directive', 'server-tier-resolution'],
    publicSubpaths: [
      '.',
      './client-directives/adaptive',
      './client-directives/stream',
      './client-directives/llm',
      './client-directives/worker',
      './client-directives/gpu',
      './client-directives/wasm',
      './client-directives/graph',
      './client-directives/motion',
      './client-directives/svg',
      './middleware',
      './middleware-entry',
      './fetch-layer',
      './runtime',
      './runtime/inspector-toolbar-app',
      './Adaptive',
      './Adaptive.astro',
    ],
    smokeImports: [
      '@liteship/astro',
      '@liteship/astro/client-directives/adaptive',
      '@liteship/astro/client-directives/stream',
      '@liteship/astro/client-directives/llm',
      '@liteship/astro/client-directives/worker',
      '@liteship/astro/client-directives/gpu',
      '@liteship/astro/client-directives/wasm',
      '@liteship/astro/middleware',
      '@liteship/astro/fetch-layer',
      '@liteship/astro/runtime',
    ],
    description:
      'The Astro integration for LiteShip: render adaptive UI as islands with the `client:adaptive` directive and resolve device tiers on the server for first paint.',
    keywords: ['liteship', 'astro', 'integration', 'islands', 'typescript'],
  }),
  pkg({
    name: '@liteship/cloudflare',
    dir: 'packages/cloudflare',
    publishable: true,
    runtimeSurface: 'module',
    layer: 'host-adapter',
    audit: { kind: 'host-adjacent', allowedInternalImports: ['@liteship/core', '@liteship/edge', '@liteship/astro'] },
    docs: { group: 'hosts', order: 3, surface: true },
    plumbStatus: 'runtime',
    plumbReason: 'Cloudflare host adapter — a live edge surface.',
    apiSurface: true,
    apiSurfaceOrder: 14,
    typedocEntry: 'packages/cloudflare/src/index.ts',
    typedocOrder: 12,
    dependencies: ['@liteship/core', '@liteship/edge', '@liteship/astro', '@liteship/error'],
    capabilities: ['cloudflare-workers-adapter', 'kv-boundary-cache'],
    publicSubpaths: ['.', './testing', './cache-provider'],
    smokeImports: ['@liteship/cloudflare', '@liteship/cloudflare/testing', '@liteship/cloudflare/cache-provider'],
    description:
      'Run LiteShip on Cloudflare Workers: a site adapter with a KV-backed edge cache and the Astro middleware glue that caches boundaries at the edge.',
    keywords: ['liteship', 'cloudflare', 'workers', 'edge', 'typescript'],
  }),
  pkg({
    name: '@liteship/stage',
    dir: 'packages/stage',
    publishable: true,
    runtimeSurface: 'module',
    layer: 'runtime',
    audit: {
      kind: 'host-adjacent',
      allowedInternalImports: ['@liteship/core', '@liteship/compiler', '@liteship/astro', '@liteship/web'],
    },
    docs: { group: 'runtime', order: 6, surface: true },
    plumbStatus: 'tooling',
    plumbReason:
      'Dual-export proof (graph→page+video). 0.4.0 (item F) filled the headless node ffmpeg encode, so it is a complete BUILD/CI proof tool — not a live-site runtime surface.',
    apiSurface: true,
    apiSurfaceOrder: 13,
    typedocEntry: 'packages/stage/src/index.ts',
    typedocOrder: 15,
    dependencies: ['@liteship/astro', '@liteship/compiler', '@liteship/core', '@liteship/error', '@liteship/web'],
    capabilities: ['dual-export', 'ffmpeg-rendering'],
    publicSubpaths: ['.', './ffmpeg'],
    smokeImports: ['@liteship/stage', '@liteship/stage/ffmpeg'],
    description:
      'Export one LiteShip document graph to many carriers: prove a single source renders to both a static Astro page and a video, joined under one receipt.',
    keywords: ['liteship', 'dual-export', 'video', 'static-site', 'typescript'],
  }),
  pkg({
    name: '@liteship/assets',
    dir: 'packages/assets',
    publishable: true,
    runtimeSurface: 'module',
    layer: 'runtime',
    audit: { kind: 'layered', allowedInternalImports: ['@liteship/core', '@liteship/_spine'] },
    docs: { group: 'runtime', order: 5, surface: true },
    plumbStatus: 'runtime',
    plumbReason: 'Asset/audio analysis consumed by the build + scene pipeline.',
    apiSurface: true,
    apiSurfaceOrder: 17,
    typedocEntry: 'packages/assets/src/index.ts',
    typedocOrder: 16,
    dependencies: ['@liteship/_spine', '@liteship/core', '@liteship/error'],
    capabilities: ['asset-declarations', 'media-analysis'],
    publicSubpaths: ['.'],
    smokeImports: ['@liteship/assets'],
    description:
      'Manage media assets for LiteShip: declare audio, video, and image assets and read cached analysis such as waveforms, beat markers, and onsets.',
    keywords: ['liteship', 'assets', 'audio', 'waveform', 'typescript'],
  }),
  pkg({
    name: '@liteship/gauntlet',
    dir: 'packages/gauntlet',
    publishable: true,
    runtimeSurface: 'module',
    layer: 'verification',
    audit: { kind: 'standalone', allowedInternalImports: [] },
    docs: { group: 'tooling', order: 2, surface: true },
    plumbStatus: 'tooling',
    plumbReason: 'The rigor engine — gates/findings/assurance/authority-ratchet; build/CI tooling, not site runtime.',
    apiSurface: true,
    apiSurfaceOrder: 1,
    typedocEntry: 'packages/gauntlet/src/index.ts',
    typedocOrder: 18,
    dependencies: ['@liteship/error'],
    capabilities: ['quality-gates', 'authority-ratchet'],
    publicSubpaths: ['.'],
    smokeImports: ['@liteship/gauntlet'],
    description:
      "The rigor engine behind LiteShip's release gates: define quality gates that report findings and earn blocking power only by proving themselves against their own fixtures.",
    keywords: ['liteship', 'quality-gate', 'fitness-function', 'static-analysis', 'typescript'],
  }),
  pkg({
    name: '@liteship/audit',
    dir: 'packages/audit',
    publishable: true,
    runtimeSurface: 'module',
    layer: 'verification',
    audit: { kind: 'standalone', allowedInternalImports: ['@liteship/canonical', '@liteship/gauntlet'] },
    docs: { group: 'tooling', order: 1, surface: true },
    plumbStatus: 'tooling',
    plumbReason: 'The audit engine — build/CI tooling.',
    apiSurface: true,
    apiSurfaceOrder: 18,
    typedocEntry: 'packages/audit/src/index.ts',
    typedocOrder: 17,
    dependencies: ['@liteship/canonical', '@liteship/error', '@liteship/gauntlet'],
    capabilities: ['repository-audit', 'consumer-audit', 'fact-building'],
    publicSubpaths: ['.'],
    smokeImports: ['@liteship/audit'],
    description:
      "Audit a LiteShip project's structure, integrity, and public surface: a downstream-installable engine that builds a model of the repository and runs configurable checks over it.",
    keywords: ['liteship', 'audit', 'static-analysis', 'code-quality', 'typescript'],
  }),
  pkg({
    name: '@liteship/command',
    dir: 'packages/command',
    publishable: true,
    runtimeSurface: 'module',
    layer: 'tooling',
    audit: {
      kind: 'layered',
      allowedInternalImports: ['@liteship/core', '@liteship/assets', '@liteship/gauntlet', '@liteship/canonical'],
      reason: 'Command owns shared host execution; assets, gauntlet, and canonical are deliberate host seams.',
    },
    docs: { group: 'tooling', order: 0, surface: true },
    plumbStatus: 'tooling',
    plumbReason: 'CLI command catalog/host — tooling.',
    apiSurface: true,
    apiSurfaceOrder: 19,
    typedocEntry: 'packages/command/src/index.ts',
    typedocOrder: 19,
    dependencies: [
      '@liteship/core',
      '@liteship/assets',
      '@liteship/canonical',
      '@liteship/error',
      '@liteship/gauntlet',
    ],
    capabilities: ['command-catalog', 'check-registry', 'context-map'],
    publicSubpaths: ['.', './host', './host-browser', './invariants'],
    smokeImports: ['@liteship/command', '@liteship/command/host'],
    description:
      "The shared command registry behind LiteShip's tooling: one source of command definitions that both the `liteship` CLI and the MCP server project from.",
    keywords: ['liteship', 'cli', 'mcp', 'command-registry', 'typescript'],
  }),
  pkg({
    name: '@liteship/cli',
    dir: 'packages/cli',
    publishable: true,
    runtimeSurface: 'module',
    layer: 'tooling',
    audit: {
      kind: 'host-adjacent',
      allowedInternalImports: [
        '@liteship/core',
        '@liteship/command',
        '@liteship/assets',
        '@liteship/audit',
        '@liteship/gauntlet',
        '@liteship/edge',
        '@liteship/canonical',
      ],
      reason: 'CLI is the terminal host that injects audit/gauntlet facts and deployed edge expectations.',
    },
    docs: { group: 'runtime', order: 7, surface: true },
    plumbStatus: 'tooling',
    plumbReason: 'The `liteship` CLI — a developer tool, not a runtime surface.',
    apiSurface: true,
    apiSurfaceOrder: 20,
    typedocEntry: 'packages/cli/src/index.ts',
    typedocOrder: 20,
    dependencies: [
      '@liteship/core',
      '@liteship/canonical',
      '@liteship/command',
      '@liteship/scene',
      '@liteship/assets',
      '@liteship/audit',
      '@liteship/edge',
      '@liteship/gauntlet',
      '@liteship/error',
    ],
    capabilities: ['command-line-interface', 'project-doctor', 'package-smoke'],
    publicSubpaths: ['.'],
    smokeImports: ['@liteship/cli'],
    description:
      'The `liteship` command-line tool for LiteShip: JSON-in, JSON-out verbs built for AI agents, with a human-friendly terminal mode.',
    keywords: ['liteship', 'cli', 'command-line', 'json', 'typescript'],
  }),
  pkg({
    name: '@liteship/mcp-server',
    dir: 'packages/mcp-server',
    publishable: true,
    runtimeSurface: 'module',
    layer: 'tooling',
    audit: {
      kind: 'host-adjacent',
      allowedInternalImports: [
        '@liteship/core',
        '@liteship/command',
        '@liteship/compiler',
        '@liteship/genui',
        '@liteship/web',
      ],
      reason: 'MCP projects the command catalog and compiler/UI renderers without importing CLI.',
    },
    docs: { group: 'runtime', order: 8, surface: true },
    plumbStatus: 'tooling',
    plumbReason: 'MCP server — a developer-assistant surface, not site runtime.',
    apiSurface: true,
    apiSurfaceOrder: 21,
    typedocEntry: 'packages/mcp-server/src/index.ts',
    typedocOrder: 21,
    dependencies: [
      '@liteship/core',
      '@liteship/error',
      '@liteship/command',
      '@liteship/compiler',
      '@liteship/genui',
      '@liteship/web',
    ],
    capabilities: ['mcp-server', 'agent-tools'],
    publicSubpaths: ['.'],
    smokeImports: ['@liteship/mcp-server'],
    description:
      'The Model Context Protocol server for LiteShip: exposes the `liteship` commands and capsule catalog as MCP tools that AI assistants can call.',
    keywords: ['liteship', 'mcp', 'model-context-protocol', 'ai-tooling', 'typescript'],
  }),
  pkg({
    name: 'create-liteship',
    dir: 'packages/create-liteship',
    publishable: true,
    runtimeSurface: 'module',
    layer: 'tooling',
    audit: {
      kind: 'standalone',
      allowedInternalImports: ['@liteship/core'],
      reason: 'The generated scaffold imports core and the core/fs-walk public subpath.',
    },
    docs: { group: 'prose-only', order: 1, surface: true },
    plumbStatus: 'tooling',
    plumbReason: 'The scaffolder — a one-shot CLI, not runtime.',
    apiSurface: false,
    apiSurfaceOrder: null,
    typedocEntry: null,
    typedocOrder: null,
    dependencies: ['@liteship/core', '@liteship/error'],
    capabilities: ['project-scaffolding'],
    publicSubpaths: ['.'],
    smokeImports: ['create-liteship'],
    description:
      'Scaffold a new LiteShip project: run `npm create liteship` to get a minimal Astro app wired to the framework in one step.',
    keywords: ['create-liteship', 'liteship', 'scaffold', 'astro', 'typescript'],
  }),
  pkg({
    name: 'liteship',
    dir: 'packages/liteship',
    publishable: true,
    runtimeSurface: 'module',
    layer: 'facade',
    audit: {
      kind: 'host-adjacent',
      allowedInternalImports: [
        '@liteship/core',
        '@liteship/quantizer',
        '@liteship/gauntlet',
        '@liteship/compiler',
        '@liteship/web',
        '@liteship/astro',
        '@liteship/vite',
      ],
      reason: 'The facade is a dependency sink whose explicit subpaths re-export these semantic and host owners.',
    },
    docs: { group: 'prose-only', order: 0, surface: true },
    plumbStatus: 'tooling',
    plumbReason: 'The umbrella meta-package — re-exports, no runtime of its own.',
    apiSurface: false,
    apiSurfaceOrder: null,
    typedocEntry: null,
    typedocOrder: null,
    dependencies: [
      '@liteship/_spine',
      '@liteship/assets',
      '@liteship/astro',
      '@liteship/audit',
      '@liteship/canonical',
      '@liteship/cli',
      '@liteship/cloudflare',
      '@liteship/command',
      '@liteship/compiler',
      '@liteship/core',
      '@liteship/detect',
      '@liteship/edge',
      '@liteship/error',
      '@liteship/gauntlet',
      '@liteship/genui',
      '@liteship/mcp-server',
      '@liteship/quantizer',
      '@liteship/remotion',
      '@liteship/scene',
      '@liteship/stage',
      '@liteship/vite',
      '@liteship/web',
      '@liteship/worker',
    ],
    capabilities: ['curated-facade', 'host-subpaths', 'one-install'],
    publicSubpaths: [
      '.',
      './schema',
      './reactive',
      './motion',
      './graph',
      './media',
      './evidence',
      './compiler',
      './runtime',
      './astro',
      './vite',
      './testing',
      './migrate',
    ],
    smokeImports: ['liteship'],
    description:
      'The curated public facade for LiteShip: one dependency and one import path over the whole `@liteship/*` adaptive rendering stack, with domain subpaths like `liteship/astro` for deeper surfaces.',
    keywords: ['liteship', 'adaptive-rendering', 'framework', 'meta-package', 'typescript'],
  }),
] as const satisfies readonly PackageCatalogRecord[];

export type PackageCatalogName = (typeof PACKAGE_CATALOG)[number]['name'];
