/**
 * journey-installed-add — prove the published CLI carries and copies its minimal
 * real scaffold fragments from an unrelated consumer directory.
 *
 * The source of truth remains `packages/create-liteship/templates/default`; the
 * CLI tarball carries a generated byte-identical projection. This journey uses
 * only the executable linked by the packed `liteship` install, first checking
 * list discovery and then copying `template default`. The copied file set and
 * every byte must match the canonical authored template.
 *
 * @module
 */

import { readFileSync } from 'node:fs';
import { join, relative, resolve } from 'node:path';
import {
  findFiles,
  installConsumer,
  journeyAssert,
  parseReceipt,
  removeDir,
  rewriteConsumerToTarballs,
  runInstalledLiteshipCli,
  scaffoldConsumer,
  REPO_ROOT,
  type JourneyResult,
  type PackedWorkspace,
} from './harness.js';

const CANONICAL_TEMPLATE = resolve(REPO_ROOT, 'packages', 'create-liteship', 'templates', 'default');

function relativeFiles(dir: string): readonly string[] {
  return findFiles(dir, '')
    .map((file) => relative(dir, file).replaceAll('\\', '/'))
    .sort();
}

function assertCanonicalCopy(copiedDir: string): number {
  const expected = relativeFiles(CANONICAL_TEMPLATE);
  const actual = relativeFiles(copiedDir);
  journeyAssert(
    JSON.stringify(actual) === JSON.stringify(expected),
    `installed add copied a different file set\n  expected: ${expected.join(', ')}\n  actual:   ${actual.join(', ')}`,
  );
  for (const path of expected) {
    const canonical = readFileSync(resolve(CANONICAL_TEMPLATE, path));
    const copied = readFileSync(resolve(copiedDir, path));
    journeyAssert(copied.equals(canonical), `installed add changed bytes for ${path}`);
  }
  return expected.length;
}

export async function journeyInstalledAdd(packed: PackedWorkspace): Promise<JourneyResult> {
  const name = 'journey-installed-add';
  let appDir: string | undefined;
  try {
    appDir = scaffoldConsumer();
    rewriteConsumerToTarballs(appDir, packed);

    const install = await installConsumer(appDir);
    if (install.code !== 0) {
      throw new Error(`pnpm install failed (exit ${install.code}):\n${(install.stdout + install.stderr).slice(-1200)}`);
    }

    // `appDir` is a fresh os.tmpdir consumer outside the repository. Executable
    // and fragment resolution therefore come only from its packed install.
    const listed = await runInstalledLiteshipCli(['add'], appDir);
    journeyAssert(
      listed.code === 0,
      `installed liteship add list failed (exit ${listed.code}):\n${(listed.stderr || listed.stdout).slice(-1200)}`,
    );
    const listReceipt = parseReceipt(listed.stdout);
    const fragments = listReceipt['fragments'] as { readonly template?: readonly string[] } | undefined;
    journeyAssert(
      fragments?.template?.includes('default') === true,
      'installed liteship add did not list packaged template fragment "default"',
    );

    const copied = await runInstalledLiteshipCli(['add', 'template', 'default'], appDir);
    journeyAssert(
      copied.code === 0,
      `installed liteship add template default failed (exit ${copied.code}):\n${(copied.stderr || copied.stdout).slice(-1200)}`,
    );
    const copyReceipt = parseReceipt(copied.stdout);
    journeyAssert(copyReceipt['status'] === 'ok', `add receipt status was ${String(copyReceipt['status'])}, not ok`);
    journeyAssert(copyReceipt['command'] === 'add', `add receipt command was ${String(copyReceipt['command'])}`);
    journeyAssert(copyReceipt['kind'] === 'template', `add receipt kind was ${String(copyReceipt['kind'])}`);
    journeyAssert(copyReceipt['name'] === 'default', `add receipt name was ${String(copyReceipt['name'])}`);
    journeyAssert(copyReceipt['dest'] === 'default', `add receipt dest was ${String(copyReceipt['dest'])}`);

    const fileCount = assertCanonicalCopy(join(appDir, 'default'));
    journeyAssert(copyReceipt['fileCount'] === fileCount, `add receipt fileCount was not ${fileCount}`);

    return {
      name,
      status: 'pass',
      detail: `packed installed CLI listed and copied template/default; ${fileCount} files byte-match the canonical create-liteship template`,
      notes: [],
    };
  } catch (error) {
    return { name, status: 'fail', detail: error instanceof Error ? error.message : String(error), notes: [] };
  } finally {
    removeDir(appDir === undefined ? undefined : join(appDir, '..'));
  }
}
