/**
 * journey-installed-add — prove the published CLI carries and copies its minimal
 * real scaffold fragments from an unrelated consumer directory.
 *
 * The source of truth remains `packages/create-liteship/templates/default`; the
 * CLI tarball carries a generated byte-identical projection. This journey uses
 * only the executable linked by the packed `liteship` install, first checking
 * list discovery and then copying `template default`. The copied file set and
 * every byte must match the canonical authored template.
 *
 * @module
 */

import { readFileSync } from 'node:fs';
import { join, relative, resolve } from 'node:path';
import { restoredTemplateName } from '../../packages/create-liteship/src/template-renames.js';
import {
  findFiles,
  installConsumer,
  journeyAssert,
  parseReceipt,
  removeDir,
  rewriteConsumerToTarballs,
  runInstalledLiteshipCli,
  scaffoldConsumer,
  REPO_ROOT,
  type ConsumerPackageManager,
  type JourneyResult,
  type PackedWorkspace,
} from './harness.js';

const CANONICAL_TEMPLATE = resolve(REPO_ROOT, 'packages', 'create-liteship', 'templates', 'default');
const MANAGERS: readonly ConsumerPackageManager[] = ['npm', 'pnpm'];

function relativeFiles(dir: string): readonly string[] {
  return findFiles(dir, '')
    .map((file) => relative(dir, file).replaceAll('\\', '/'))
    .sort();
}

function restoredRelativePath(path: string): string {
  const [head, ...tail] = path.split('/');
  return [restoredTemplateName(head!), ...tail].join('/');
}

function assertCanonicalCopy(copiedDir: string): number {
  const canonical = relativeFiles(CANONICAL_TEMPLATE);
  const expected = canonical.map(restoredRelativePath).sort();
  const actual = relativeFiles(copiedDir);
  journeyAssert(
    JSON.stringify(actual) === JSON.stringify(expected),
    `installed add copied a different file set\n  expected: ${expected.join(', ')}\n  actual:   ${actual.join(', ')}`,
  );
  for (const sourcePath of canonical) {
    const consumerPath = restoredRelativePath(sourcePath);
    const sourceBytes = readFileSync(resolve(CANONICAL_TEMPLATE, sourcePath));
    const copied = readFileSync(resolve(copiedDir, consumerPath));
    journeyAssert(copied.equals(sourceBytes), `installed add changed bytes for ${sourcePath} -> ${consumerPath}`);
  }
  journeyAssert(!actual.includes('gitignore'), 'installed add retained the package-safe gitignore placeholder');
  return expected.length;
}

export async function journeyInstalledAdd(packed: PackedWorkspace): Promise<JourneyResult> {
  const name = 'journey-installed-add';
  try {
    const copiedCounts = new Map<ConsumerPackageManager, number>();
    for (const manager of MANAGERS) {
      const appDir = scaffoldConsumer();
      try {
        rewriteConsumerToTarballs(appDir, packed, { packageManager: manager });
        const install = await installConsumer(appDir, manager);
        if (install.code !== 0) {
          throw new Error(
            `${manager} install failed (exit ${install.code}):\n${(install.stdout + install.stderr).slice(-1200)}`,
          );
        }

        // Each appDir is an unrelated os.tmpdir consumer. Executable and
        // fragment resolution therefore come only from its packed install.
        const listed = await runInstalledLiteshipCli(['add'], appDir, manager);
        journeyAssert(
          listed.code === 0,
          `${manager} installed add list failed (exit ${listed.code}):\n${(listed.stderr || listed.stdout).slice(-1200)}`,
        );
        const listReceipt = parseReceipt(listed.stdout);
        const fragments = listReceipt['fragments'] as { readonly template?: readonly string[] } | undefined;
        journeyAssert(
          fragments?.template?.includes('default') === true,
          `${manager} installed add did not list template/default`,
        );

        const copied = await runInstalledLiteshipCli(['add', 'template', 'default'], appDir, manager);
        journeyAssert(
          copied.code === 0,
          `${manager} installed add copy failed (exit ${copied.code}):\n${(copied.stderr || copied.stdout).slice(-1200)}`,
        );
        const receipt = parseReceipt(copied.stdout);
        journeyAssert(receipt['status'] === 'ok', `${manager} add receipt status was ${String(receipt['status'])}`);
        journeyAssert(receipt['command'] === 'add', `${manager} add receipt command was ${String(receipt['command'])}`);
        journeyAssert(receipt['kind'] === 'template', `${manager} add receipt kind was ${String(receipt['kind'])}`);
        journeyAssert(receipt['name'] === 'default', `${manager} add receipt name was ${String(receipt['name'])}`);
        journeyAssert(receipt['dest'] === 'default', `${manager} add receipt dest was ${String(receipt['dest'])}`);

        const fileCount = assertCanonicalCopy(join(appDir, 'default'));
        journeyAssert(receipt['fileCount'] === fileCount, `${manager} add receipt fileCount was not ${fileCount}`);
        copiedCounts.set(manager, fileCount);
      } finally {
        removeDir(join(appDir, '..'));
      }
    }

    return {
      name,
      status: 'pass',
      detail:
        `npm (${copiedCounts.get('npm')} files) + pnpm (${copiedCounts.get('pnpm')} files) installed CLIs listed and ` +
        'copied template/default byte-identically from the canonical create-liteship source',
      notes: [],
    };
  } catch (error) {
    return { name, status: 'fail', detail: error instanceof Error ? error.message : String(error), notes: [] };
  }
}
